### ISSUE TITLE
Improve Uploader

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1038]
From https://github.com/owncloud/android/issues/903#issuecomment-111843850:
What about some kind of "Upload new" window in the app, which isn't part of instant upload, but basically:
1. Shows thumbnails of all new photos and videos since the last upload
2. Allows users to preview each
3. Allows easy multi-selection and
4. Uploads all selected with a single click.

@Bugsbane that sounds like a pretty clever thing. Perhaps you can even just take the current upload dialog and let it hide things (behind a 'previously uploaded' button) which are already on the ownCloud server...

Even better. Maybe a "Hide previously uploaded" checkbox or something.

**Comment by jack71** [comment]
great idea i appreciate that :+1:

**Comment by Bugsbane** [comment]
Yes, I think it's an excellent idea to just add functionality to the current upload window, rather than creating a second one.

From a UX perspective, I would suggest that in the vast majority of use cases, users are only likely to be wanting to upload things they haven't already uploaded before. In those cases it would be one less interaction step for users if previously uploaded files are hidden by default, as long as it is made *very clear* what is happening and how to see the full list if needed.

I'd suggest that what is currently the file selector window have a toggle switch at the very top labelled "Show all files". By default it would be off, with two statuses: "Only show files which have not been uploaded" and "Show all files, including previously uploaded." Underneath would be the file list, like this:

![new-uploads-1](https://cloud.githubusercontent.com/assets/401733/8397329/e99bf73e-1d95-11e5-948d-39ac3bc48941.png)

Another alternative that I don't like as much, but would take less screen space up top, would be to hide the toggle in an options (3 dot) menu, and then for people who didn't think to look in there, down the bottom of the list of files, we could add a button that said "Show all files / Including files already uploaded." Presumably, anyone who couldn't see their file would scroll to the bottom of the list and see this button. I don't think this option is as clear as my first suggestion, but it does save on screen real estate, leaving more room for the file list, so I'm adding it here anyway:

![new-uploads-2](https://cloud.githubusercontent.com/assets/401733/8397344/54356fbc-1d96-11e5-8c38-7b2a41e1fbdc.png)

As I said before, my preference would be the first suggestion. It's more consistent with Android UI and clearer to users who don't know the option exists.

**Comment by jab416171** [comment]
I prefer the first option. We should try to stay as close to material design as possible.

I'm not sure if any of you have used the Photos app in Lollipop, but I really like its interface. There's an option in the drawer to see "Device folders", and from there, you can choose to back up the entire folder with a toggle per folder. This would be great for the folder that holds all of your pictures.

Additionally, under "Backup & sync", there's toggles to back up while roaming, while charging, and while on Wi-Fi, and a "Back up all photos & videos now (if connection settings allow). I realize this is just for backing up photos & videos, but we could probably adapt most of the UX (Simply taking out "Photos" or "Videos" would probably work just fine) to work with any folder.

**Comment by jab416171** [comment]
Here's some screenshots from the Photos app:
![device-2015-06-28-113805](https://cloud.githubusercontent.com/assets/345752/8397495/566c930c-1d8a-11e5-8350-0fa9d2d25b9d.png)

![device-2015-06-28-113855](https://cloud.githubusercontent.com/assets/345752/8397496/5c9ceb82-1d8a-11e5-8f58-2e8928aaf1c8.png)

**Comment by Bugsbane** [comment]
@jab416171 - There's another issue filed somewhere on here that's specifically about backing up and syncing multiple folders to ownCloud. Your comments are probably more relevant on that one if you can find it, than on an issue about uploading images not yet uploaded via the file selection window.

**Comment by jab416171** [comment]
alright, thanks @Bugsbane. I didn't realize that.

**Comment by masensio** [comment]
This issue contains:
https://github.com/owncloud/android/issues/1015
https://github.com/owncloud/android/issues/899

**Comment by tobiasKaminsky** [comment]
@Bugsbane You mean #744 ?

**Comment by Bugsbane** [comment]
I think so, yes.

**Comment by roy128** [comment]
:+1:
