### ISSUE TITLE
Missing retry-option for instant upload

### ISSUE THREAD

**Issue by alex42ka** [owncloud/android#1062]
Sometimes an instant upload is failing. If this happens I'm getting an error message which is stating that it failed. But there is no option to retry the upload (or even an option in the settings to automatically retry it after some minutes or so).
When I'm clicking on the error message I'm just redirected to the folder in which my pictures should be uploaded. Makes the owncloud app nearly useless for me at the moment because I can't trust that everything is just working.

**Comment by LukeOwncloud** [comment]
> Makes the owncloud app nearly useless for me at the moment because I can't trust that everything is just working.

Agreed. 

This issue is discussed here: https://github.com/owncloud/android/issues/340#issuecomment-121250921. Closing this issue.

If working uploads are more important than a current version and a developer/test/debug version is okay for you, you can download my proposed fix here: https://github.com/LukeOwncloud/android/releases/tag/1.6.2
