### ISSUE TITLE
Extend PassCode to use password from owncloud

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1064]
from #1060:
Add an option to use the password from the owncloud account instead of the pinCode to make the app more secure.

**Comment by davivel** [comment]
@jancborchardt , @LukasReschke , any thoughts about usability and security impact?

cc @MTRichards

**Comment by MTRichards** [comment]
Cool. How is the passcode stored on Android today?

**Comment by davivel** [comment]
The password is saved through the ```AccountManager``` system service. Under the hood, it stores the password in clear text, in a database owned by the system, readable with root permissions or through the ```AccountManager``` API, that requires the process accessing to a password is the same process that stored it (more or less).

Low level details to access the password in http://developer.android.com/reference/android/accounts/AccountManager.html#getPassword(android.accounts.Account).

(This detail was also discussed in #605)

**Comment by jancborchardt** [comment]
@davivel @tobiasKaminsky well, using a pin code has big usability and security advantages:
* much easier and quicker to type
* doesn’t have the potential to visually leak your password

Also seeing how the other prevalent apps mostly do it with pin code instead of a password, I would actually keep it that way.
If a bunch of people really fervently (and with good arguments) request this then maybe we can think about it. But seeing as it probably introduces a bunch of code and complexity, we shouldn’t jump to implement it based on a one-time request.

**Comment by sd1998** [comment]
@davigonz  Is this feature needed? I would like to work on it.

**Comment by michaelstingl** [comment]
I don't really see a use case for this. Maybe someone(tm) can explain?
