### ISSUE TITLE
Show green download indicator on folder when all folder contents are downloaded

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1075]
When using the »Download« function on a folder, it would be good to have the green arrow on the folder as feedback when all files/folders in there are on the device. Otherwise it’s pretty confusing and one might think it didn’t work.

This is probably also an issue with iOS. @rperezb @davivel @masensio @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Will this still work when #819 is merged? As @davivel proposed not to distinguish between local and cloud files?

**Comment by davivel** [comment]
This is a tricky one to make with full precision. The etag of a folder is modified whenever a file inside (in any sublevel) is modified, deleted or created. Due to this, when we refresh a folder we know immediately if something changed inside, but not what. If the meaning of the badge is 'everything downloaded', check the next sequences:

Seq  A
1. in the smartphone, download /folder/ successfully ; enable green badge
2. from the web, add a new file /folder/new.png
3. in the smartphone, pull down to refresh /

Seq B
1. in the smartphone, download /folder/ successfully ; enable green badge
2. from the web, update the content of /folder/old.png (downloaded previsouly in 1.)
3. in the smartphone, pull down to refresh /

In the step 3 of both we know by the etag of folder that something changed, but we can't distinguish the case, so can't know if everything is still downloaded or not.


@tobiasKaminsky , my proposition of not distinguishing local Vs remote files is as a general behaviour. That doesn't mean that the information about local cache is not useful, known that we consider the Android devices as contrained in storage.

**Comment by jesmrec** [comment]
for this one, av. offline is the proper way.
