### ISSUE TITLE
No remote thumbnail in App (OC server 8.1.1)

### ISSUE THREAD

**Issue by BearTi** [owncloud/android#1126]
Hi,

I´ve a problem with the preview/thumnails in the ownCloud App.
When I´m uploading Images via the DektopClient and then open the App I see no preview of trhe images I uploaded before. So I´ve to download the hole image.

When I´m taking a pgoto and the picture is synced directly I see the preview in the App.

Any Idea?

Thanks

(I´m using ownCloud 8.1.1)

**Comment by tobiasKaminsky** [comment]
Is image preview working with the web frontend of your owncloud?

**Comment by BearTi** [comment]
Yes, this does work!

**Comment by tobiasKaminsky** [comment]
Can you try to connect with the android app to the official demo account:
demo.owncloud.org
user: test
password: test

**Comment by tobiasKaminsky** [comment]
@BearTi any update regarding my question?

**Comment by TheBR** [comment]
Hi,  I'll take this on as i have the same issue and have done some investigations to narrow it down.

The problem is as follows - please read.

demo.owncloud.org works, as will a connection to your own server, thumbnails WILL be shown however ONLY if you have generated the thumbnails by browsing via the web interface first.

Here's an example.

Copy one or more pictures to your Owncloud instance, preferably manually via linux command line etc so Owncloud itself isn't involved. 

So if your sharing a "Pictures" directory, copy a few pictures to subdir "Pictures->Test".

Now using your android app - browse to the server and open the Pictures directory then Test, you will NOT see thumbnails other than the default thumbnails.

Now using Owncloud Web interface on a Desktop, browse to your server and goto Pictures->Test again - you will now see thumbnails for your pictures.

Now go back to your Android app and refresh - you will now also see Thumbnails.

Essentially, unless you use something other than the Android app the thumbnails do not get generated, you need to have browsed the directory with your pictures in it with the Owncloud web client first before thumbnails get generated and then the Android app can always see them.

This is also why the demo.owncloud.org test will work.

However, the Android app fails to trigger generation of thumbnails in a directory if none exist.

**Comment by tobiasKaminsky** [comment]
@TheBR As far as I know all file handling (create, update, delete) must be done via an official way: webdav, desktop or mobile client as otherwise owncloud is not aware of a file change.
Therefore your test is not valid and must fail.

**Comment by TheBR** [comment]
Ok, so how does Owncloud handle file shares etc? This also used to work also prior to version 8.

Either way - i think my test was over complicated, here's a more "official" way of doing it.

Add a directory of pictures via Owncloud web interface however do not then go into that directory via the web interface.

Browse to the newly added directory via the app - no thumbnails.
Browse into it via the web interface - thumbnails get generated.
Back to the app - thumbnails.

**Comment by BearTi** [comment]
I also reproduced the problem:

1) I put some photos in my windows folder and the ownCloud Client synced the photos my ownCloud-Server (Webhosting).

2) I opened the app -> no thumbnails

3) I browsed to the folder via web-interface ->  thumbnails get generated.

4) Back to the app - thumbnails.

So. same like TheBR decribed just via windows client...

**Comment by tobiasKaminsky** [comment]
This is the issue in /core
https://github.com/owncloud/core/issues/18417
