### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by guettli** [owncloud/android#1173]
What does the development roadmap of owncloud-android look like?

Where is the focus of the developers today, tomorrow, ...?

What are the next steps?

What will be done later?

**Comment by tobiasKaminsky** [comment]
There is the label "roadmap" for issues.
Beside that you can see the open pull requests, which will be merged sooner or later.
To see the next steps, you can browse the milestones.

**Comment by guettli** [comment]
I see. Github issue tracking system gets used for this. Do you think this is a good tool for strategic planning?

**Comment by tobiasKaminsky** [comment]
Sorry, it is called "0 - Backlog": https://github.com/owncloud/android/labels/0%20-%20Backlog
Relating the "strategic planning": I do not know if the guys from owncloud using something else.
This is maybe related to #1067

**Comment by rperezb** [comment]
@guettli as @tobiasKaminsky has already pointed the focus of the Android team today and in the near future is: https://github.com/owncloud/android/milestones/1.8.1-current

What will be done later? Certainly, we will take care of the pr, for instance https://github.com/owncloud/android/pull/821, this is a very big one so the idea is to work on it on small pieces, meaning this, dividing it in different pr so that we may qa it and add the functionality

If it´s ok for you, since this is a similar topic to #1067 we may follow the status there in order to avoid duplications. 

About the tool, the whole ownCloud project it´s using GitHub; should you have any suggestion, please, let us know, we are open to know and to evaluate them. Have in mind that the requirements are to be open source and integrate with gitHub
