### ISSUE TITLE
Deletion/modification of owncloud files from "outside"

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1175]
from @joede: 

> Just a stupid question. If other tools like QuickPic can see the images, can these tools delete these files too? If so, what happens to the sync process? Does the ownCloud client sync the deletion of the file?

from @tobiaskaminsky:

> @joede The deletion of the local file on the device is not synced to the server.
> But I do not know, if the app is noticed about the deletion.
> I bet that the app tries to open the local file and fails as it is not there OR the app downloads the file again (which is most likely)

from @joede: 

> @tobiasKaminsky so the OC app should disallow modifications of the filename and deletions. Is this possible?

**Comment by tobiasKaminsky** [comment]
I do not know if it is possible that an app is restricting its files to other apps.
As far as I know they are either "public" or "private". But with private no other app can access these files.
But as long as the app does not sync the changes, that are made on the device, back to the server, I guess it is fine, or?

**Comment by joede** [comment]
My thought was the following. The image is moved to the OC folder and than synced to the server. The app saves the state "file has local copy and is synced".  No he file is deleted without the notice of the app. What happens after this?
On my notebook I sync files with Unison. If I delete a file, this *deletion* is synced to ownCloud. I don't know the internals of the OC app, so I don't know how a "missing" file is handled. But the app must ensure, that an actions in the background doesn't lead to the loss of data.

**Comment by tobiasKaminsky** [comment]
There is currently no 2way sync, so the app will not notice/track that the file is deleted.
In the nearer future there will be 2way sync, but I guess that it is then adjustable how to behave or which folders should be synced two way.

**Comment by davivel** [comment]
Not exactly.

The app notices if the local file is deleted, and it will appear as not downloaded as soon as the folder containing it is refreshed. This will happen whenever the user browses into it, or automatically if full-account sync is enabled.

In the past was decided not to propagate this deletion to the server, since files are stored in public storage and any app in the device might delete them with zero barriers.

There are some open issues regarding 2-way sync, and can be  considered again in them. About the scope of this issue, I think everything is answered. If I'm wrong, please, reopen it.
