### ISSUE TITLE
Open with is shown empty on Android 5 devices when there is not an installed app to open the file

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1182]
STEPS TO REPRODUCE
1.- Download a file whose extension can't be handled by any app installed on the device
2.- Select open with

EXPECTED BEHAVIOR
A text is shown letting the user know why it is not possible to open the file

CURRENT BEHAVIOR,
See attached image, it´s shown emtpy

![screenshot_2015-10-01-14-17-04](https://cloud.githubusercontent.com/assets/1846927/10220466/0f2bbdac-6848-11e5-92b9-259c00b19ab8.png)

NOTE.
Android 4 works fine

ownCloud android version, 1.8

**Comment by rperezb** [comment]
@AndyScherzinger likely to be related to the material design

**Comment by AndyScherzinger** [comment]
I am away from keyboard for the rest of the week, but will have a look.

**Comment by rperezb** [comment]
Thx, no hurries!

**Comment by AndyScherzinger** [comment]
@rperezb fixed in PR #1190

It wasn't a material bug per se but rather the standard behavior on Lollipop (open with without any choice in case the chooser is launched). I implemented a check if there is any app awailable to handle the mime type and if not simple show the text (implemented throughout all android versions).

**Comment by masensio** [comment]
Fix in master with PR #1190.
