### ISSUE TITLE
Downloading files

### ISSUE THREAD

**Issue by ghost** [owncloud/android#1188]
Hi,
I personally find it rather annoying to have each file I open stored locally on my device.
Would it be possible to make opening/viewing a file seperate from downloading it. So that it's streams it from the server so to say. Much like dropbox and other cloud storage providers, one can simply tap an audio file and stream it. Other documents should be stored temporarily, such as word documents (unless I press download, and thereby specifically ask for it to be permanently stored locally) Because now I find myself having to remove each and every file I open from my device.

Thanks

**Comment by tobiasKaminsky** [comment]
At least for images this is done in #1044. The file is also resized to fit to the display size on the server and therefore only a very small file (~50kb instead of 5Mb) is being transferred.
This file is cached internal just like the other thumbnails.

**Comment by LukeOwncloud** [comment]
This request reminds me of this discussion. https://github.com/owncloud/android/issues/588
Unfortunately, no solution nor compromise there...

**Comment by JasperWeiss** [comment]
Could this be looked at, please. The fact that I have to manually delete each and every file really makes owncloud a no-go for me.

**Comment by tobiasKaminsky** [comment]
Do not rush! There are several issues that belong to this and that are a lot of older.
See #592. I am already working on it. Also #1044 is handling images.
And furthermore, you do not have to delete every file on its own. Just go to the parent folder and delete this with "only on device".

Replacing the download functionality to a version where the files are not permanently being stored was already discussed. Conclusion was not to change the current behaviour as this behaviour allows to sync files and let external apps use the downloaded files (without opening them from OC).

**Comment by enoch85** [comment]
> Replacing the download functionality to a version where the files are not permanently being stored was already discussed. Conclusion was not to change the current behaviour as this behaviour allows to sync files and let external apps use the downloaded files (without opening them from OC).

But it should still be able to choose the behavior. This has been, and will be an ongoing discussion until something happens, or someone does something to solve it. 

I started a discussion in #588 that I now reopened when I saw that this still happens, and there is no plan to change it. I actually use another app to sync my pictures now a days, mainly because of this behavior and that the devs are so unwilling to change it.

It would be a better solution to solve it the other way around - *don't* download automatically when viewing, but let the user *choose* when to download the files, in all the other cases, just show the file.

**Comment by tobiasKaminsky** [comment]
Just have a look at the beta version.
There is video streaming and images are stored in a resized version in cache and are only saved if the user choose to.
> devs are so unwilling to change it.

Is very harsh and not friendly at all!
There is a *big* difference between having good reason to do it in one way and ignoring the users.

**Comment by LukeOwncloud** [comment]
And most important: It *was* changed. Setting cache size to 0 will not store any images permanently.

**Comment by enoch85** [comment]
@tobiasKaminsky Sorry! Wrote that in without knowing that you solved it. I was a bit upset, since this has been know for several years, and no one did something about it. You the other hand - is a life saver! https://github.com/owncloud/android/issues/588#issuecomment-154876312

And thanks @LukeOwncloud for pointing me int the right direction.

**Comment by jesmrec** [comment]
to do as part of https://github.com/owncloud/android/issues/3289
