### ISSUE TITLE
Quick battery drain after hitting "refresh"

### ISSUE THREAD

**Issue by jharris0221** [owncloud/android#121]
Multiple of my main folders don't show any subfolders when viewed via the Android app.

So I then hit "refresh" in the file list, it never seems to complete and you just get the progress circle going on forever. Afterwards, I usually go back about my business. However, after hitting refresh, it then causes a ton of wakelocks, and quickly drains the battery.

If I do that, I have to force close the app, and the issue resolves. Interestingly, if you restart the app but don't try to refresh anything, the instant upload feature works fine and doesn't cause this issue.

**Comment by masensio** [comment]
Hi @jharris0221,

We have done some updates of the app and some changes in synchronization process. Do you still have the battery problem?

**Comment by sebmaynard** [comment]
@masensio I've got this issue as of today; fresh install of the OwnCloud mobile app yesterday, this morning ownCloud has used 33% of my battery (according to the power status thing in Settings) with my phone in "awake" state since.

I have 3 folders in my ownCloud - one with around 150,000 files (music, photos) and clientsync that only has about 500. 

I only opted to sync a single text file from the clientsync folder and it's taken my battery from 100% this morning to around 45% now (in < 5 hours) - this is on a 1 week old Galaxy Note 4, that previously would outlive 2 days on a single charge

**Comment by davivel** [comment]
@sebmaynard . 

Please, open a new issue with your problem, If I understood your case, the battery problem is related to the keep-in-sync option, not the refresh button.

Closing this issue due to lack of response.

**Comment by sebmaynard** [comment]
@davivel "I opted to sync" - sorry if I was unclear, I meant "get this file once onto my device, so it that is in sync"! I didn't choose to keep-in-sync.
