### ISSUE TITLE
Full-height material drawer?

### ISSUE THREAD

**Issue by The0x539** [owncloud/android#1210]
So I looked through the couple issue and PR threads pertaining to the Material redesign, and all I can tell is that at one point in the screenshots the drawer went at least up to the status bar, but then it started stopping at the app bar. Can't seem to find an issue pertaining to this, so...

### Expected behaviour
The drawer goes from the nav bar, or bottom of screen with hardware buttons, to the top of the screen, or at least to the status bar.

### Actual behaviour
The drawer stops at the app bar, almost certainly intentionally

### Steps to reproduce
1. Open app drawer, using hamburger button or edge swipe.

### Environment data
Android version: 5.1.1
Device model:  OnePlus One
Stock or customized system: Customized (CyanogenMod instead of Cyanogen OS)
ownCloud app version: 1.8.0
ownCloud server version: 8.1

Are logs relevant with intentional behavior?

Sorry if this is the wrong place, I wasn't quite sure where this goes.

**Comment by AndyScherzinger** [comment]
This is the right place and a known behavior :(
I will look into it but it will unfortunately take some time since I am quite busy at the moment.
When I implemented it it worked as you described it while I was using a toolbar instead on an action bar but the toolbar had a lot of problems with setting the back navigation right. Thus we felt back to the action bar. Not sure if this can be tackled with the action bar but I'll check.

**Comment by AndyScherzinger** [comment]
discussion and possibly an implementation has been moved to #1556

**Comment by davivel** [comment]
Merged, will be released in version 2.2.0.
