### ISSUE TITLE
Owncloud Android doesnt like Android 6 Marshmallow

### ISSUE THREAD

**Issue by TheBR** [owncloud/android#1262]
Hey all,
  Took delivery of a Android 6 enabled phone yesterday and put the Owncloud app on it. It does not like it one bit to be honest, frequent black screen / crash and upload is not working.

I did notice that at no time was i asked for permissions management, this is new in Android 6 in that permissions are supposed to be requested as an when they are needed rather than at install time via marketplace and i'm wondering if this is to blame (access to storage etc).

Anyone else using Android 6 ATM who can confirm?

**Comment by AndyScherzinger** [comment]
I run Android 6 and do not have any of the errors you mentioned popping up. The permission management is an Android 6 feature, true. But it needs code changes in order to work like that, else it simply works as designed on pre-Android 6 (so nobody to blame :wink:).

So permissions would be a new feature which could be implemented in a backwards compatible manor using AppCompat. 

At this moment if you installed 1.8.0 you are running an app compiled for Android 5.1 which also (should) work on Android 6.

Are you running the app on a new Phone like Nexus 5x or 6P or on an older phone like the nexus 5?

**Comment by TheBR** [comment]
Hi,
  I'm running on a Nexus 6P - i previously reported a permissions a few days ago here on Android Lollipop using the Owncloud appliance, https://github.com/owncloud/android/issues/1239, and playing around a bit im tempted to think its that again - BUT!

Its weird though, i can upload from my Desktop no problem, but uploading via the owncloud app i have issues.  

As an example, i can upload a text file from the App, from the download directory of the phone no problem, but not a zip file. Or from another directory i can upload an XML file but not another file ending in txt.0

Log files show as follows:-

{"reqId":"Z6XcbeJPPNFB1hQ177B6","remoteAddr":"192.168.0.1","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-11-06T09:41:14+00:00"}
{"reqId":"Z6XcbeJPPNFB1hQ177B6","remoteAddr":"192.168.0.1","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#92","level":3,"time":"2015-11-06T09:41:14+00:00"}

If it were permissions i would expect nothing to be able to be uploaded?

**Comment by AndyScherzinger** [comment]
>  (Cannot modify header information - headers already sent by)
Might be the issue, I guess. 

I run ownCloud 8.1.3 so this might be due to the newer serverside. Since I can only update my server via the updater I can't test it since it'll still be some days to go until 8.2 becomes available.

@LukeOwncloud @tobiasKaminsky @rperezb anyone running 8.2 and exeriencing the issues mentioned here?

**Comment by tobiasKaminsky** [comment]
I have no Android 6.0 installed, so I can, for now, help here...

**Comment by TheBR** [comment]
Well, I've been testing a few things today and in the process i deleted and then recreated my account on the app for the connection to the server. 

Since doing this it seems to be fine uploading everything now, even files that were failing previously are now uploading Ok. I have a theory that it may be to do with entering my site name in a way which it failed to properly create a secure connection with the server, perhaps causing an issue with SSL / Port redirection at the server side etc, but i don't know for sure.

I'll close this off but thank you all for your time and assistance.

**Comment by elpraga** [comment]
I am using OC 8.2 and Android 6. Instant upload is working for me. Let me know if I can help You by sending some data.
