### ISSUE TITLE
External storage added with "use session credentials" do not show in android app

### ISSUE THREAD

**Issue by Larx** [owncloud/android#1284]
Before OC8.2, I had several external storages (SFTP) mounted on a per-OC-user base, so every user had to enter login and password to use the external storage. As I use LDAP, all user's logins are the same, so this was quite a bit of double work.

Now I switched to OC 8.2's new method to use session credentials. I globally added the external storage with this option, so OC logs in every user with his or her OC credentials to the SSH server.

This works fine in the web interface and with normal WebDAV-access.

The android app, however, does not even display the external storage mounted with "use session credentials".

**Comment by dbenz04** [comment]
I also have this same issue. Is this a known issue in this app? I see very few reports of this problem.

**Comment by jebrown55** [comment]
Same issue here on Android 5.0

**Comment by Larx** [comment]
Never got any feedback on this bug report :-(

**Comment by AndyScherzinger** [comment]
I don't have any knowledge in this area, so looping in @davivel and @masensio

**Comment by dbenz04** [comment]
Andy, thanks for following up. We have done some more testing and the issue seems to be isolated only to workplace devices managed with Maas360. I'm not sure what Maas360 could be blocking to only cause external storage to not show up in OwnCloud, because regular OwnCloud folders do work. I'll continue to investigate to see if I can determine what Maas360 may be doing in this situation.

We have tested this with the OwnCloud client from the Play Store as well as the Beta from a few days ago - same results.

**Comment by dbenz04** [comment]
After investigating this further, this issue is very strange. Maas360 is not the problem, some users can login on devices with Maas360 and see their external storage. Others cannot see their external storage no matter what android device they login on. 

All users can see the external storage when logging into the iOS app, through the sync client or the web browser. WebDAV on a computer works for everyone as well. WebDAV from Android devices has mixed results - some the external storage right away, others have to refresh the WebDAV client to see the external storage.

We are using LDAP via Active Directory for all user accounts, and the accounts with the Android external storage issue seem to be older accounts. All AD accounts created in the last couple of months work fine. I don't know what this means, but I am following this rabbit hole now and investigating further.

**Comment by AndyScherzinger** [comment]
Thanks @dbenz04 for further investigating this issue. @jancborchardt do you know anyone from the server dev team who could have a look at this issue just to make sure the server side isn't the originating source (shouldn't be since iOS clients seem to work). But maybe it is some change that needs changes on Android?

@dbenz04 did you do any Server updates regarding the ownCloud version?

**Comment by dbenz04** [comment]
This is a new server install that is only a couple weeks old - it is the community maintained virtual appliance running OC8.2.2 on Ubuntu 14.04.

**Comment by dbenz04** [comment]
After much investigating, I believe I have found the source of the problem. Most of our LDAP users have a photo associated with their AD account, usually in both jpegPhoto and thumbnailPhoto. Every  OwnCloud user with an LDAP-provided avatar photo cannot see their external storage in the Android client. 

To test this theory, I added a photo in AD for one of the users whose account was previously working on Android. After logging in through the web interface and seeing the new profile avatar, I tried the Android client again. This user can no longer see their external storage.

As I mentioned in a previous post, using a separate Android WebDAV client kind of works - Initially no external storage is shown for these users, but if you use the refresh button within the app the storage appears. Using the "refresh account" option in the Owncloud Android app does not show external storage.

Since disabling syncing of LDAP photos/avatars woudl presumably fix this issue, does anyone know how this could be accomplished? I've looked around several config files and database tables, but don't see an obvious way to disable this behavior.

Should I report this as a bug?

**Comment by AndyScherzinger** [comment]
Yes, please! :) The LDAP part/question would be a server question in my opinion. Stil that issue should reference this and we should keep it open for now until the server team can provide some more insights. Since there might still be an issue on Android (since you mentioned it works on iOS and with other webDAV clients.)

pinging @davivel @masensio - what do you think?

**Comment by jancborchardt** [comment]
cc @DeepDiver1975 for server input

**Comment by AndyScherzinger** [comment]
@rperezb this might be the corresponding issue to https://github.com/owncloud/core/issues/21555 - not sure though...

**Comment by rperezb** [comment]
@AndyScherzinger certainly, yes, it seems to be the same environment
Key:
- LDAP /AD server with avatar
- External storage  with session credentials

**Comment by rperezb** [comment]
good catch, @AndyScherzinger

**Comment by AndyScherzinger** [comment]
--> https://github.com/owncloud/android/issues/1284#ref-issue-125643366 :grin:

**Comment by davivel** [comment]
@Larx , @dbenz04 , @jebrown55 , is it possible that any of you upgraded to OC server 9.0.1? In that case, could you check if the bug persists for you?

Thanks in advance.

**Comment by Larx** [comment]
I have removed all avatars from LDAP, so I unfortunately cannot check anymore. Otherwise, session credentials work fine.

**Comment by dbenz04** [comment]
I have 9.0.1 installed on a test server. The ldap avatar/android bug seems to be fixed. I can access external storage using session credentials with an ldap avatar from the android app.

**Comment by rperezb** [comment]
this has been fixed on the server side (https://github.com/owncloud/core/issues/21555) 
If after upgrading this didn't work, please reopen the issue
thx
