### ISSUE TITLE
[Duplications] [1168] Setting view not updated after changing the behavior

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1312]
With the branch: https://github.com/owncloud/android/pull/1168

STEPS:
1.- Access to settings:
2.- As Behavior it´s shown: Do nothing
3.- Tap on behavior and change it to move file to OC folder

EXPECTED BEHAVIOR
On the settings view it´s shown:  move file to OC folder

CURRENT BEHAVIOR
On the settings view it´s shown: do nothing
If you change the device orientation, it´s updated

Device
HTC 4.1.2

**Comment by tobiasKaminsky** [comment]
This is working for me with nexus 4 and nexus 5 in emulator.
Maybe @AndyScherzinger (our design dev :) ) has an idea?

**Comment by AndyScherzinger** [comment]
I'll have a look, but need proper internet access for cloning/checkout.

**Comment by rperezb** [comment]
Double check it, the view on a mobile device is not refreshed, however, on a tablet, it's

**Comment by tobiasKaminsky** [comment]
What devices and android versions have you tried?

**Comment by AndyScherzinger** [comment]
Hmm strange. It seems this is specific to some Android versions even though I don't know which of them. This (https://github.com/owncloud/android/commit/35a68aa33766f43f9b190a4b67be327051e04ca4#diff-ffb88170f459941fc1526888859e39aaR80) should take care of it and change the summary value. Else I can see if implementing a onSharedPreferenceChangeListener which does this manually: http://stackoverflow.com/questions/531427/how-do-i-display-the-current-value-of-an-android-preference-in-the-preference-su or http://stackoverflow.com/questions/4823442/android-list-preferences-have-summary-as-selected-value

**Comment by tobiasKaminsky** [comment]
Where do you have merged your commit? I cannot find it ;)
I think it belongs in #1168?

**Comment by AndyScherzinger** [comment]
Exactly, see right be my comment here: https://github.com/owncloud/android/pull/1168#issuecomment-143574628

**Comment by tobiasKaminsky** [comment]
Ah. Thought it is a new commit.
So, the problem exists even with your fix?

**Comment by AndyScherzinger** [comment]
I didn't tryout any of the possible fixes described here: https://github.com/owncloud/android/issues/1312#issuecomment-160197665 
since we have summary="%s" Android should take care of it, but it seems that at least on @rperezb device (HTC) with Android 4.1.2 it doesn't 
--> so I am not sure how to fix the summary display (anything else seems to work for her). It always works for my and you, so I can only add some code and @rperezb would have to test it.

**Comment by rperezb** [comment]
Hey, I have checked it with:
View not refreshed, mobile handsets
- Galaxy Nexus 4.2.1
- Galaxy S3, 4.1.2
-  HTC ONE 4.3

View refreshed:
- Tablet nexus Android 6

(Code https://github.com/owncloud/android/commit/5d77cfc62d8f5018b44adc4832d372674c956128 )

**Comment by AndyScherzinger** [comment]
Good morning @rperezb. Does that mean it only works on the tablet for you?

**Comment by rperezb** [comment]
hey @AndyScherzinger checked with another device, a tablet Nexus 7 Android 4.3, the view is not refreshed till you change the device orientation or go to another view and go back to settings (as with the other devices)

**Comment by AndyScherzinger** [comment]
@rperezb I think I found the mistake, it is related to Android versions rather than tablet/phone. I was relying on the change listener mechanism of setValue which is a feature that has been introduces with Android 4.4 (API 19). So I added some pre API-19 handling for this :) - For details please see https://github.com/owncloud/android/commit/4f7d416b81d42e26b7c36d673f76ddf460f4500e committed against #1168 branch and already pushed to the beta branch @tobiasKaminsky  :)

Please let us know if this works for you :)

**Comment by rperezb** [comment]
great!

it worked
:clap: :clap:

**Comment by AndyScherzinger** [comment]
Glad to here that :smiley:
