### ISSUE TITLE
Clearing application data removes passcode

### ISSUE THREAD

**Issue by quincunx** [owncloud/android#1325]
If the application data is cleared via app info (Settings > Apps > ownCloud > Storage > CLEAR DATA), then the PIN is removed, too. But as the account info is kept, starting the app again will give one access to the account without any PIN code.

Tested on Nexus 5 with Android 6.0 and ownCloud Android App 1.8.0.

**Comment by przybylski** [comment]
Clearing data is a system setting and application data (SharedPreferences) cannot hide from it, since it is controlled by system. This is a security thread which doesn't have a simple way of handling.

**Comment by tobiasKaminsky** [comment]
The only way is to also remove the account details when doing "clear data".

**Comment by przybylski** [comment]
Since 'clear data' is a system feature I guess app cannot remove account (because it doesn't know when data was cleared).
The way out is instead of putting pin into shared preferences create a dummy file which would be encrypted by this PIN, and if decryption succeeds then we can unlock app.

**Comment by tobiasKaminsky** [comment]
"clear data" also deletes the storage in /sdcard/owncloud/account-name or?
If this is true, then we would have an indicator: account folder is missing for existing account entry and then delete also the account entry.

**Comment by przybylski** [comment]
No it is not removing data folder

**Comment by davivel** [comment]
cc @rperezb @MTRichards @cmonteroluque 

To solve it we'll need:
1. Move all the information of the Account from current storage (AccountManager) to app database; (possible exception: account password; or maybe not)
2. Update all the code dependent of 1; not so bad as seems; specially important: code validating account and redirecting to log-in Activity when invalid.
3. Grant that the information of the accounts is correctly migrated for the existing users when the app is upgraded.

This way, when "clear data" is clicked not only the PIN will be removed, but also the account information, and the app will request log-in.

**Comment by przybylski** [comment]
Please don't move Account information from AccountManager to app DB, the whole point was to have oc integrated with system, so android could schedule synchronizations of files (those "keep in sync" as well as file list), or maybe those functionalities were owned by some other app component?

**Comment by przybylski** [comment]
And BTW why not use http://developer.android.com/reference/android/accounts/AccountManager.html#KEY_USERDATA to store PIN information?
This could lockup single account instead of whole app (but locking entire app is also possible).

**Comment by davivel** [comment]
The point is keep the minimum information available in the AccountManager, this is:
  - accountName
  - password (maybe not)

And use the accountName to access the rest of the Account data in the app database.

If I'm not wrong, keeping the accountName and the SyncAdapter (registered through syncadapter_files.xml) should be enough to keep the integration in the device accounts.

**Comment by przybylski** [comment]
SyncAdapter requires Account to in onPerformSync method which is called by the system, this would need to be triggered by hand

**Comment by davivel** [comment]
Yes, and that Account only contains Account#name and Account#type ; Account#name is used to recover data from KEY_USERDATA, but could be used instead as an index to recover data from a table in the database, since onPerformSync receives also a ContentProviderClient to access the database.

**Comment by przybylski** [comment]
Userdata is Parcelable so it can store anything. I don't see a point of moving account data to app

**Comment by davivel** [comment]
The point is getting that when a user clicks the button 'Clear data', the account data are also cleared :)

We can explore your proposal to store the passcode in the AccountManager tomorrow, I can't go on today.

**Comment by przybylski** [comment]
I made a simple POC code to illustrate that assigning pin data to account.
This changes survives data clear.
Code is available here https://github.com/owncloud/android/tree/POC_account_pin

**Comment by przybylski** [comment]
Only this change is relevant: https://github.com/owncloud/android/commit/f7155df0d9db44860dad876baa0496218c51aa41 but it's basing on bug_1251 branch which made some changes to how passcode is processed

**Comment by davivel** [comment]
Sorry for coming back so late.

IMHO, setting a passcode per account is not the way to go. That is the role of the account passwords. We would have a situation where the users would need to remember two different secrets per account (or at least, per passcode-protected account). Sounds pretty uncomfortable.

To get protection per account, a simpler option would be asking the user for the account password instead of a different passcode. Instead of an option "Passcode", we would have a checkbox "Request password in UI access"  (better text needed). Should be requested in the same situations as the passcode now, and in account switches.

This would be, conceptually, an important change in the passcode behaviour. Not sure how would be received by current passcode users. 

cc @MTRichards , @rperezb 

Personally, I prefer the option of moving account data to the database (except account names and maybe passwords) to get the "Clear data" button clears more data. Would require more effort and care, but I think it honors better the idea that users have of the meaning of that system action.

**Comment by przybylski** [comment]
I never said that password should be per account (altho it could) but we could attach password data to account, so password will survive data wipe.
Moving password to application itself will erase all account information and force users to setup their account once again.
Personally I am using data wipe from time to time to remove cached resources and related stuff.
Setting my 3 accounts again would be a pain in the butt after moving account data to app itself.

**Comment by quincunx** [comment]
From a user's point of view, I agree with @przybylski 
The reason why I discovered this issue was that the app kept crashing again and again. I suspected some corrupted cached data, therefore I used the feature to clear the application data (and it solved the issue).

**Comment by davivel** [comment]
If attached to the account, but not per account, then the passcode should be saved multiple times, repeated in all the accounts. Otherwise, the user could remove the account that stores the passcode and lose the passcode accidentally.

Alternatively, we could save the passcode in a single account, and move it to other existing account (if any) when the account is removed. Might be possible via AccountAuthenticator.getAccountRemoveAllowed(), but I'm not sure that method is granted to be called when the account is removed from the device settings for every device model. 

In both cases the implementation seems tricky.



On the other hand, I understand the concern about entering again the accounts when only trying to recover from a corrupted state. Of course, the right solution for that should be not getting to a corrupted state, but reality... 

About using data wipe periodically just to remove cached resources, that could (probably should) be added as an app feature. Shouldn't be the use case for that entry in the device settings, though I admit that's the only option available right now.

Moreover, although both use cases are handy for the savvy user, removing account information, though uncomfortable, is perfectly consistent. The warning message on the button clearly states tat accounts information will be deleted. 

Need to think a bit more. I will check what other apps with accounts do in this case, as a reference.

**Comment by davivel** [comment]
And I just discovered the existence of the attribute ```application:manageSpaceActivity``` to attach to the app. Poorly documented (being generous) http://developer.android.com/intl/es/guide/topics/manifest/application-element.html , and apparently replacing the system button "Clear data" by a button "Manage space" that opens the Activity of our app we want.

This is AWESOME, since gives our app total control about what is cleared or not. This way we can grant that the PASSCODE survives or not, whatever we feel.

Coming back soon.

:)

**Comment by masensio** [comment]
We are developing in the branch ```manage_space_activity```

**Comment by davivel** [comment]
Solved via #1461
