### ISSUE TITLE
Unknown error ocurred!

### ISSUE THREAD

**Issue by sermilrod** [owncloud/android#1336]
Hi,

The android client for owncloud is throwing the following error when trying to connect over HTTPS:

"Unknown error ocurred!" after testing the connection.

I just updated recently to core version 8.2.1 and suddenly the mobile connectivity stopped working. 

I am using nginx + php5-fpm (5.6.16-2+deb.sury.org~trusty+1 (fpm-fcgi)) in ubuntu 14.04 and the nginx config is directly the config you provide in the official documentation.

I put here a capture of nginx logs when the mobile app tries to connect:

 [08/Dec/2015:19:12:54 +0000] "GET /status.php HTTP/1.1" 200 106 "-" "Mozilla/5.0 (Android) ownCloud-android/1.9.0" "-"

It seems like the webserver responds properly but the mobile app fails to connect.

I am trying to connecto from a Nexus 5 with Android 6.0, but this is also reproducible in other mobile phones and in Android 5.x

This is getting very annoying and I would be very please if you could take a look.

Thanks in advance.

**Comment by tobiasKaminsky** [comment]
what is said when opening the your server within the browser? http://yourdomain.de/owncloud/status.php?

**Comment by sermilrod** [comment]
that works perfectly fine. Access via browser and desktop applications look good.

**Comment by sermilrod** [comment]
I am still wondering why the application prompts such a undescriptive message of error, and how could that be fixed

**Comment by davivel** [comment]
Hi, @sermilrod. We need some information to help you.

Did you update the ownCloud app recently? Before or after updating your server? Was the previous version working fine?

Did you update the app from Play Store, F-Droid or any other store? Did you upgrade, or made a clean installation?

Do you use a self-signed certificate in your server? 

Did you change your server certificate recently?

Could you show us the info shown by the browser in the URL that @tobiasKaminsky specificed before?

Thanks in advance.

**Comment by guik67** [comment]
Hi,

Same issue here and solved it with adding the 'trusted_domains' parameter in config.php

Try to acces your owncloud via your mobile web browser, it should tell you to add the trusted domains.

Hope it helped

**Comment by davivel** [comment]
Thanks, @guik67 , but if this was the same problem...

> that works perfectly fine. Access via browser and desktop applications look good

... probably some of this would be failing too.

@sermilrod , are you using the same URL to access from web browser, desktop client and Android client, right?

**Comment by sermilrod** [comment]
Hi @davivel. I didn't update the app recently. As far as  I know I've got the latest version available for my android device.

Regarding the certificate, yes, I am using a self signed certificate. Could that be the main focus of the problem? However, that is something that haven't been happening before. I am using the same URL to access the application from browser, desktop and android app.

The result of calling the status.php endpoint is the following:

curl -k https://mydomain/status.php?
{"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":""}

Thanks in advance for the assistance.

**Comment by tobiasKaminsky** [comment]
Issue and possible fix in #1394

**Comment by sermilrod** [comment]
I hope it fixes it. I just replaced my self signed certificated for a trusted one and the error is persistant. When is scheduled the release of the new fix?

**Comment by sermilrod** [comment]
By the way, this is a PAID application and this is urgent as we paid for a product we cannot use.

**Comment by tobiasKaminsky** [comment]
@sermilrod this is not a real fix but only redirect the user to status.php in order to see if there is something misconfigured (like the trusted domains).
But your problem seems to be different.
Can you access with your mobile app the official demo owncloud? 
https://demo.owncloud.org
user/pass: test / test

**Comment by sermilrod** [comment]
Hi @tobiasKaminsky I am able to connect to the demo from my mobile app. That makes me think that the issue is at the cert validation process, or the SSL negotiation phase. Is it trying to validate something in particular to establish the secure connection?

**Comment by tobiasKaminsky** [comment]
Unfortunately I am not that into the ssl process (and not into nginx at all). 
@davivel might help you better with that.

**Comment by sermilrod** [comment]
Any progress in the case?

**Comment by JoKeyser** [comment]
Same problem here, using a freshly installed client 1.9.0 from F-Droid on Android 4.4.4. (I've never used the Android client before.)
It's working with `demo.owncloud.org`.

My server is Debian jessie, with nginx 1.6.2. I'm running ownCloud 7.0.4.2. This was upgraded from wheezy not long ago, but web-access and Desktop clients work fine.
Checking with `/status.php` yields `{"installed":"true","version":"7.0.4.2","versionstring":"7.0.4","edition":""}`.

In `/var/log/nginx/access.log`, I get e.g.
```
[12/Jan/2016:18:10:49 +0100] "GET /status.php HTTP/1.1" 301 184 "-" "Mozilla/5.0 (Android) ownCloud-android/1.9.0"
```
In `/var/log/nginx/error.log`, I get e.g.
```
2016/01/12 18:10:49 [alert] 24938#0: worker process 25728 exited on signal 11
```

Let me know if you'd like more logs.

**Comment by sermilrod** [comment]
In my case, I don't see error in nginx or syslog so that might be unrelated if you are having the same problem. 

Any progress in this case? It has been month and a half without solution.

**Comment by kiwiASRALL** [comment]
Same issue here... After uninstall and reinstall app, I can't connect to my owncloud...

**Comment by sermilrod** [comment]
It would be great some developers feedback on this case, just to know if this is being tackled or what is going to happen with this situation.

**Comment by davivel** [comment]
@sermillrod, since you changed your SSL certificate, please, try the next steps:

1. Go to your device settings (out of the ownCloud app) > "Apps" > "ownCloud"
2. Click the button "Clear data" ; in Android 6 you will need to click first on "Storage"; this will clear all the app data, including previous certificates.
3. Try to log in again.

Besides, could you tell us where did you install the app from - Play Store, Amazon?

What version of the app are you using? (available in device settings > "Apps" > "ownCloud" too).

How is structured your URL? I mean, is there a path after the domain, such as "/owncloud/", or other?

Thanks in advance.

**Comment by davivel** [comment]
@JoKeyser , your log seems slightly different. Your server is behind a permanent redirection, right? Is there any other log message from "Mozilla/5.0 (Android) ownCloud-android/1.9.0" after that one?

Are you entering the "https://" prefix as part of the URL?

Could you try to input the IP of your server instead of the domain in the URL input field? The final IP, after the redirection.

Thanks in advance.

**Comment by sermilrod** [comment]
Hi @davivel 

I have tried to clear application data and it does not fix the problem I am afraid.

I have installed the 1.9.0 version of the application and I installed it from Play Store.

Regarding the URL there is no extra path after the domain, I access the application by using https://mydomain.com/

I hope this helps.

Thanks!

**Comment by davivel** [comment]
@semilrod, would you create a test account in your server and send it to apps@owncloud.com ?  I could test it directly that way, if you will. Please, include in the subject the text "Issue #1336".

**Comment by sermilrod** [comment]
You should have now the information you need.

**Comment by davivel** [comment]
@sermilrod , seems there is an unexpected line break in the header 'Strict-Transport-Security' , right before 'includeSubdomains'. Usual web browsers seem deal with this problem, but unfortunately our network library doesn't, and reports an HTTP protocol violation. 

The same as in #1203 

Please, check your server configuration to remove the line break, and tell us how it results.

FYI: we didn't get to use the credentials, just the server URL.

**Comment by sermilrod** [comment]
Thanks, I will test it by the end of the day and I will tell you something.

**Comment by davivel** [comment]
@JoKeyser , @kiwiASRALL , are you also using HSTS in your servers? Thanks.

**Comment by sermilrod** [comment]
Mobile app is working now @davivel thank you very much for the assistance.

**Comment by davivel** [comment]
Happy to hear it, @sermilrod.

Let's keep the issue open a while to get feedback from @JoKeyser and @kiwiASRALL .

**Comment by sermilrod** [comment]
Sure, I have no problem with that. Thanks again!

**Comment by tobiasKaminsky** [comment]
@davivel while the cause of the error is solved, would it not be better to make the library more robust against such typo errors? 
I know this can be a very hard work to solve all cases, but maybe just start with this and the cause of the linked issue #1203?

**Comment by davivel** [comment]
> I know this can be a very hard work to solve all cases

@tobiasKaminsky, that's the problem, and that's why there is a generic "Unknown error" message.

In this case, there is not much we can do to handle the error, unless we totally switch the current HTTP library to another one. At most, we could show an specific error message for exceptions about HTTP violations, but that's still quite generic. I wouldn't print the message of the exception itself because, first, these messages hardly help the users to understand the problem; second, could result in dump of information that would be better not to dump for security reasons.

The topic of switching to a different HTTP library has been discussed recently, and probably will be done quite soon. Very carefully.

About #1203, its cause is **exactly** the same as the cause of this issue. What makes me wonder...

@sermilrod, did you set the line with the HSTS by yourself, or was it in a configuration file provided by the ownCloud package? Sounds suspicious that different users have this issue from independent sources.

@JoKeyser , @kiwiASRALL , any feedback from you? Could you check your HSTS configuration? Thanks.

**Comment by AndyScherzinger** [comment]
Just as a side note. We should switch the HTTP lib at some point anyways with Android v23 due to the fact that Google deprecated Apache HTTP in Android 23. For now I implemented the workaround to include the apache http legacy jar to be able to use it also in v23. SO we can/should move to another HTTP lib but at least for v23 we don't need to move right away.

**Comment by davivel** [comment]
@AndyScherzinger , the app is not using the Apache HTTP deprecated by Google (maybe there are some references to constants in it, but nothing else, if I recall correctly). The  owncloud-android-library includes its own version of Apache HTTP Client in a JAR file, even older than the version deprecated by Google in Android, but independent of it.

**Comment by AndyScherzinger** [comment]
@davivel Ouh, didn't know that. But you are right then even though this will be tricky when we update to Android M since we then either ship an legacy apache jar or change the implementation.

Easy to fix would be:
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/activity/ShareActivity.java#L52

I (slightly) larger fix would have to be done for:
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/syncadapter/AbstractOwnCloudSyncAdapter.java#L27

**Comment by sermilrod** [comment]
I have my custom deployment @davivel , I do not make use of the owncloud package. 

My nginx config is the same as it was except for that bit that I had to put in one line instead of putting it in separated lines. You could print out a more descriptive error instead of "unknown" or just simlpy have it documented in the default config for nginx so that the next person does not make the same mistake.

I think that making a note in the documentation would be a good option to avoid this kind of issues while you decide in development weather to change the library or do something else.

**Comment by davivel** [comment]
@sermilrod , excuse my ignorance about Nginx. Could you tell me what's the name of that configuration file, where is it located? 

Would you remember if you entered manually the problematic property in separated lines, or if you copied it from a trusted reference?

**Comment by sermilrod** [comment]
The configuration was inside a vhost in nginx and looked like this:

add_header Strict-Transport-Security "max-age=63072000; 
includeSubdomains; 
preload";

upstream php-handler {
  server 127.0.0.1:{{ fast_cgi_port }};
}

server {
  listen {{ port }};
  server_name {{ server_name }} www.{{ server_name }};
  # enforce https
  return 301 https://$server_name$request_uri;
}
.
.
.

So you can see at the very beginning that the configuration for the header is split up in several lines, it is just a way to type in nginx. The issue we had is that the library does not handle the header sent in such way. The solution is to put them in one line like this:

add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";

upstream php-handler {
  server 127.0.0.1:{{ fast_cgi_port }};
}

server {
  listen {{ port }};
  server_name {{ server_name }} www.{{ server_name }};
  # enforce https
  return 301 https://$server_name$request_uri;
}

I hope it helps and do not hesitate to ask if you need something else.

Cheers!

**Comment by davivel** [comment]
Helps a lot. Thank you so much.

**Comment by davivel** [comment]
Note added to documentation in https://github.com/owncloud/documentation/pull/2156 .

Backports in its way for previous server versions.

Thanks everybody.

**Comment by Andrew908** [comment]
Hello, 

I am having the same issue as @sermilrod, but the recommended fix isn't working for me. I tested the owncloud in every web browser and the owncloud windows application is working. Can you please tell me how I can test to see where it is failling the owncloud android app when trying to connect to my server. I have the nginx configuration in the manual and the owncloud version is 8.2.3. 

Kind regards,

**Comment by davivel** [comment]
@Andrew908 , would you mind to open a new issue, add more details about your environment (similar to those in the first comment here), and link this issue there? That would help to follow the state of the topic and prevent that the details of your setup are mixed with those that were already working.

Thanks in advance.

**Comment by Andrew908** [comment]
@davivel I have fixed the issue. It was a setting in nginx that needed to be configured globally instead of specific to the vhost. 

Thank you

**Comment by orloxgr** [comment]
> @davivel I have fixed the issue. It was a setting in nginx that needed to be configured globally instead of specific to the vhost.
> 
> Thank you

What setting a where? Please explain.
