### ISSUE TITLE
Client keeps scanning directory even though it should not be synched

### ISSUE THREAD

**Issue by d-t-o** [owncloud/android#1379]
### Expected behaviour
it should be possible to not autosynch/refresh specific folders.

### Actual behaviour
the client is relentless and goes on for hours, ~~synching~~ scanning a folder that was removed locally, until the phone runs out of battery.

i have a directory in my owncloud storage that i do not want to synch on my phone as it's rather big (~2GB). what i've done so far is select the directory in the client, select 'remove' and then 'local copy only'. i'm not sure if this is supposed to disable the synching of this directory from that point on, but as i see no other setting where i can exempt this folder, i guess it should.

### Steps to reproduce
1. have a rather big folder in your owncloud (~2gb in my case)
2. wait.

### Environment data
Android version: 5.1

Device model: Moto G LTE 1st gen

Stock or customized system: stock

ownCloud app version: 1.9.0

ownCloud server version: 8.1.2

#### Web server error log
this goes on for hours:
```
PROPFIND /remote.php/webdav/that_folder/[...]
```

#### ownCloud log (data/owncloud.log)
there are no entries from the time the issue occured.

**Comment by davivel** [comment]
Hi, @d-t-o.

> what i've done so far is select the directory in the client, select 'remove' and then 'local copy only'. i'm not sure if this is supposed to disable the synching of this directory

Sorry, that's not what you're searching for. That action deletes the local copy of any file in that folder that is downloaded in the device, but has no effect in the way the folder is synchronized or refreshed in the future. 

What you want is selective sync (or not sync), a feature not available in the app, that is already requested in #960 (and maybe in other issues).

About the specific problem of draining the battery, there is a bug fixed in #1359, already merged, that will be available in the next version. Meanwhile, I only can suggest you to disable the automatic synchronization of the account in your device settings.

So, I'll close this issue since it's duplicated in the matter of selecting folders not-to-sync in #960, and fixed in the matter of battery draining in #1359. 

Thank you very much.
