### ISSUE TITLE
Automatic upload works only sometime

### ISSUE THREAD

**Issue by CriticalNoob** [owncloud/android#1380]
What I'm doing :
-Check automatic picture upload
-Check only wifi

What is happening :
-Nothing most of the time
-If I'm on wifi + owncloud in the background + I take a picture : It uploads it

What I'm expecting to happen :
-Should upload all the pictures that has been taken when I didn't had wifi
-The app shouldn't have to be launched to upload pictures

 Some suggestion :
-Maybe a way to disable the owncloud notification / icon on each upload.
-Are the weird kind of "loading" dots on the top of the app made on purpose ? They look weird.
-Users should be able to chose the folder name for auto upload, if you have more than one device it is a mess.

Thanks for reading :)

**Comment by tobiasKaminsky** [comment]
This should work the way you want it already...
But I have currently no clue how to check why it does not work.

your suggestions:
1: no notification is not customisable but there is an issue that should reduce the amount of notifications
2: what/where are those loading dots?
3: this is already possible. please see settings.
(and please open in the future different issues for each question)

**Comment by LordCrush** [comment]
Same here only uploading, if photo is taken when WLAN is connected
Best Rgards
-LD

**Comment by tobiasKaminsky** [comment]
Hmm. Maybe the app is not being notified when switching back to wlan.
What kind of device (and android) do you have?

**Comment by CriticalNoob** [comment]
For some reason it now works well, I tried to reinstall it and basic stuffs but suddenly after a reboot, it began to work.
FI I'm using a Honor 7 - Android 5.0.2.

For the white dot I was speaking about that :
![screenshot_2015-12-29-14-12-56](https://cloud.githubusercontent.com/assets/7241431/12034829/9794899c-ae36-11e5-94ae-86fd990ddb7e.png)

But maybe I should open another ticket ? Or is it a feature ?

**Comment by tobiasKaminsky** [comment]
The "white dots" are indicating that a sync is in progress.
For further explanation/discussions we should open a new issue.

**Comment by freddano** [comment]
I'm sorry if I'm bumping an old thread, but I might have found the "cause and solution" to this problem.

I also have an Honor 7, running Marshmallow. The Honor 7 seems to have an aggressive powersaving-mode, in which it closes apps which aren't specifically allowed to run in the background when it shuts down the screen or you lock your phone.

I gave owncloud permission to keep running in the background, and I've since been running some tests, a few hours apart, and now automatic upload seems to work just the way it did with my nexus 5.

I hope this helps someone.
