### ISSUE TITLE
Connection Problem on WLAN Networks with fast bss transition

### ISSUE THREAD

**Issue by fmoessbauer** [owncloud/android#1387]
### Expected behaviour

The File should get uploaded normally (like if using only 1 AP).
### Actual behaviour

The Uploader gets stuck / does not finish. With very many APs not even a folder can be accessed in the app.
### Steps to reproduce
1. Connect to a WIFI with fast bss transition enabled (for example "eduroam" (Wifi of most universities), or other wifi networks with many access points)
2. Try to upload / auto upload a file. If the client roames in this period, the uploader gets stuck.
3. With very many APs no folder can be accessed in the app.
### Environment data

Android version: 4.3

Device model: Samsung Galaxy S3 (i9300)

Stock or customized system: Stock and Custom (occures on both)

ownCloud app version: 1.9.0

ownCloud server version: 8.2.2

**Comment by AndyScherzinger** [comment]
Hmmm, I guess we need to check why the upload gets stuck and hwo to deal with this in case it is possible since the is imho rather an Android issue. Looking at:
https://code.google.com/p/android/issues/detail?id=22575
https://code.google.com/p/android/issues/detail?id=19068
ans especially at:
https://code.google.com/p/android/issues/detail?id=17972

proper wifi roaming need support for 802.11r which seems to be available on Lollipop and  later versions :(

Can you check if this also happens with lollipop devices?

**Comment by fmoessbauer** [comment]
With Android 6 the problem does not exist any more. Tested with Cyanogenmod 13 (I have no "native" Android 5 device) on a Galaxy S3.

Thank you for your investigation.

**Comment by AndyScherzinger** [comment]
Glad to hear that. From the links my guess is it won't happen on Android 5 either.  
@davivel @przybylski @masensio @tobiasKaminski is there anything we can do to restart stuck uploads and downloads or would this be covered by the reliable uploads work?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger restarting broken downloads is part of reliable uploads.
Best would be, of course, to resume them (but I do not know if this is supported by the server)
