### ISSUE TITLE
Idea for enhancement: Add the possibility to rotate images

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1390]
The beta app is already a very powerful and handy image viewer, and as it provides the option to view previews without having to download the original and to control the cache size, it became my viewer of choice for many occasions.

Would it be too hard to add the possibility to rotate the photo? I know it could be tricky as sometimes we only have the preview, and it would only make sense, if the rotation got uploaded automatically to server, but..

What do You think?

**Comment by tobiasKaminsky** [comment]
Great idea!
We will have to see if there is already an API on server side that supports this.

**Comment by AndyScherzinger** [comment]
One thing we should then consider is auto rotation based on the photo meta data. Modern cameras and cellphone cameras store this information thus the picture "knows" if it is landscape or portrait and could be displayed accordingly. But this might be a totally different topic. Not sure though. 

Is this the main reason why you asked for image rotation (and persisting this rotated image)? 
Because if so I would rather go for auto rotation based on meta data.

**Comment by tobiasKaminsky** [comment]
Auto rotating is already enabled

**Comment by AndyScherzinger** [comment]
oh okay, didn't know that. Nice! :+1:

**Comment by elpraga** [comment]
I just ask if there is an API.

https://github.com/owncloud/gallery/issues/494

**Comment by tobiasKaminsky** [comment]
If this should be included in the app it must not depend on a "third party"/optional app but must be always included in ownloud/core.
Otherwise the app always has to make sure if the api for rotating exists.

**Comment by elpraga** [comment]
Thanks for clarifying.  I'll wait for an answer from the gallery app as it
might interest them as well and if this is the case,  I'll mention that it
should be handled by core.

**Comment by AndyScherzinger** [comment]
I agree with @tobiasKaminsky for the use case of doing it on the server side. Since image rotation might be an image only action it might not make sense to implement it in core (just to support this mobile use case). If this is the case I would say this could then be handled completely on the client side (with its up- and downsides).

**Comment by elpraga** [comment]
I got the response from Gallery app developer:

```
If an Android app can rotate a picture and modify it's metadata, then once it's uploaded to ownCloud again it should show up with the correct rotation in ownCloud.

It should be possible in the future to rotate images from within Gallery. See #236
```

So it makes it quite clear that they are not too interested in the feature and core does not support it right now :)
