### ISSUE TITLE
Account creation: unknown error links to status.php

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1394]
When the message "unknown error occurred" is shown, there is now also a link to the status.php of the owncloud instance.
This helps with the "untrusted domains".

![unknown](https://cloud.githubusercontent.com/assets/5836855/12048847/8a47f990-aee0-11e5-90fa-f5f541c50c8e.png)

**Comment by tobiasKaminsky** [comment]
PR is #1395

**Comment by davivel** [comment]
I'm not trying to ruin the day but, how is this helpful for a *regular* user?

**Comment by tobiasKaminsky** [comment]
When clicking the link it could reveal that the ip of the server is not set correctly in the config.
So, yeah, it is a one-timer right after the installation, but from reading the issues here and in the forum this problem occurs quite often and it is a quick and easy "fix" to help provide the user more informations.

**Comment by davivel** [comment]
My point is that a regular user will have no idea what that means. I mean, somebody that is not tech-savvy. 

We need to give feedback to the users as clear as possible. I'd rather to improve the error message, being more concrete about the problem, or even inviting  the user to contact the server admin, instead of this. 

In the end, parsing that URL is exactly what has been done by the connection test. There is nothing there that we couldn't explain to the user in the error message.

**Comment by jesmrec** [comment]
Not planned to fix
