### ISSUE TITLE
Three dots per list item

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1396]
- show three dots per list item, showing all action that are possible with one selected item
- long press initiates multi select

(as discussed in #1346)

**Comment by tobiasKaminsky** [comment]
cc @AndyScherzinger @jancborchardt

**Comment by cornzy** [comment]
@jancborchardt is it realy necessary to have these three dots per list item?

Like in most other apps (e.g. Mail, Gallery) I think it is fair to open the Item and use the menu in the next screen. In the list I only want to perform an action for multiple Items, that's why we need the multi select.

The three dots per item is known from apps like 'Play Music' where you cannot "open" an item because it simply playback the song.

Maybe if there is a favorite action like "share" it is helpful to provide this action directly (in Mail it is "mark as favorite"). Indeed in the current version I am always confused by the share-icon on the right edge and I always want to click it to change my sharing. For folders and grid view we already have the icon on the left, maybe just add an overly for other icons and image previews? (I know, new issue but maybe related)

Further more you could use a swipe right for delete (also maybe new issue).

**Comment by jancborchardt** [comment]
> In the list I only want to perform an action for multiple Items

This is only an assumption though. Actually people want to quickly act on files no matter the view. You shouldn't need to switch to the detail view to be able to quickly share a file. (Sure long press is possible, but hard to discover.) It should be very fast directly from the list as well, just like in the web interface.

**Comment by malkomich** [comment]
Yes, in the web interface the three dots are shown, but I'm not sure if in mobile interface the user will find comfortable having lots of dots around the screen.

**Comment by jancborchardt** [comment]
@malkomich we discussed it multiple times before and I’m not in the mood atm to restart the whole thing again. Short version:
- mobile apps and web interface should work similarly
- actions need to be findable
- check what competitors like Dropbox do

-> Let’s add the 3-dots. It’s just an icon in every row, and 50% transparent like in the web interface. The current long-press to get to the actions is just not discoverable.

**Comment by tobiasKaminsky** [comment]
Hmm. I thought that this will be replaced all by multiselect?
Long pressing initiates multiselect and depending on 1 or >1 items the three dot menu changes?

(Sorry to reopen the discussion)

**Comment by AndyScherzinger** [comment]
Imho the solution was to have both.

**Comment by jancborchardt** [comment]
Yup, both. Only long press is not discoverable enough for normal people.

**Comment by supportreq** [comment]
we should replicate what dropbox or google drive is doing.. single click opens the content menu [the arrow button in dropbox or the three dots in google drive] in google drive if long pressed it starts multi select..

**Comment by AndyScherzinger** [comment]
@supportreq and that is exactly what we discussed/decided if I am not misreading the discussions :)

**Comment by jancborchardt** [comment]
Yep, confirming that is what was discussed @supportreq :)

**Comment by jesmrec** [comment]
Continue here -> https://github.com/owncloud/android/issues/2885
