### ISSUE TITLE
Highlight current view in sidebar, use »On device« as header title

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1427]
When I started the ownCloud app where I left off, I was initially confused about how little files where there. Turns out I was in the »On device« filter, with no indication.

Hence whenever the current view is a filter (anything else than »All files«), that filter should also be used as the title in the header.

Additionally, the current view should have a highlight in the sidebar. Darker icon & text for example, like we do in the web interface.

**Comment by AndyScherzinger** [comment]
Just a slight addition, standard way to highlight a sidebar item would usually be to collor the background of the row in light gray. Would that work for you?

**Comment by jancborchardt** [comment]
If that's the standard way, yeah.

**Comment by AndyScherzinger** [comment]
It is at the moment yes. So that should be easy to implement :) 

So for collaboration @tobiasKaminsky I think you implemented this, would you be able to take care of the header title in the action bar? I can take care of the visual changes in the drawer (independently).

**Comment by AndyScherzinger** [comment]
Would it be fine with you to move to the new support lib navigation view (already part of the used support lib...)? That is the view to render the menu items, example: http://antonioleiva.com/navigation-view/

**Comment by jancborchardt** [comment]
Seems like that's what we should go for.

**Comment by AndyScherzinger** [comment]
Alright :+1:  I'll will see if and when I can start working on it. Unfortunately quite busy the next few days... :disappointed: 

The new implementation would then make use of menu-structures again which support grouping, thus we could then:
* either not add settings but put it at the bottom of the drawer
* or add it in a separate group since afaik groups are then seperated with a grey divider (just the groups)

I am fine either way even though I haven't yet implemented any drawer with the newly provided support lib API.

**Comment by jancborchardt** [comment]
Yeah, no hassle here. The really important thing is the "On device" header for immediate feedback. The rest is polishing.

**Comment by AndyScherzinger** [comment]
As soon as "on device" is merged to master, the drawer menu coming with PR #1559 will be able to mark that one in the menu. The Toolbar title would have to be set be the implementation that takes care of the "on device" view/filtering.

**Comment by jesmrec** [comment]
Filters removes from there. Nothing else to do.
