### ISSUE TITLE
Move storage path and passcode/PIN down to »Advanced« settings section along with cache size

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1431]
As said in the title. This will clean up the settings and have them sorted by importance/usage:
1. Accounts
2. Instant upload
3. Advanced
4. Additional links

**Comment by jancborchardt** [comment]
This current unsorted Settings area keeps annoying me. ;)
Anyone up for the task @AndyScherzinger @tobiasKaminsky @Kernald @stoyicker @LukeOwncloud? :)

**Comment by LukeOwncloud** [comment]
You are referring to "storage path" of instand uploads, right? So the whole section "instant uploads" should rather be a single item, which opens a new submenu when pressed? I'd like that. About "password". It is currently available via long click on any account. Isn't that as it should? Where should "pin protected" go?
@jancborchardt Could you perhaps provide a complete overview of the menu structure how it should be making clear what is a section within the menu and what is a submenu?

**Comment by jancborchardt** [comment]
@LukeOwncloud sorry for the misunderstanding – by »Password« I mean the passcode/PIN (updated the title) and by Storage path I mean the new setting in the beta of where the data is stored (either on the device or on external SD). See https://github.com/owncloud/android/pull/1293 by @przybylski 

This is a simple request to move these entries lower down. The instant uploads section is fine as it is, and I would advise against nesting them further because that makes them less accessible.

**Comment by AndyScherzinger** [comment]
Logs has been moved to "more" (#1552). Anything else is not yet present on master and should thus be done in their respective feature branches referencing this GH issue.

**Comment by jancborchardt** [comment]
@AndyScherzinger since you asked for next stuff interface-wise, I’d say this is reasonably easy (I guess ;) but high-impact.

**Comment by AndyScherzinger** [comment]
@jancborchardt in general yes, I can do this extremely quickly in case I know exactly hwo it should bne sorted, but unfortunately I do not :( Since the 1 level Order isn't enough here.

Actual Screenshot from beta:
![beta](https://cloud.githubusercontent.com/assets/1315170/14682693/077f6a26-0727-11e6-9277-0859ee412475.png)
NICE: Logs are moved to bottom/preferences, Accounts have been moved to their own manager screen :dancer: 

Actual ~2.0.0
![191](https://cloud.githubusercontent.com/assets/1315170/14682708/185c477e-0727-11e6-8f9c-1e5a3ef2d0bf.png)

So Looking are your wish:
1. Accounts
2. Instant upload
3. Advanced
4. Additional links

and looking at 2.0.0
1. Accounts
2. Instant upload
3. Details
4. More

So this seems to be solved (at least for 2.0.0)

**Comment by jancborchardt** [comment]
Yeah, in 2.0.0 it's correct – the beta is strange but that's because several diffent PRs introduce sections, right? They should all go in »Details« – to be renamed to »Advanced«.

**Comment by AndyScherzinger** [comment]
Okay :+1: That shouldn't be too much of an issue to do but like you said the preferences are introduces by several PRs so we need to keep an eye on this whenever the PRs get merged back to master.

**Comment by jesmrec** [comment]
Settings were already re-structured.
