### ISSUE TITLE
Move Settings to bottom of sidebar, move Log to Advanced settings

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1432]
First one to separate the settings from the actually daily useful filters. And then in the beta, the log entry should also be in the settings, advanced section. (Which I described in #1431)

**Comment by AndyScherzinger** [comment]
@jancborchardt should we really move the log entry? The log entry is only shown:

* in the beta: so users can provide us with logs to support finding bugs 
* in the regular app when installing a debug build: so it is a dev feature only

both kind of make sense being accessed easily without having to navigate through the setting, wouldn't you agree? I am fine either way since being a developer means I use the IDE's console anyways. So if you think is simplifies the UI we can move it to the settings. No problem! :)

As for the settings item I'll have to check since the list is basically a menu rendered as a list. So it should be possible by removing it from the list and put in a separate bottom aligned item just for settings :)

**Comment by AndyScherzinger** [comment]
Would it be finde with you to move to the new support lib navigation view? That is the view to render the menu items, example: http://antonioleiva.com/navigation-view/

**Comment by jancborchardt** [comment]
Yeah, the reason I'm not happy with the log entry there is that the main interface elements of the beta should look exactly like the normal release. :)

When an actual error occurs, the log is presented anyway. And when you want to get the log, the extra step into settings is ok.

**Comment by AndyScherzinger** [comment]
Oh, okay didn't know that. So yeah, when the log pops up anyways in case of an error than we can move it into the settings. :)

**Comment by AndyScherzinger** [comment]
@jancborchardt just a general question wouldn't it make sense that if we move the menu entry for log to the settings screen to also make it available in the standard release? If so we might need some discussion with @davivel and @masensio on when to purge the log. For background processes like instant uploads etc. it might make sense to provide access to a log for reporting issues here. On the other hand but that again might be a privacy discussion would be automated error reporting to a central server like crashlytics which would be a whole other level of discussion, so I would postpone that one.

**Comment by jancborchardt** [comment]
@AndyScherzinger sure! Then it could be in the »Advanced« section on the bottom, with PIN, Storage path and Cache size.

**Comment by AndyScherzinger** [comment]
Logs has been moved to the settings screen, please see: #1552

**Comment by AndyScherzinger** [comment]
Settings would be slightly seperated in the menu with the latest Drawer PR #1559

**Comment by davivel** [comment]
> wouldn't it make sense that if we move the menu entry for log to the settings screen to also make it available in the standard release?

Sorry, I don't think so. Logs are a diagnostic tool for administrators and / or developers (depending of the context). Logs are not useful for regular users.

For example, I want my mom uses ownCloud. She always has a hard time just to understand folders, files, and handle all of them. She has a harder time to understand syncing. I can't even imagine what she would think about a view with log messages.

I don't have any problem with put the access anywhere in the app, but I think that showing the option only for debug builds is the way to go.

**Comment by tobiasKaminsky** [comment]
I would also hide the LogView.
But maybe a possibility to share a log after an app crash via email, etc. is a good idea?

**Comment by davivel** [comment]
It's a good idea if we complete the context.

Apps distributed through Play Store offer the user sending crashes to Play Store, without need of adding anything to the app.

What other environments should we cover? What would be the default target of the e-mail / automated push?

**Comment by tobiasKaminsky** [comment]
For F-Droid a native crash report (like in Beta) would be cool.
In Beta there is no default target. It is mainly a text intent that is shared. So every app that can receive text is a possible recipient.

**Comment by jancborchardt** [comment]
Sounds good – don’t show it for normal people, but bring it up when relevant (on crash). That’s how Firefox also does it.

**Comment by AndyScherzinger** [comment]
@jancborchardt #1552 is ready to test and moved the Log-menu item to the preference screen. ATM the log item is only available in debug mode but implementation now also includes a feature toggle (off by default) so that configuring during build time the item could also be made available in official releases.
 
So that is one thing to discuss: Should the log be accessible in the releases via the preference screen?

We now will have moved it to the preference screen so it is a bit hidden but would still give the user the chance to access it in case we need this info for bug hunting else it could not be accessed at all in case some weird behavior happens.

**Comment by AndyScherzinger** [comment]
merged to master thus be in the next release. So closing this issue :)
