### ISSUE TITLE
Mention CalDAV/CardDAV address somewhere in the app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1436]
Currently we talk exactly _not at all_ about the Calendar and Contact syncing functionality of ownCloud. This is the cause of lots of negative reviews and people asking to integrate full-blown Calendar/Contacts sync into the app.

So to alleviate this a bit and to make it easy for people to copy/paste the address, we should do some small things in the app:
- Show the CalDAV/CardDAV address in the app settings (new section »Calendar & Contacts sync«), so they can be copied
- Advertise a CalDAV/CardDAV client, like [DAVdroid](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=en) (that one is open source)
- Mention the ability for Calendar & Contacts sync in the first run slideshow.

Same for the iOS app, save for the CalDAV/CardDAV client because iOS supports that natively.

cc @karlitschek @DeepDiver1975 (as talked about) and @rperezb @MTRichards @tobiasKaminsky @AndyScherzinger

**Comment by DeepDiver1975** [comment]
> Advertise a CalDAV/CardDAV client, like DAVdroid (that one is open source)

I'd even go a step further - talk with the developers of DAVDroid and CalDAV/CardDAVSync on how to integrate.

The ownCloud client has all information at hand and can setup the accounts automatically.

**Comment by przybylski** [comment]
To go even further calendar & contacts should be moved to separate app and all essential classes (including authentication & account) to common library. file app should not become a monolithic monster.

**Comment by DeepDiver1975** [comment]
> To go even further calendar & contacts should be moved to separate app and all essential classes (including authentication & account) to common library. file app should not become a monolithic monster.

we don't want to add caldav and carddav sync into the owncloud app - other apps are already doing a great job here - we simply should integrate with them and setup the accounts.

**Comment by GIJack** [comment]
> we don't want to add caldav and carddav sync into the owncloud app - other apps are already doing a great job here - we simply should integrate with them and setup the accounts.


and why not? It is the most widely requested feature. Do you hate us? Do you like annoying us? Do you utterly hate the concept of owncloud being a production grade solution? Are you going to charge extra money for a version with the contacts/calendar/notes integrated? Are you living under a rock and do not understand modern interface concepts of 2016?

What. What is your fucking problem? Please let it not be because of some dogmatic attachment to the UNIX design vision to not understand why its not relevant on the cell phone.

**Comment by strugee** [comment]
@GIJack language like that isn't appropriate for this tracker. In the future please take a couple deep breaths before commenting and remember that the people working on ownCloud are real human beings who are just doing what they honestly think is best.

As for Unix, it was successful for a reason. Unix principles, generally speaking, lead to a more robust and flexible solution. Of course that doesn't mean that everything under the sun should adhere to the Unix philosophy, but it _does_ mean that there are tradeoffs.

Adding features is not free. They need lots of initial time to develop and then regularly require additional time for maintenance, not to mention that it could make other work take even more time due to the increased codebase complexity. In this particular case, it just doesn't make any sense to allocate resources to this when there's a perfectly functional and frankly very good external app that does the same thing.

**Comment by michaelstingl** [comment]
contacts and calendar aren't in scope of the ownCloud Android app
