### ISSUE TITLE
Can't share the current folder

### ISSUE THREAD

**Issue by strugee** [owncloud/android#1441]
It's possible to share a folder if you go to its parent and select it, but it's not possible to share if you descend into the relevant folder.

I'm on beta 20160109.

**Comment by tobiasKaminsky** [comment]
This also happens with the official release?
I guess it is just a missing option in the "three dots menu"

**Comment by AndyScherzinger** [comment]
The official release doesn't offer this either, so yeah it is missing in general.

**Comment by davivel** [comment]
This is a general behaviour in the app. If made this, we should consider also "Download/Synchronize the current folder", "Delete the current folder", "Move the current folder"... Sounds like the options menu growing a lot.

The only real limitation is for the root folder, since we can't browse to its father.  That's a case to consider, IMHO.

Calling @jancborchardt for an opinion.

cc @owncloud/android-developers

**Comment by jancborchardt** [comment]
This is definitely an issue, one we have in core as well. (https://github.com/owncloud/core/issues/4333)

Proposed solution:
- the Share icon for the current folder should be placed in the top bar next to the 3-dot-menu _always_. Because being able to quickly share everything is very important. (Except in the root folder cause that would likely introduce recursive sharing and other weirdness.)
- the Download/Sync folder function is also quite important but not as important. Should be first entry in the 3-dot-menu.

Deleting and moving the current folder is not so important that it needs to be in this menu.
Other than that we only have »Refresh account«, »Sort« and »List/grid view«. The »New folder« will go away because it’s in the FAB. So only one addition to the list.

**Comment by jancborchardt** [comment]
Oh and btw I’m proposing this as a quite important interaction issue we should fix. cc @MTRichards

**Comment by rperezb** [comment]
@jancborchardt 

yes, i agree on the first idea, to have the option to share the current folder.

However, not very sure about the other suggestions, because not all the actions that can be done over a folder are covered, for instance: rename, or copy just partially.

On the other hand, since this ticket is about sharing the current folder, can we keep the goal to this and open a new ticket for the rest of changes? thx

**Comment by jancborchardt** [comment]
>  not all the actions that can be done over a folder are covered, for instance: rename, or copy just partially.

As I said, all these options are not that important. First we need to cover share and download/sync. The rest doesn’t justify filling up that menu as well.
