### ISSUE TITLE
Top Open PRs

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1454]
@AndyScherzinger @tobiasKaminsky opened this for input on your top PRs.

@LukeOwncloud FYI.

**Comment by tobiasKaminsky** [comment]
The biggest improvement for user would be https://github.com/owncloud/android/pull/1044, I think.
But this might not be the best to start with as it depends on gallery+ for < OC 8.2 and gallery for => 8.2

**Comment by AndyScherzinger** [comment]
I also don't have any preferences. A top PR imho would be #1191 since this prevents extra costs for users for example with their data plans especially when you are abroad and leave the hotel. 

My PR can be considered rather low prio since I usually implement ui stuff so that is rather polishing work. The FAB PR would be nice though since I adds a primary action to the UI.

**Comment by MTRichards** [comment]
Hello @tobiasKaminsky @andromaex we are looking at 1191 in the next sprint - which is the next 2 weeks starting today, now that the new version is out (yeah!). Further, looking at #1100 at the top of the backlog as well (which means if we get time in the next 2 weeks, and we will get it in the next release), and then finishing the uploads view #471 in the next 2 weeks as well.

And a bug or two on the side as well. Any new PRs that would be high priority? Let us know, we can prioritize them higher for the next sprint.

**Comment by AndyScherzinger** [comment]
@MTRichards Thanks for the update! Sounds fine to me. One UI PR I would suggest woudl be #1413 wehich implements @jancborchardt requierements regarding styling of the new share privilege dialogs. The FAB #1100 would be nice but as far as I understand depends on a decision if we add another library (part of the PR) to the app or not, since Android doesn't provide a out of the box implementation for the specified "speed dial".

**Comment by LukeOwncloud** [comment]
I support @tobiasKaminsky's suggestions for next sprint: #1044 and #1176 
They would be a huge improvement.

Further, there are 18 very small PRs (max 3 touched files, but most only 1 file).
Reviewing them and if appropriate accepting them would be great, in order to reduce the number of open PRs. Currently we are at 49. This is a little discouraging for developers...

https://github.com/owncloud/android/pull/1539
https://github.com/owncloud/android/pull/1494
https://github.com/owncloud/android/pull/1466
https://github.com/owncloud/android/pull/1450
https://github.com/owncloud/android/pull/1395
https://github.com/owncloud/android/pull/1373
https://github.com/owncloud/android/pull/1370
https://github.com/owncloud/android/pull/1369
https://github.com/owncloud/android/pull/1292
https://github.com/owncloud/android/pull/1226
https://github.com/owncloud/android/pull/1221
https://github.com/owncloud/android/pull/1187
https://github.com/owncloud/android/pull/1142
https://github.com/owncloud/android/pull/1111
https://github.com/owncloud/android/pull/1036
https://github.com/owncloud/android/pull/1028
https://github.com/owncloud/android/pull/944
https://github.com/owncloud/android/pull/796

**Comment by tobiasKaminsky** [comment]
Yeah that would be great.
I can help with update the branches and testing them.

**Comment by davivel** [comment]
I took the liberty to edit @LukeOwncloud's comment so that checboxes are shown.

I'm having a first look to the PRs in the list.

**Comment by AndyScherzinger** [comment]
I added my latest ones to the list...
 - [ ] https://github.com/owncloud/android/pull/1277
 - [ ] https://github.com/owncloud/android/pull/1559
 - [ ] https://github.com/owncloud/android/pull/1552

**Comment by davivel** [comment]
I think we should move this issue to owncloud/core#24684 .

cc @owncloud/android-developers

**Comment by davivel** [comment]
Please, everybody take there your suggestions.

**Comment by tobiasKaminsky** [comment]
I thought that the linked issue is about enhancements that are platform wide and not individual per each subsystem (calendar, contacts, gallery,...).
Devs from iOS are not interested in specific PRs from us, or?

**Comment by MTRichards** [comment]
What I think would be helpful is to add an issue to the master list @davivel pointed to, but keep a link back to the specific Android or iOS issue that discusses the change in more detail. That way there is an overview of what is going on (and some voting and prioritization), but the details are still here.

And I do think iOS is interested in some of the changes, because we will want to make the user experience similar over time.

**Comment by tobiasKaminsky** [comment]
Ok, I see the point.
I have added a description for my very favourite PR (#1599) and hope that it gets upvoted :)

**Comment by MTRichards** [comment]
Thank you!

**Comment by rperezb** [comment]
@tobiasKaminsky certainly yes! from iOS team we are also interesting in what it's going on Android and back way, no doubt! the goal is to build a platform. I'd go one step away and add the desktop client too.
We try to propagate what it's being done on each client, for instance, when we implemented the internal sharing we took care of following similar approaches
btw, voted your suggestion 😄
