### ISSUE TITLE
Error `UNKNOWN` if server certificate changes

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1515]
### Expected behaviour
A more helpful error message. Maybe even `Credentials error`.

Related to issue https://github.com/owncloud/android/issues/1463

**Comment by davivel** [comment]
I guess you mean in the uploads view, right? Please, mention #1493 in any issue you open about it.

At this point I think it should show ```Connection error```. Could you test it, @LukeOwncloud

**Comment by LukeOwncloud** [comment]
Good. Its says "Connection error" now. But when clicking (to upload again) the credentials view is not shown. This would allow the user to accept the new certificate. Just showing "connection errror" might also be a little confusing, as the user does not know why. How about "SSL certificate failure"? This is a little technical, but users know what to do (or what to tell their admins).

**Comment by davivel** [comment]
That's a reasonable improvement, but gets out of the scope we defined for this release of the uploads view. There is a set of recovery interactions we agreed internally for it (I'll update the issue so that they're public), and this one is not included. 

Besides, there is also another issue specific for notifying the user as soon as the certificate is updated and opens the app. Not too far in priority also if I recall correctly. We could include this as an acceptance criteria of that.

**Comment by rperezb** [comment]
This one is related to: https://github.com/owncloud/android/issues/609 https://github.com/owncloud/android/issues/1420 and https://github.com/owncloud/android/issues/1463

Let's track the status of the issue on the oldest one #609, I update the ac

as @davivel has said the plan is to work on this one in 2 releases

**Comment by davivel** [comment]
Clearing wrong milestone, was released in 2.0.0, in #1598
