### ISSUE TITLE
Thumbnails not shown in `UPLOADED` section

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1517]
### Expected behaviour
For all photos a preview/thumbnail should be shown in https://github.com/owncloud/android/pull/1493.

### Actual behaviour
For some photos in `UPLOADED` section placeholder is shown.

### Steps to reproduce
0. Enable instant upload and set behavior to "move to app folder".
1. Take photo to invoke instant upload.
2. Wait until upload has finished. Do not click notification "upload at x%".
3. Go to uploads view (e.g. by clicking the notification "upload **successful**").

**Comment by davivel** [comment]
With "preview" you mean "thumbnails", right? 

We need to narrow down the "some photos" part. Happens only with instant uploads? What "behaviour" did you selected in the instant uploads options?. Is the thumbnails still invisible if you scroll the upload out of the screen and then bring it back? Is the thumbnail of the picture visible in the list view?

**Comment by LukeOwncloud** [comment]
Good call @davivel!
Yes, I mean the thumbnail next on the left of the upload item.
Yes, it happens only for instant uploads with behavior "move to app folder". Follow steps from above them (I'll update them). At this point scrolling down and up does not help. Also swichting to file view does not help. Thumbnail in upload view will not show up.

Curious: The other uploads for which a thumbnail is shown are still missing the thumbnail in the file view (list view). They need to be downloaded there first, too. Shouldn't it be the same thumbnail?

**Comment by davivel** [comment]
That info will be very useful. Let's deal with this as a bug to fix for #1493, at least as nice-2-have.

> Shouldn't it be the same thumbnail?

This is a very interesting question. It's a side effect of merging the recently added "policy" about duplication of files for instant uploads, and the addition of the uploads view.

The list of files tracks OCFiles -- this is, files that exist in your OC account. In practice, files that already exist in your server. The app tracks local copies of these files, but only if they are contained in the local ```owncloud``` folder. With the now default behaviour for instant uploads, the pictures are left in the DCIM folder (to avoid duplications), so the app handles the new created OCFile as not downloaded. If you enable the other behaviour for instant uploads, the pictures are moved from DCIM to the local ```owncloud``` folder, and then the app consider the new created OCFile as downloaded. Thumbnails in the list of files are generated from the local copy in ```owncloud``` if it exists, and remotely requested to the server [1] if there is no local copy **there**.

The uploads view can't track OCFiles because for many upload there is still no OCFile - it doesn't exist until the file is completely uploaded for the first time. Due to this, stored uploads need to track the local file even though it's out of the ```owncloud``` folder, otherwise there is no way to retry failed uploads of files that are added to the account. Thumbnails try to take advantage of this, and use those local files out of the ```owncloud``` folder. 

[1] If remote thumbnails use to work with your server, but you have no thumbnail for pictures that show thumbnail in the uploads view, then we could be facing another bug related with a key failure in the thumbnails cache.

**Comment by davivel** [comment]
And after all this, I just noticed that maybe remote thumbnails are not working at all in your server setup. Is that the case, @LukeOwncloud ?

**Comment by davivel** [comment]
And you are using "move to app folder", so definitely something is wrong there.

**Comment by LukeOwncloud** [comment]
Remote thumbnails work fine with my server. I see all of them in the files view.

**Comment by davivel** [comment]
But this is still happening, right?

> Curious: The other uploads for which a thumbnail is shown are still missing the thumbnail in the file view (list view). 

So, no remote thumbnails working for those particular files. Or am I misunderstanding?

**Comment by LukeOwncloud** [comment]
Exactly, problem persists. Just follow **Steps to reproduce** from above.

**Comment by malkomich** [comment]
Fixed :)
Now when the upload view is refreshed the thumbnail is generated in a right way.

**Comment by jesmrec** [comment]
:+1: refreshing the view all thumbnails from moved instant uploads are shown

**Comment by malkomich** [comment]
I'll close this issue since it is already approved by QA and merged in PR #1493 ;)
