### ISSUE TITLE
Synced Files disappear on Samsung Galaxy S6 every day

### ISSUE THREAD

**Issue by jmit79** [owncloud/android#1588]
### Expected behaviour
Files that were synchronized should stay on my smartphone until i delete them (local or remote)

### Actual behaviour
All files get deleted by Samsungs Smart Manager App every day (or even faster??). The app somehow recognizes the synchronized files as temporary files and cleans up storage as soon as a (unknown) limit is reached. The app can't be uninstalled/deactivated as it is a preinstalled system app by Samsung.

### Steps to reproduce
1. Synchronize a file/folder in the client
2. Start Smart Manager app and cleanup storage
3. All synced files are gone

### Environment data
Android version: 6.0.1

Device model: Samsung Galaxy S6

Stock or customized system: stock

ownCloud app version: 1.9.1

ownCloud server version: 9.0

**Comment by LukeOwncloud** [comment]
For technical reasons uploaded files are copied to Owncloud directory (usually on sd card). 

Just a guess: Maybe the Smart Manager App detects these duplicated files and removes one copy (in this case the original). If this is not the case please clarify which copy (or both) is removed. 

Potential work arounds:
- File instant uploads, go to owncloud app settings and choose upload behavior "move" instead of "copy". In this case owncloud app moves photos from gallery to owncloud folder. Thus, Smart Manager App won't detect any duplicates. Downside: Only works for instant uploads, photos are not accessible in default gallery folder. 
- Check Smart Manager App settings to disable duplicates (or configure which copy is deleted). 

Under the line, I'd argue that this is rather an issue of Smart Manager App. Any chance to file a bug und feature request there?

**Comment by malkomich** [comment]
Needed more information about how Smart Manager app works, and for what is it used. @jmit79

**Comment by jmit79** [comment]
@LukeOwncloud: sorry for the late reply... The problem does not relate to instant uploads. They're working flawlessly. I also think that Smart Manager is the culprit.

@malkomich: Here's the official samsung news: https://news.samsung.com/global/smart-manager-the-way-to-keep-your-galaxy-smartphone-as-good-as-new-always

And another link why you shouldn't use the app: https://www.androidpit.com/why-you-shouldnt-use-samsung-smart-manager-clean-all :)

You can only get rid of the app on a rooted device and you can't deactivate the app. :( It's a shame that you can't get rid of this app. 

I think you can close this issue as there is nothing we can do here.

**Comment by LukeOwncloud** [comment]
Okay, closing then.
