### ISSUE TITLE
Can edit can be enabled when it should not

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1615]
### STEPS TO REPRODUCE

1.- Share a folder with a user in other server with "Can edit" disabled.
2.- The sharee accepts the share
3.- The sharee re-shares the folder with a user in another server
4.- The sharee enables "Can Edit"

### ACTUAL BEHAVIOUR

The switch is enabled. If you go back and enter again in permissions view, the switch is disabled.

### EXPECTED BEHAVIOUR

The switch "Can edit" can not be enabled because the sharee does not have edit permissions

Tested with Nexus 6P

Servers
{"installed":true,"maintenance":false,"version":"9.1.0.0","versionstring":"9.1.0 pre alpha","edition":"Enterprise"} {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":"Enterprise"}

**Comment by davivel** [comment]
This is updated now in branch release-2.0.0, but the result is still not the expected.

The request to update share permissions was not being sent, that's why there was no error due to lack of permission.

Now the request is being sent, but the server is responding with an OK (and then, some time later, changing the permission back to the original value). This is unexpected for us, and we'll have to talk about it with our pals in the server; but there is nothing else we could or should do in the app regarding it, so this should be closed.

**Comment by davivel** [comment]
Real problem in https://github.com/owncloud/core/issues/24128. Let's track it there.
