### ISSUE TITLE
[Feature request] Rename uploaded pictures with a friendly name

### ISSUE THREAD

**Issue by effemmeffe** [owncloud/android#1723]
I noticed that with the dropbox app when I take a picture from my phone it uploads the picture and changes the name from IMG_YYYYMMDD_SOME_OTHER_CHARS.jpg to a more friendly YYYY-MM-DD HH.MM.SS.jpg
Is there some way to do that also with the owncloud app?

**Comment by LukeOwncloud** [comment]
Unfortunately, not yet. But it was already requested here :https://github.com/owncloud/android/issues/871

**Comment by effemmeffe** [comment]
I did a search, but was unable to find it, sorry. 
Is there a road map?

**Comment by davivel** [comment]
Sorry, there is not an easy-to-read roadmap yet.

If you install Zenhub in your web browser, you can see the short term work and prioritization entering in the "Boards" option that appears in the Github menus.

You can also see the currently defined milestones in https://github.com/owncloud/android/milestones and the estimated issues for each of them. 

Besides, we keep an eye in the mobile topics more voted in https://github.com/owncloud/core/issues/24684 .

As you can see, there is nothing related to this topic. 

Since this is duplicated, I will close it. Please, let's track any progress on #871.

Thanks.
