### ISSUE TITLE
As an user I want to be able to enable/disable "can share" option for FEDERATED shares if OC server is >=9.1

### ISSUE THREAD

**Issue by jabarros** [owncloud/android#1725]
AC:
- Only if OC server is >= 9.1
- The checkbox "can share" will be visible and enabled for federated shares
- By default the checkbox will be checked.
- Whenever the user updates the value of the checkbox, a request to update the permission "can share" on the federated share will be triggered.

-Related https://github.com/owncloud/core/issues/22122#issuecomment-228028647

____

BUGS & IMPROVEMENTS

- [X] "Can Share" disabled by default https://github.com/owncloud/android/issues/1725#issuecomment-236129243 [FIXED]
- [X] "Can Share" disables "Can Edit" https://github.com/owncloud/android/issues/1725#issuecomment-236151088 [FIXED]

**Comment by davivel** [comment]
@rperezb , this should be added to milestone 2.1.0 for synchrony with server release.

**Comment by davivel** [comment]
Working in this right now.

**Comment by davivel** [comment]
Done inhttps://github.com/owncloud/android/pull/1752 and https://github.com/owncloud/android-library/pull/127

**Comment by davivel** [comment]
cc @jesmrec

**Comment by jesmrec** [comment]
### Bug

### Steps

1. Share a folder from a 9.1 server with a user in another server
2. Open the privileges view

### Actual behaviour

"Can Share" option is disabled. 

### Expected behaviour

"Can Share" is enabled by default. This is the behaviour in server side and in iOS app.

Server: 
{"installed":true,"maintenance":false,"version":"9.1.0.15","versionstring":"9.1.0","edition":"Enterprise"}

Tested with Nexus5 v5.0.1, Nexus9 v6

**Comment by davivel** [comment]
Checking bug.

**Comment by davivel** [comment]
Fixed now in #1752

**Comment by jesmrec** [comment]
### Bug

### Steps

1. Share a folder from a 9.1 server with a user in another server
2. Open the privileges view
3. Disable "Can Share"

### Actual behaviour

Both "Can Share" and "Can Edit" options are disabled.

### Expected behaviour

Only "Can Share" is disabled.

Server: 
{"installed":true,"maintenance":false,"version":"9.1.0.15","versionstring":"9.1.0","edition":"Enterprise"}

Tested with Nexus5 v5.0.1, Nexus9 v6

cc @davivel

**Comment by davivel** [comment]
@jesmrec , fixed now in #1752

**Comment by jesmrec** [comment]
@davivel Approved 👍 

Take in account the regression bug detected during the validation, added to the new version issue:

https://github.com/owncloud/android/issues/1750#issuecomment-236154125

**Comment by davivel** [comment]
OK, I'll deal with it in the release branch.

Thanks!
