### ISSUE TITLE
Automatic Picture Upload on Android not working

### ISSUE THREAD

**Issue by cschwarz007** [owncloud/android#1747]
### Actual behaviour
The owncloud Android app is enabled to upload pictures automatically. However, this does not work on my Galaxy A3 / Android 5.1.1

Manual upload through the app works, hence it can't be a matter of permission but must be something else.

Please let me know what information I can provide to further narrow down the issue and help solve it.

Many thanks in advance!

**Comment by davivel** [comment]
Hi, @cschwarz007 . What camera app do you use?

**Comment by cschwarz007** [comment]
Hi David,

I use the built-in Samsung Camera App. After testing with "Open Camera" the
upload works. Hence it seems to be an incompatibility with the Samsung
App...?

Best,
Christian

2016-07-25 8:59 GMT+02:00 David A. Velasco <notifications@github.com>:

**Comment by davivel** [comment]
Yes, the current implementation of instant upload of pictures depend on camera apps that send an event to all the apps in the device, called "com.android.camera.NEW_PICTURE". The ownCloud app is subscribed to be notified about it, and then starts the upload of new pictures.

But many camera apps don't send the event.

In the next weeks we will change our implementation so that it doesn't depend on that event anymore. In the next Android version, Android Nougat, the event will not exist.

You can find another people with the same problem in the issue #6. Let me invite you to track there our progress with the fix, and close this issue as a duplication.

And thanks for reporting :)
