### ISSUE TITLE
Auto upload, exif problem

### ISSUE THREAD

**Issue by fs-2014** [owncloud/android#1761]
### Actual behaviour
When the app automatically upload a picture after it's been taken, the exif of the image file indicate the date of the upload, not the original date and time of the picture.

If the upload succeed imediately after the photo shoot, there is not big problem. But when the upload fails, the exif of the image indicate the datetime of the retried upload, not the original exif.

### Expected behaviour
The exif of an uploaded image should always be the original one. Else, it mess up the order and the chronology and it's a problem.
 
### Environment data
Android version: up to date.

Device model: One Plus One

Stock or customized system: Cyanogen

ownCloud app version: up to date.

ownCloud server version: 9.0.1

**Comment by davivel** [comment]
Hi, @fs-2014 . Do you really mean the date in EXIF or the modification time shown for the file? As far as I know, the Android app doesn't modify EXIF metadata in any case.

**Comment by fs-2014** [comment]
Hi @davivel, I checked. You are right, the exif is not modified. It seems to me that modification time (it's a normal behavior) and **creation time is wrong**. Is it normal ?

As you can see in this screen (sorry it's in french), the right datetime is the filename and both creation and modification datetime is wrong (this is the datetime of the upload).

![capture d ecran 2016-08-10 a 13 22 01](https://cloud.githubusercontent.com/assets/6321058/17552198/b8c5dcd2-5efe-11e6-8fd9-1eca67aeb725.png)

**Comment by davivel** [comment]
This is a well-known bug. Exactly 1000 issues ago, in #761.

The modification time is something we should fix.

The creation time, not sure if will be handled, if I recall correctly there are problems to handle the creation time in a unique way depending on the file system of the server side, and that's why it never was managed in the Android app.

Please, track any progress on this topic in the aforementioned issue.
