### ISSUE TITLE
Instant Upload fails when phone goes to sleep

### ISSUE THREAD

**Issue by SakadiwaaSoftware** [owncloud/android#1766]
A video is recorded or photo is taken and instant upload kicks in. The phone is put into sleep mode and next time it is woken up OwnCloud displays an error message. Upload failed 'app was terminated'.

Presumably Android is terminating the service when the phone goes into sleep mode. I understand that the desktop client breaks files down into chunks for uploading. Could the Android client not implement the same behaviour? Then the service could be created as START_STICKY and resume uploading from the previous chunk when it gets restarted. This would also help when switching between wifi hotspots or moving from wifi to cellular data.

The issue is occurring on a Samsung Galaxy J7 with Android Marshmallow

**Comment by davivel** [comment]
Hi, @SakadiwaaSoftware . Probably this is due to Doze. We plan to make some improvements about the operation of the app when the device goes to sleep mode right for the next release, but I  can't tell you right now how far we'll get with them in the first iteration.

**Comment by isaacwalkercox** [comment]
@davivel where in the src folder is instant upload happening?

**Comment by davivel** [comment]
Sorry for coming so late, @isaacwalkercox . 

The upload is requested from https://github.com/owncloud/android/blob/master/src/com/owncloud/android/services/observer/InstantUploadsHandler.java .

Later, the upload is performed as an https://github.com/owncloud/android/blob/master/src/com/owncloud/android/operations/UploadFileOperation.java ran by https://github.com/owncloud/android/blob/master/src/com/owncloud/android/files/services/FileUploader.java .

**Comment by detly** [comment]
Why is this listed as an enhancement? It makes the app unusable. Almost every file I have tried to upload has failed for this reason; retrying it doesn't help because it'll just fail again for the same reason. The app restarts all uploads from scratch. Even leaving the screen on doesn't help; Android will occasionally terminate apps that aren't in the foreground depending on resources.

The only way for the OwnCloud app to work here is to (a) leave the screen on, (b) prevent the phone from sleeping by continuously interacting with it, and (c) keep the OwnCloud app in the foreground. This means that you can't use your phone for anything else, or even *do* anything else because you have to keep tapping the phone so it doesn't sleep.

This also applies to manual uploads too! So basically, there is no way to upload files that are larger than a couple of MB.

**Comment by michaelcadilhac** [comment]
I concur with @detly: this should be considered an important bug rather than an enhancement request.  My phone is quite aggressive at "terminating" tasks, and most uploads fail for this reason; it is for instance quite unusable for pictures, videos, and illustrated versions of War and Peace.

**Comment by davivel** [comment]
> In tagging this as an enhancement, I think you're overlooking how it makes the app unusable for large uploads. 

Sorry, I didn't want to give that impression. Trust me, I understand this is a heavy thing. To be honest, 'bug' or 'enhancement' labels don't result in different consideration for prioritization.

@SakadiwaaSoftware , @detly, @michaelcadilhac , could you all tell us what's the version of your Android devices? I made some (partial) tests with Doze in an Android 7 device, and didn't get that uploads failed so hard. 

In any case, thinking twice, 'bug' label is probably more appropriate for the nature of the issue.

**Comment by michaelcadilhac** [comment]
Very glad to see this!  Thanks very much @davivel ! I'm on Android 6.0.1 on an A310F.

**Comment by davivel** [comment]
Related to #1684; a first patch mitigating the problem will be provided with #1905, granting the retry of interrupted uploads. Probably will need to go further soon, so that the app resumes uploads in the point where they were stopped.

**Comment by davivel** [comment]
With next version 2.4.0, instant uploads interrupted by Doze will be retried when Wifi network is available again.

Thanks for your patience.
