### ISSUE TITLE
let users know what kind of error occurred

### ISSUE THREAD

**Issue by treaki** [owncloud/android#1776]
### Actual behavior
-Tell us what happens
i have uploaded something, again and again it worked but than ive got an unknown error

![screenshot_20160821-215310_](https://cloud.githubusercontent.com/assets/1477872/17839553/954b3ca2-67eb-11e6-8e99-21841954b218.png)

### Expected behavior
-Tell us what should happen
a proper error message should be shown instead

### what i did then

i logged into the webinterface and seen that i am out of storage, i have increased my quota and now anything fine again but first i was quite confused about that facile/meaningless error message. you should fix that!
 
### Steps to reproduce
1. fill your owncloud account until its full
2. upload something

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

its clear i dont need to do nonsense things

### Environment data
Android version:
6.0.1
Device model: 
not relevant, just a phone like everyphone else
Stock or customized system: cyanogenmod 13

ownCloud app version: 2.1.0 (from fdroid)

THATS ENOUGH IRRELEVANT QUESTIONS, WHY DONT ALLOW USERS FREE TEXT?

please fix that.

thanks in advance

**Comment by davivel** [comment]
> THATS ENOUGH IRRELEVANT QUESTIONS, WHY DONT ALLOW USERS FREE TEXT?

There is no need to use uppercase / shouting. If you think something is not relevant, simply remove the section or ignore it.

Nobody is forbidding free text, we are providing a template to gather information because, from our experience, it's way faster doing so that asking for every issue the things that could be relevant.

This issue is duplicating #1767. Please, track any progress in fixing it there.
