### ISSUE TITLE
App not responding to touch events

### ISSUE THREAD

**Issue by Marmo** [owncloud/android#1799]
### Actual behaviour
- no (not even any visual) reaction on tapping buttons/list items/input fields

(If the focus is already on an input field (for example after fresh install the field for the server url), the keyboard pops up and text input is accepted (as expected).)
### Expected behaviour
- appropriate reaction on the input 
### Steps to reproduce
1. install and enable Lux (https://play.google.com/store/apps/details?id=com.vito.lux). This app uses some screen overlay to make the screen darker than the lowest backlight setting would allow. I guess there are other apps, that use the same technique and thus might cause the same issue. the combination of Lux and Owncloud worked before the 2.1.1 update.
2. open Owncloud app
3. tap any button/list item/input field
4. nothing happens (not even any visual reaction on the tap)
5. disable Lux (tap the off-icon in its notification)
6. Owncloud app works as expected

Can this problem be reproduced with the official owncloud server?(url: https://demo.owncloud.org, user: test, password: test)

Not tested, as it seems not related to the server (happens even without any server configured)
### Environment data

Android version:
5.0

Device model: 
BQ Aquaris E 4.5

Stock or customized system:
Stock

ownCloud app version:
2.1.1

ownCloud server version:
(9.1)

**Comment by AndyScherzinger** [comment]
@davivel only thing that comes to my mind without further research is https://github.com/owncloud/android/commit/2f4fdb20f66b9d908f37b1c5978f9f142dbb98f6

**Comment by davivel** [comment]
Sure it's that.

I don't know if we will be able to fix this soon. That change has been added as a security measure to protect the app against tap-jacking. I guess we could make it optional, but can't compromise any time to release it.

@Marmo, could you tell us something about your reasons to use Lux? Why is this app so important for you? Thanks in advance.

**Comment by Marmo** [comment]
My reasons to use Lux:
- in lowlight conditions (mainly at night) the screen is too bright for me, the (black-transparent) overlay reduces the brightness further
- i can create sensor-reading/screen-brightness pairs and control the auto-brightness this way

I understand the tap-jacking concerns. For me I found a solution now (actually I found two ...): 

1. In the Lux app there  is an option to use an "alternative overlay", which does not cause the unresponsiveness in the Owncloud-app. I dont know, if that alternative overlay works for me like the standard one, but I will see.
2. The Lux app has a list of apps, that cause the overlay to be deactivated while one of these apps is in the foreground (this list contains the android package installer per default, which seems to have a similar tap-jacking protection). So I could add the Owncloud app to that list.

**Comment by PVince81** [comment]
Same issue here, I'm using a different app called Twilight: https://play.google.com/store/apps/details?id=com.urbandroid.lux&hl=en
It's similar to the desktop app "redshift" for Linux (which I also use).
Basically it makes the screen more red on evenings and more blue in the mornings to make it easy on the eyes.

The app also uses a screen overlay, so since the last update of the Android client for ownCloud, I can't use it any more.

@davivel would it be possible to make a switch to disable this protection ?
I think ideally the clickjacking protection needs to be only done on specific sensistive parts of the UI.

I noticed for example that Android also prevents clicking on the "Install" button through an overlay when installing third party apk files.

**Comment by vals-productions** [comment]
I have the same issue - Android 5.0, Samsung Galaxy Note 3. Owncloud App is not responding to any touch events.

If I reboot the device and start owncloud app first thing it might respond for a couple of touches, but then again its dead frozen.

**Comment by davivel** [comment]
We didn't preview this side effect. Seems there's enough interest in it, and the security fix was not considered of high sensibility, so we could roll it back until we are able to do it optional.

**Comment by PVince81** [comment]
@davivel are there any specific dialogs that would need such security ? I'd suggest to restrict this security feature to a small subset of sensitive UI components.

**Comment by davivel** [comment]
Reference: https://github.com/owncloud/android/pull/1107

**Comment by davivel** [comment]
Proposal from @LukasReschke was protect all the UI. Specially sensible are login and passcode views.

**Comment by huettenhain** [comment]
I have the same problem with Lux installed.

**Comment by xeros** [comment]
I have the same issue with all ownCloud Android client 2.1.x versions (except 2.1.0, which works fine).
I didn't even suspect that the issue is with combination of ownCloud + Lux (I haven't found any other app than ownCloud that has problems with Lux).
And I need to use Lux for exactly the same reasons as Marmo, who listed them above.
Additionally, my phone screen is draining much battery with screen brightness at higher levels, that's why I limit it with Lux in low-light conditions.

**Comment by croisez** [comment]
I got the UI not detecting my finger touch in the following situation:
- in notification tray, disable auto-rotation.
- start owncloud app in my bed, with screen rotated in landscape, but app is still in portrait due to auto-rotation locked.
- enter a https address, which has a self-signed certificate which causes the apparition of a warning message.
- at this point, impossible to push on any of the 3 options (no, details, yes).
My guess is that this issue is related to the screen rotation, because when I redo the whole process in the normal position, I can access and push on the 3 menu items.

**Comment by croisez** [comment]
My owncloud server at home cannot authenticate login requests from my Android 6.0.1 phone.
In the play store, there is a mention of a workaround app. But I cannot find it.
Could you help me find it please?

**Comment by davivel** [comment]
@croisez , your issues are different than what's described here. Please, open two new separate issues for them.

**Comment by michaelstingl** [comment]
An user also reported an issue with the app "BlueLight filter".

@davivel Could this check be configurable in the settings?

**Comment by alongwor** [comment]
Same issue using Twilight.

**Comment by davivel** [comment]
> @davivel Could this check be configurable in the settings?

Yes, it could be. And it should be. And it should be easy.

**Comment by maxim-kukushkin** [comment]
Any chance that this bug is fixed? To me it happened even without installing any programs like Lux. It just accidentally stop working (i.e. responding to any taps).

Android Nougat. Moto G5 Plus

**Comment by arjenlentz** [comment]
I've seen this issue on a Samsung S4 in the past, with Twilight active.
Now same on Nokia 6 (Nougat 7.1.1) again with Twilight active.
Since Twilight was mentioned by someone, I told my Twilight to pause and behold, everything works!
So that's definitely the trigger - as to the cause, I do not know. Most (not all) other apps work fine with Twilight active.
Now that I know, I can work around it by pausing Twilight when I need to use or configure OwnCloud - it's just a nuisance and obviously creates problems for less savvy users. It should "just work".
Anyhow, hopefully this input will assist in tracking down the root cause and find a possible solution!
thanks

**Comment by RalphBike** [comment]
Same here. Not working with Android 7.1.x and Twilight, working fine with disabled Twilight.

**Comment by Relaking** [comment]
Same issue here, using a pixel-filter app or anything else that overlays the ownCloud app

**Comment by harshitbansal05** [comment]
@davivel @davigonz is the issue still open? I found it interesting but could'nt get exactly what is preferred? Could you please help me?

**Comment by michaelstingl** [comment]
@harshitbansal05 please install a tool like Lux or Twilight and try to use the ownCloud app to check the behavior. ownCloud app has a security feature that protects your data from other apps that add an additional layer to your screen. A config option is needed so users could disable this security feature.

**Comment by RalphBike** [comment]
I still have the same effect with the latest lineage, with Twilight and without.

I tried excluding the client from Twilight and also uninstalled Twilight. For me this is a blocker and makes the client completely unusable, which is basically the only reason why I still have to use Dropbox and can not switch to Owncloud.

**Comment by Polfo** [comment]
I have the same issue with EyeFilter installed

**Comment by theScrabi** [comment]
@RalphBike Let me guess, since you are trying to setup owncloud you want to login before using the app.

Well the reason it might not be working is because we secured the login screen, so it is not possible to take screenshots of it, or use an overlay with it.
Please make sure not to use any overlay if you want to log in.

**Comment by davigonz** [comment]
@michaelstingl the switch to enable/disable light filtering from other apps is already in https://github.com/owncloud/android/pull/2429 and will be disabled by default in PlayStore release, but what about including a new option in the app so that end users can also enable/disable it under their own responsibility, after accepting a warning dialog?

**Comment by PVince81** [comment]
side note: Android 9 has built in night mode and doesn't seem to affect the app any more, I'm using that now.

**Comment by michaelstingl** [comment]
> but what about including a new option in the app so that end users can also enable/disable it under their own responsibility, after accepting a warning dialog?

👍

**Comment by michaelstingl** [comment]
2.10 with config option to allow this got released in the Play Store:
https://central.owncloud.org/t/owncloud-2-10-for-android-released/18900
