### ISSUE TITLE
able to use different Storage (external SD)

### ISSUE THREAD

**Issue by zoff99** [owncloud/android#1804]
### Actual behaviour
- storage directory for the whole app not selectable

### Expected behaviour
- select from available storage cards
 
without this the app fills up the internal storage and stops working (out of space), at the same time lots of GB are free on the extSD Card.

what is the reason that the branch for this [externalSD2] is not merged? it seems to work just fine

**Comment by davivel** [comment]
Hi, @zoff99 . It's great to know it works for you, that positive feedback is a new push to have it merged :) 

See the PR of that branch here: https://github.com/owncloud/android/pull/1293 . We need to find some time to review it and make some deep testing. We'll try to schedule it soon. Maybe you can help us with a code review of the PR too, any feedback is welcome.

Maybe you are also interested on this idea to handle local storage: https://github.com/owncloud/android/issues/756#issuecomment-240070815 . Would be great to have your opinion there. It's a little better explained also here: https://www.youtube.com/watch?v=iWE0rxFCDXc#t=3m30s

Anyway, this issue is duplicating #10. Please, follow any progress in the topic there or in #1293. I need to close this issue, duplications make more difficult handle the repo.
