### ISSUE TITLE
use session cookies for android app

### ISSUE THREAD

**Issue by Kawohl** [owncloud/android#1841]
### Actual behaviour
android app ignores session cookies.

### Expected behaviour
android should check for the session cookies so the access can be revoked fromm the server side.
 
### Steps to reproduce
1. create user test on server
2. login with user on server
3. login from android.
4. on personal page on server look for active sessions
5. android client is not shown in sessions overview.

### Environment data
Android version: android 6 

Device model: 
moto g3 
Stock or customized system:
cyanogenmod
ownCloud app version:
2.1.2
ownCloud server version:
9.1.2 expected to work from 9.1.0

**Comment by Kawohl** [comment]
@davivel as discussed

**Comment by davivel** [comment]
@Kawohl , what do you mean with "expected to work from 9.1.0"?

**Comment by michaelstingl** [comment]
@Kawohl Do you have a SFDC reference?

**Comment by Kawohl** [comment]
@davivel  Sorry for the confusion. What i meant was that it you have this overview beginning from server version 9.1.
![screen shot 2016-11-24 at 09 16 09](https://cloud.githubusercontent.com/assets/12275313/20891523/40fd1e4a-bb0b-11e6-9b6f-2e0da4157ba8.png)
It would be awesome to be able to  revoke the access with the session cookie.

**Comment by davivel** [comment]
@Kawohl , I have a first solution.

But, it's limited.

With it we can see the sessions of the Android app in the list, and we can revoke them. BUT, since the app is storing the password in the device, as soon as the user makes another action in the mobile app, a new session is created.

To get a real revocation, the user will have to change the password in the web UI and then revoke the active sessions.

This is the same behaviour that the iOS app shows right now. I didn't test the desktop client.

Is this good enough for the moment? To get a direct revocation of the session without changing the password we need to change a lot of things in the app,  too many if we want to release before Christmas. Besides, those changes match better with the next switch to token based authentication.

**Comment by davivel** [comment]
@borjahawk , this is ready to test.

**Comment by Kawohl** [comment]
@davivel awesome! Thank you. This should be fine for now. I think the proper way to do this in future with the token revocation will be better. For now this shoul do it.

**Comment by borjahawk** [comment]
QA Validated.
