### ISSUE TITLE
Trash icon too close to "three dots" menu

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#1877]
Note: I usually use vimtouch to open text files

1. Install vimtouch (or any other text editor)
1. Upload some text file "test.txt" from another machine
1. In the ownCloud app, navigate into the folder of the file "test.txt"
1. Hold on the "test.txt" item (we want to edit but don't want to view the file with the built-in viewer)
1. Use the "three dots" menu to select "open with" but be clumsy and tap a bit on the left of it

### Expected
No trash icon so close to "three dots"

### Actual
Risk of tapping the delete icon when aiming for the three dots menu.

Note: in general I'm not too happy to have to use this menu when editing a file. But due to the new built-in viewer I need to do more manual action to be able to open the file in an external editor. (maybe I'll make another separate report)

**Comment by jesmrec** [comment]
@PVince81 do you have the latest app version installed (2.2.0)? In this version was released a re-ordering of the menu options (https://github.com/owncloud/android/issues/1144), which set the 'Remove' option at the end of the menu, far from the three-dot-button (for a mobile device).

Anyway the 'Remove' option is shown on the toolbar if the device screen has enough room. I have checked with a larger-than-10-inches screen and the option remains at the bottom of the menu (no remove icon displayed). So, a very large screen (a TV, for example) maybe shows the option at the left of three-dot-button, causing the effect you described.

@owncloud/android-developers does it make sense if this case to remove the 'ifRoom' property in order to assure that the 'Remove' option is always on the bottom?

**Comment by PVince81** [comment]
Indeed, can't reproduce the issue with 2.2.0.
