### ISSUE TITLE
Beta link broken

### ISSUE THREAD

**Issue by JanGross** [owncloud/android#1903]
The link to the beta version from the README seems to be ´broken (404)  
https://github.com/owncloud/android/raw/beta/apks/latest.apk

**Comment by lsaavedr** [comment]
if you like, you can download "the last" "owncloud-beta" with "files on SD support" from this link:

https://owncloud.timining.cl/index.php/s/VyADUscp8eCjyMO

why "SD support" was broken? I have a lot of data in my owncloud to save these in internal memory ¬¬

**Comment by davivel** [comment]
"SD support" was not broken; it never was merged in the master app.

The old beta is not maintained anymore. We'll start a new beta soon. This time we'll try that it works as is expected for a beta, including features that are should be released next, instead of any feature passing by.

Closing in favor of #1839.
