### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1923]
Related to: https://github.com/owncloud/platform/issues/24

Folders can be created with emojis in name

To improve:

- Rename/Delete a file with emojis in filename. Error is shown but the action is correctly done.
- Content can not be uploaded to a folder which name contains emojis. Neither manual nor instant nor sharing from other apps. Unknown error in uploads view. On the other hand, a folder can be created with or without emojis into a folder with emojis.
- A file with emojis can not be moved/copied into a folder with emojis 
- Set a folder (empty) as av. offline. An error is displayed

Server must be set to support mb4 characters: https://github.com/owncloud/documentation/issues/2924

**Comment by davivel** [comment]
Thinking aloud.

> Folders can be created with emojis in name

Creating a folder does not result in creating a corresponding folder in the local file system, that is delayed until any file is put inside (download or upload).

All the things failing suggest also that problem is trying to take the emoji characters to the local filesystem.

Probably the only way to do this safe is mapping emoji names other names in local filesystem. Will require some work.

cc @michaelstingl
