### ISSUE TITLE
Get rid of 'contacts' permission group request

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1940]
Some of the permissions requested in ```AndroidManifest.xml``` to access system ```AccountManager``` are resulting in```contacts``` permission group being listed in the settings of the ownCloud app, requested by disabled. 

![contacts_group__device-2017-04-11-165033](https://cloud.githubusercontent.com/assets/2225614/24915289/12e7ab12-1ed7-11e7-9d68-c5c65794e4e9.png)

It's highly probable that we don't need all the permissions in the manifest, and that we can get rid of ```contacts```. 

We should ask as few permissions as possible, so nice to have.

**Comment by davigonz** [comment]
@davivel The contacts permission is requested in this view because GET_ACCOUNTS permission belongs to the CONTACTS permission group since Android 6.0 and although the API let us provide permissions, the user is asked for permission groups. 

Many people have complained about this because it has no sense include this permission in CONTACTS groups. I think that we can't do anything to solve it at the moment.

**Comment by jesmrec** [comment]
Will be fixed when minimum SDK is 23 -> https://github.com/owncloud/android/issues/3245

Expected for upcoming releases.
