### ISSUE TITLE
Auto media upload fails to grab all files

### ISSUE THREAD

**Issue by fsantiago07044** [owncloud/android#1991]
### Actual behaviour
-Tell us what happens

Not all photos / videos seem to be uploaded

### Expected behaviour
-Tell us what should happen

All media to be uploaded if I have auto upload turned on 
 
### Steps to reproduce
1. Google pixel
2. Android O beta (also happened with latest N)
3. Take photos or videos and wait to see if it uploads automatically (or at all)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version: latest stable

ownCloud server version: latest stable

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hello @fsantiago07044 , thank you for reporting this issue, what you described here has been already detected in Android 6 and 7 and we are currently working on fixing it - have a look at https://github.com/owncloud/android/issues/1829 for Android 7 for more details. Besides, we will launch a beta version with the fix soon so that users can test it and report us the results they obtain.

**Comment by jesmrec** [comment]
Feel free to reopen if still reproducible, Thanks!
