### ISSUE TITLE
App is reopened from login view after double tap on "Back" button

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2009]
### Steps to reproduce
In login view, tap twice in "Back" button (triangle button)

### Current behaviour
App is closed

### Expected behaviour
App is closed and reopened

**Comment by yongjiexu** [comment]
I think this should be a feature, not a bug.

**Comment by jesmrec** [comment]
@yongjiexu maybe... depending on the expected behaviour.

**Comment by sd1998** [comment]
@jesmrec I would like to work on this issue.

**Comment by jesmrec** [comment]
@sd1998 ok! first of all, try to reproduce the problem by yourself, so you can check what is really happening. Please, open a new branch to develop the fix and tell us if you need help.

**Comment by sd1998** [comment]
@jesmrec I tried to reproduce the problem. The login layout is account_setup.xml in res/layout right? What I have seen is that when the activity(AuthenticatorActivity.java) launches the on screen keyboard opens and then if I press back two times the app is closed. To fix this issue when the user presses the back button the app should not close right? Or the app should close and relaunch again. And this should not happen when the user is adding a second account because in that case on pressing back button twice the app returns to the FileDisplayActivity.java.

**Comment by jesmrec** [comment]
Two taps on the back button are performed without the screen keyboard, and no accounts attached. I mean, first tap on the back button to vanish the keyboard, and then, double tap to reproduce the problem. The expected behaviour is that the app is closed as well as with one tap. Maybe it is not easy to reproduce (for that reason the low severity).

**Comment by sd1998** [comment]
@jesmrec So after the keyboard disappears if the user taps the back button two times the app should not close?

**Comment by jesmrec** [comment]
It should close. The wrong behaviour is that it does not. It closes and reopens.

For that reason, i pointed you to try to reproduce it before start developing :)

**Comment by sd1998** [comment]
@jesmrec  I am trying to reproduce it but it happens sometimes (very rarely) and most of the times it just closes.

**Comment by sd1998** [comment]
@jesmrec I think I just have to eliminate the very rarely possibility of the activity to relaunch.

**Comment by jesmrec** [comment]
Not reproducible anymore
