### ISSUE TITLE
Change Instant upload Location

### ISSUE THREAD

**Issue by danielromney** [owncloud/android#201]
I tried to search for this, and hope this isn't a repeat issue. I was wondering if it would be possible to change or upon initial set-up to pick where your instant uploads go. I am running ownCloud and mounting an SMB share so I can have access to all my files on my file server. If I could have the ownCloud android app save my instant uploads to that SMB share, that would be amazing! That way I could centralize everything and not have to move things later.
ownCloud has made it possible for me to start getting rid of my dropbox. You guys are awesome.

**Comment by ocontant** [comment]
ANDROID CLIENT: 

Another issue with the client side.  InstantUpload keep the files  locally on the device instead of removing them automatically.  As a result, all picture exist twice on the device eating the small internal memory space. 

I also cannot see the setting to configure the client side to put the data on an external SD card. 


Think that I would like to see is :
1- A way to configure the client to store the data on an external SD card *define the complete path*
2- A way for the instantupload to not keep a local copy as it is eating space for nothing.  *if we need an offline copy, we should do the same step as for any other file in owncloud.  
Syncing all on device is not good practice. 


Thank for the amazing work by the way!  I tried to contribute as well, but my programming level wasn't good enough.  I hope my recommendation can help a bit :) 


High Five!

**Comment by strugee** [comment]
@ocontant see #819. Please don't comment on random issues - search for duplicates, and if there's no issue for your problem, file a new one.
