### ISSUE TITLE
how to painless rename package from com.owncloud to org.freecloud

### ISSUE THREAD

**Issue by lazarvgd** [owncloud/android#2012]
I have the problem with renaming package. If I rename the package then I run into problem that I have bunch of classes that need to re-import in other classes.

How can I easy achieve this?

thanks

**Comment by davigonz** [comment]
Hi @lazarvgd , I've just seen in https://github.com/owncloud/android/issues/2017 that you are signing the apk so I guess that you have managed to fix this problem, haven't you?

**Comment by lazarvgd** [comment]
I have done it, but I still have huge problems when I renaming the folder - sometimes I am unable to refactor it without changing import of R class.

**Comment by davigonz** [comment]
Hi @lazarvgd , there are many ways to rename the package, I've tried this in other projects and has worked for me so far:

1. Change the package name in the manifest
2. Refactor the name of your package with right click -> refactor -> rename in the tree view, then Android studio will display a window, select "rename package"
3. Change manually the application Id in the build.gradle file : android / defaultconfig / application ID
4. Then clean / rebuild the project

BTW, I'm going to close this issue since you have managed to rename the package. You can follow the steps above if you need to rename a package in the future. If the problem reappears, please reopen this.

**Comment by lazarvgd** [comment]
Sure, Thank you very much for your time and effort. :1st_place_medal:
