### ISSUE TITLE
Calling mCapapility NullPointerException in sharedFileFragment

### ISSUE THREAD

**Issue by Kjehad94** [owncloud/android#2025]
### Actual behavior
-Tell us what happens
I added a new capability to the code which basically restrict sharing to individual file, now I whenever I try to get the value in SharedFileFragment class it shows null pointer exception.
In the same time it is working 100% fine in the method refreshCapabilitiesFromDB.

I want to add this code snippet in these lines: https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/fragment/ShareFileFragment.java#L241

The code is:
```
 ```
else if (flag && mCapabilities.getmIndividualFileSharingRestriction().isTrue() && !mFile.isFolder()) {
                Toast.makeText(getContext(),"ggg",Toast.LENGTH_SHORT).show();
                shareNoUsers.setText("Individual files cannot be shared among users and groups..");
                shareNoUsers.setGravity(View.TEXT_ALIGNMENT_CENTER);
                addUserGroupButton.setVisibility(View.GONE);            }
```
```
### Expected behavior
 Return a boolean value of true or false and change layout depends on that,

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hi @Kjehad94 , the null pointer exception you get is because you're trying to access to the capabilities before they are set in `refreshCapabilitiesFromDB` method.

Taking into account the lifecycle of a fragment and the activity to which is attached, we have two important methods in `ShareFileFragment`, that are called in the next order:

1) `onCreateView`: fragment view is inflated. Here is where you are trying to access to the capabilities but they are still null.
2) `onActivityCreate`: called when the onCreate() method of ShareActivity has completed. Here is where we call `refreshCapabilitiesFromDB` method and **mCapabilities** variable is initialized.  

Therefore, if you want to change the UI depending on your new capability, I would add a call to a new method, where you could include the code you've attached above, in onActivityCreated method, after `refreshPublicSharesListFromDB` call (line 368). As you can see the **refreshUsersOrGroupsListFromDB** and **refreshPublicSharesListFromDB** call other methods to update the UI depending on the capabilities.

**Comment by Kjehad94** [comment]
Dear David,

I tried what u said as shown in the snippet below, but it keeps telling
that we have null pointer exception..

getActivity().setTitle(R.string.share_dialog_title);

// Load known capabilities of the server from DB
refreshCapabilitiesFromDB();

// Load data into the list of private shares
refreshUsersOrGroupsListFromDB();

// Load data of public share, if exists
refreshPublicSharesListFromDB();
flag = restrictShare();

-------------------------------------------------------------------------------------------

private boolean restrictShare(){
    return mCapabilities.getmIndividualFileSharingRestriction().isTrue();
}


Khalid J. Abushammala
Founder
*I'M*


Skype:khalid.jehad

FB:Khalid J Abushammala <https://www.facebook.com/king1101>

Whatsapp: +972595133941

**Comment by Kjehad94** [comment]
It is mentioned that it must for OnCreateView to be finished before we call the method, but the problem that I need to fetch that line which uses restrictShare method inside OnCreateView ,,,,,



https://github.com/owncloud/android/compare/master...Kjehad94:share_restriction?expand=1#diff-ca51d8aa4d6ff8fc4a053f2c116e8685R263

**Comment by davigonz** [comment]
Why do you need to call restrictShare method from OnCreateView? I mean, by using the code you've copied above you want to change the UI and this can be done after calling the restrictShare method from OnActivityCreated.

Have you checked also that you capability is being properly saved in the database?

**Comment by Kjehad94** [comment]
Yes I checked and solved it, the problem was to where shall I call it and after `refreshPublicSharesListFromDB` it wasn't work also because first time it called before OnCreateView and the initialization was from ShareActivity.Java class.

Then the only way to change in UI was by calling getView method and change it in the refresh capability part, so whenever it is initialized it will change the ui depending on the JSON object.

**Comment by davigonz** [comment]
I'm glad to know you've finally fixed the problem. I will close this issue, please if any other problem arise do not hesitate to ask us 👍
