### ISSUE TITLE
deletion of files may lead to data loss

### ISSUE THREAD

**Issue by danield5732** [owncloud/android#2061]
### Actual behaviour
- deleting a file in the app leads to deletion from mobile and from server
- the file is moved to trash at the server
- the file is NOT moved to trash at the mobile
- if the file on mobile was modified and not manually synced it is lost

This especially might happen when the updated file is uploaded again that causes automatical renameing insteadt of questioning for replacement. In this case the user will delete the old file first and unintentional delete it at the mobile simultaneously.

### Expected behaviour
- the app shoud check if the versions at the mobile and at the server is identical
- at least deleted files should be moved to trash at mobile, too
 
### Steps to reproduce
1. open a pdf via owncloud mobile app
2. modify the pdf and safe 
3. delete the file via owncloud mobile app
4. try to restore the modified pdf

### Environment data
Android version: 6.0

Device model: Aquaris M10 FHD

Stock or customized system: Build 2.3.0_20170405-1553

ownCloud app version: 2.5.0

ownCloud server version: 11.0.3

**Comment by davigonz** [comment]
Hi @danield5732 , thank you for your feedback, I'm trying to reproduce the problem you detail here by using a pdf editor and what I understand here is that you are requesting the next features:

1. Upload to the server the last version of a file just after updating it, without having to tap it to perform the check with the server version and update it if it is not the same. 

2. When the user performs an upload of a file that already exists on the server, ask the user for renaming or replacement, instead of renaming and uploading it directly.

3. Implement a new option named something like "Deleted files" with the possibility to restore deleted files. 

Am I right?

**Comment by danield5732** [comment]
Hi @davigonz , thank you for your answer! I think your three options would prevent the unintended data loss very well.

to 3.: if this option is dedicated to mobile, then it's right. Because the server is already working this way, I think.

Best, Daniel

**Comment by jesmrec** [comment]
1 -> already with document provider
2 -> will need more discussion
3 -> Trashbin feature.

Feel free to reopen if you need extra info.
