### ISSUE TITLE
Still no support to save file in SD card -- Bye bye

### ISSUE THREAD

**Issue by cheesecracker** [owncloud/android#2114]
### Actual behaviour
- NOTHING happens in more than four years

### Expected behaviour
-Expected feature to be implemented ages ago
 
### Steps to reproduce
1. Ask once
2. Ask twice
3. Ask and ask

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes, anywhere, everywhere

I'm leaving ownCloud: this forum, the newsletters.  It's been many years and this is never done.

Better use my time to look for alternative.

Maybe when they see that their user base is in the decline that they would wake up to see what is more important for users.

BYE BYE

**Comment by jesmrec** [comment]
@cheesecracker i'm sorry if you are not satisfied, but please, you have to take in account several things:

- We receive a lot of proposals regarding many features of the app. 
- SD card sounds as a very cool feature, but other considerations have to be taken in account. Also, many people is against the feature due to security issues. 
- This issue is duplicated in https://github.com/owncloud/android/issues/10. You opened a new issue about something existing in another one. 

We will take in account your comment anyway.

Closing this, if you desire to comment anything regarding SD support, please post in in the mentioned thread.

**Comment by cheesecracker** [comment]
-  FYI: Someone sent me a private message telling me that NextCloud has already implemented this cool feature
- I don't know what "security issues" it's about.  But we cannot live in the shadow of the fear.  We need to go forward.  We can always inform user of eventual security issues before letting them choose SD card.
- I knew #10.  I have subscribed on that.  I opened this issue NOT to duplicate that issue, but to express my disappointment LOL and let people know how slow things are moving.

BYE
