### ISSUE TITLE
New downloaded/offline available icons + pins

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2145]
Through [this](https://github.com/owncloud/android/issues/2081) issue here we came to the conclusion that we might need new pin designs in order to keep UI consistence. We tried to take an approach equal to what was suggested [here](https://github.com/owncloud/ios/issues/927) for the iOS version.

Instead of showing two labels when a file is marked offline available and downloaded we only show the marked as offline available, since that will make sure that the file is downloaded anyway. 

### This is what it would look like

<img src="https://user-images.githubusercontent.com/1891273/37282263-16192b2e-25f4-11e8-9450-7ff021268821.png" width=300px/>
<img src="https://user-images.githubusercontent.com/1891273/37282265-1652c62c-25f4-11e8-8c3d-f0898425355b.png" width=300px/>

**Comment by theScrabi** [comment]
This is what it currently looks like
![screenshot_1521038508](https://user-images.githubusercontent.com/1891273/37409407-91048512-279e-11e8-8ec3-166c23519c2b.png)
![screenshot_1521038517](https://user-images.githubusercontent.com/1891273/37409408-91300958-279e-11e8-9663-45f701e6e21d.png)

**Comment by davigonz** [comment]
@theScrabi you could use tables to compare previous with current UI, something like 

| Current filelist labels | New filelist labels  | 
| ------------- |:-------------:| 
| ![current_file_list_labels](https://user-images.githubusercontent.com/1891273/37409407-91048512-279e-11e8-8ec3-166c23519c2b.png) | ![new_file_list_labels](https://user-images.githubusercontent.com/1891273/37282263-16192b2e-25f4-11e8-9450-7ff021268821.png) |

In this case, it doesn't look so nice because the screenshots have different size.
