### ISSUE TITLE
Notification: Wrong timestamp is shown

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/android#2188]
### Actual behaviour
![screenshot_20180414-214804](https://user-images.githubusercontent.com/22525368/38772068-8bc50c04-402e-11e8-9954-f15e6be9d542.png)

### Expected behaviour
The timestamp should be the time I started the upload (~2 seconds before)
 
### Steps to reproduce
1. Open app
2. Upload image

### Environment data
Android version: 7.1

Device model: Oneplus X

Stock or customized system: LineageOS 14

ownCloud app version: 2.7.0-beta1

Just from looking at the code, there is a "setWhen" missing: https://github.com/owncloud/android/blob/master/src/com/owncloud/android/files/services/FileUploader.java#L900
Same for FileDownloader.java and maybe more

**Comment by theScrabi** [comment]
I have that bad feeling that this timestamp shown isn't even doing something useful. Maybe we can remove it.
@davigonz what do you think.

**Comment by davigonz** [comment]
Thanks @mueller-ma for reporting this issue

> I have that bad feeling that this timestamp shown isn't even doing something useful. Maybe we can remove it. @davigonz what do you think.

@theScrabi the mentioned timestamp could be relevant to the user since is used in the notifications panel to sort the notifications by time.

> Just from looking at the code, there is a "setWhen" missing

Yes @mueller-ma , you are right, we have already used that option when reproducing an audio file (https://github.com/owncloud/android/blob/master/src/com/owncloud/android/media/MediaService.java#L649). 

Following that example and now that you have had a look at the code, you could contribute with the solution. What do you think? 😉

**Comment by mueller-ma** [comment]
Having all in #2192 would be the best, wouldn't it? ;)

**Comment by theScrabi** [comment]
I think its better to discuss here.

**Comment by davigonz** [comment]
> Having all in #2192 would be the best, wouldn't it? ;)

@mueller-ma That PR is going to remove the timestamp, not implement your expected behaviour - The timestamp should be the time I started the upload. 

As I said in my previous comment, I wouldn't delete it but implement it properly by using `setWhen(System.currentTimeMillis());` so I would close #2192, do you agree @theScrabi?

**Comment by theScrabi** [comment]
I aggree.
