### ISSUE TITLE
Option not insta upload on mobile data

### ISSUE THREAD

**Issue by Yoshimanly** [owncloud/android#2201]
It's not really a problem, but I find it really annoying having to manually upload my photos because instant upload dosent have the feature to not upload when using mobile data, I still want to have access to my files when on mobile data, so no the fix is not going to options a disabling it.

**Comment by davigonz** [comment]
Hi @Yoshimanly , 
if I've understood well, your problem is that you want your photos to be automatically uploaded only when you are using wifi, isn't it? If so, there's an option for that purpose in Instant Uploads settings, which is **Upload pictures via wifi only**. Could you give it a try and tell us if it works for you? Thanks

**Comment by Yoshimanly** [comment]
Sorry @davigonz, I posted to the wrong place, I'm running ios, if u could help me anyway it would be amazing, thank you

**Comment by theScrabi** [comment]
@Yoshimanly please take a look at our [ios app](https://github.com/owncloud/ios) then. We are not responsible for iPhone :)

**Comment by Yoshimanly** [comment]
@theScrabi Oh okay, thank you ^^

**Comment by davigonz** [comment]
Let's close this then...
