### ISSUE TITLE
Improvements in "Descending" file list sort method

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2224]
Currently, the "descending" option to sort the file list is placed within the action bar menu as following:

![device-2018-05-15-184407](https://user-images.githubusercontent.com/14894746/40071510-409aed42-5871-11e8-81e4-1b23ce8c2d5f.png)

We can improve this behaviour in two different ways:

- By changing the wording to `Sort descending` , so only the word `Descending` can be confusing 
- By setting the option in the same dialog as the sorting method, in the bottom as a checkable option:

![device-2018-05-15-184549](https://user-images.githubusercontent.com/14894746/40071575-77412c4e-5871-11e8-8f9a-f52a8018bd37.png)

CC @michaelstingl

**Comment by michaelstingl** [comment]
@cdamken @voroyam @lefherz @pmaier1 what do you think?

**Comment by voroyam** [comment]
The more options to sort the files the better, imo.

**Comment by michaelstingl** [comment]
@voroyam The question is: Where to show the "Descending" menu item?

**Comment by voroyam** [comment]
In the sort dialog

**Comment by theScrabi** [comment]
> In the sort dialog. BTW, "smallest - largest" makes more sense to me than "smallest - biggest". Files are large, not big.

true.

> In the sort dialog

I've tried that, at the beginning, however it's not quite trivial to put it there since that menu only accepts either radio buttons or checkbox buttons, but not both. Supporting both would require to create a new layout.

Could you be convinced to something like that:

#### aproche 1
![screenshot_1526630418](https://user-images.githubusercontent.com/1891273/40223497-8f17c8b4-5a83-11e8-8f59-c8b6ce2b17bf.png)

#### aproche 2
![screenshot_1526630625](https://user-images.githubusercontent.com/1891273/40223504-9624fc26-5a83-11e8-9f0d-21c40e737fe5.png) ![screenshot_1526630632](https://user-images.githubusercontent.com/1891273/40223506-9640500c-5a83-11e8-93e5-c9eeb0bd1472.png)

**Comment by davigonz** [comment]
I would choose the second approach

**Comment by jesmrec** [comment]
First approach overloads the menu. The menu is intended to be a list of available options and there are mixed checkbuttons, radiobuttons and other options, not a good UX from my POV. Second option is better so the main menu structure remains and  it is clear in the sort view the available options.

**Comment by theScrabi** [comment]
here is an implementation of the second suggestion: https://github.com/owncloud/android/pull/2226

**Comment by jesmrec** [comment]
Are the cloud pic and the background image in the top of the drawer brandable?

**Comment by lefherz** [comment]
idea - what if we leave out the descending option, and instead make it descending, when people tap on "A-Z" the second time, even if it's already chosen? so if "A-Z" is checked right now, user taps on "A-Z", the option morphs to "Z-A"? then we could get rid of the ugly descending checkbox.

**Comment by theScrabi** [comment]
Well but the checkbox can be combined with all the other options. If we really wanted to replace it we had to add 3 more options. @lefherz why do you think [this](https://github.com/owncloud/android/pull/2226#issuecomment-391257298) solution is ugly?

**Comment by jesmrec** [comment]
we can create a separate issue to be scheduled with this enhancement. It does not have room for 2.8.0 (current milestone)
