### ISSUE TITLE
Instant photo/video upload works only when the App is open. 

### ISSUE THREAD

**Issue by byTschus** [owncloud/android#2285]
The feature "Instant Upload" don't work. It uploads the pictures/videos when i open the App. 

It should upload pictures/videos everytime i make a record. Not until I open the App.

### Environment data
Android version:
Android 8.0
Device model: 
Huawei Mate 10 Pro
Stock or customized system:
EMUI 8
ownCloud app version:
2.8
ownCloud server version:
10.0.9

**Comment by jesmrec** [comment]
Feature instant upload does not exist anymore in the app. It was replaced by "Camera uploads", that are not instant, so you have to wait (in average) 15 minutes until job scheduler get the pics and upload them  to oC. The reason is that Android is cutting off background processes to save battery, so the processes we use (in background) to run to check if new pics/videos were taken can not be keep alive.

**Comment by davigonz** [comment]
Hi @byTschus , did you finally make the camera uploads work?

**Comment by jesmrec** [comment]
Camera uploads totally reworked. Feel free to reopen if problem persists
