### ISSUE TITLE
Warn users to select the correct camera folder (camera uploads)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2303]
We have noticed that some users get confused with the "Camera folder" field of camera upload's settings. An incorrect selection in this field makes camera uploads not to work. 

The idea is warning the users to select the correct camera folder (folder in which the camera stores the pics and videos) when the feature is enabled (either pics or videos). An alert should be enough.

Considerations:

- Sometimes the internal and external storage path is the same, so here also we can point to confusion
- Non-skilled users (maybe) do not understand or know how to select it. We should make this process easy for users and this is not trivial.
- If the device default camera app changes, should be changed in the app. Could we detect this change to alert the user?
- The nicest way would be detecting automatically which is the path of the default camera, so the users do not have to select it manually. Does the Android API provide such info?
 
CC @michaelstingl @davigonz

**Comment by michaelstingl** [comment]
@hannesa2 what's the storage location of the camera app you are using? What location did you select in the app settings?

**Comment by hannesa2** [comment]
picture from camera are stored at `/storage/emulated/0/DCIM/Camera`
I specified same directory in app, but in Owncloud there are just two files and no sync is done

**Comment by michaelstingl** [comment]
This issue is more about user errors, where people aren't aware that camera storage location and ownCloud settings doesn't match.

Otherwise it works pretty fine with 2.9+ versions. Maybe you could open a separate issue for your problem. You can build the app with logging enabled. It should show where the problem is.

![camera_folders](https://user-images.githubusercontent.com/214010/49540740-1d67df00-f8d1-11e8-9a17-3886fe47e5ee.png)

If `/storage/emulated/0/DCIM/Camera` is configured in the ownCloud app, the right image will never be auto-uploaded.

**Comment by hannesa2** [comment]
As I understand, It looks not bad on  my side
![image](https://user-images.githubusercontent.com/3314607/49541336-cd8a1780-f8d2-11e8-8a3a-c223785b1aab.png)

An I see I've to solve it by myself

**Comment by michaelstingl** [comment]
@hannesa2 those are all very valid points, but unrelated to this issue "Warn users to select the correct camera folder". Please open another issue, so we can focus on every problem individually.
