### ISSUE TITLE
Production and debug version can't be installed on same device

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2393]
It happen with version 2.9.3 and the app declaims about authorities 

And there is an old one https://github.com/owncloud/android/issues/1091 too

**Comment by hannesa2** [comment]
In this https://github.com/owncloud/android/pull/2391 there is a commit https://github.com/owncloud/android/pull/2391/commits/fee4f6ef8e2b70ab877edbb90577b8bb6fbe78bf which solves it.
Unfortunately this https://github.com/owncloud/android/pull/2076 has no progress, that's why I've to do in `build.gradle` otherwise I would overwrite it in `debug` directory. But with Eclipse structure it's not possible 👎

**Comment by hannesa2** [comment]
But now I run into next issue. Prod and debug version try to use same account, but `ExistenceCheckRemoteOperation.java` prevent to use it
https://github.com/owncloud/android-library/blob/7dc611cd1444914bdd71615fa54b053d7c429ad1/src/com/owncloud/android/lib/resources/files/ExistenceCheckRemoteOperation.java#L116

What's the best way to enable this ?

**Comment by hannesa2** [comment]
@davigonz do you have an idea ?

**Comment by davigonz** [comment]
@hannesa2 I fixed https://github.com/owncloud/android/pull/2391#issuecomment-467851048 locally, gave it another try and I was able to install both debug and release apks at the same time but the error I get is different from what you have:

```
java.lang.IllegalArgumentException: Trying to execute a sync operation with a NULL storage manager
        at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:109)
        at com.owncloud.android.ui.activity.FileDisplayActivity$5.run(FileDisplayActivity.java:1725)
```

This error is triggered because the storage manager is never created due to https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java#L155 is not called because there's no new account when installing release apk after debug one but the same account.

With those hints, you could keep working on it via https://github.com/owncloud/android/pull/2391

**Comment by davigonz** [comment]
We are about to release 2.10 version so let's put this off till 2.11.

**Comment by davigonz** [comment]
Closing this since is no longer a priority (https://github.com/owncloud/android/pull/2391#issuecomment-473248349) , reopen if needed
