### ISSUE TITLE
Please add support for ownCloud 7/8 back into Version >=2.9.3

### ISSUE THREAD

**Issue by drtrigon** [owncloud/android#2433]
### Actual behaviour
- Installed the most recent version of the client (due to OS update to Android 7 etc.) and now I cannot setup an account anymore. It throws an error "Fehlerhafte Server Konfiguration". My server uses an own certificate I have to confirm first once.

### Expected behaviour
- I should be able to setup my account and use the client. The server configuration has not been changed and it used to work before. Also DAVx5 connections for contacts and calendar still work.
 
### Steps to reproduce
1. Try to setup your account - while testing the connection it throws the error mentioned and refuses to continue

Can this problem be reproduced with the official owncloud server? No
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: Fairphone Open 18.10.0 (Android 7)

Device model: Fairphone 2

Stock or customized system: one of the stock systems

ownCloud app version: 2.9.3 (from fdroid)

ownCloud server version: 

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by drtrigon** [comment]
As FolderSync for ownCloud 7/8 works I suspect it beeing an old protocol. Could you please add support for it back in? I used to be there...

**Comment by michaelstingl** [comment]
@drtrigon the ownCloud Android client used an ancient networking library for a long time. The [main issue with discussions](https://github.com/owncloud/android-library/issues/51) was opened back in 2015. In 2018, the team invested heavily in fighting technical debt, so they started to migrate to the widely used [OkHttp](https://github.com/square/okhttp) library and worked with the DAVx5 (former DAVdroid) community on a [new WebDAV library](https://gitlab.com/bitfireAT/dav4jvm).

The ownCloud server version 9.1 introduced a new WebDAV endpoint in 2016 (see [release notes](https://doc.owncloud.org/server/9.1/admin_manual/release_notes.html)), and the advanced features, like reliable chunking, only work with the new endpoint.

Supporting both the new WebDAV endpoint and the old WebDAV endpoint would have meant doing the work twice in the replacement of the networking library and the new WebDAV library. Based on the fact, that pre-9.1 versions of the ownCloud server are [EOL since 2017,](https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule) , we decided to not do this effort.

You can download pre-2.9 versions through the F-Droid App, and there are many 3rd party tools that work well with the old WebDAV endpoint.

We did not a great job communicating this change. I'm very sorry for that, and I hope we'll do better in the future. Lessons learned.

**Comment by drtrigon** [comment]
Thanks for the intressting insights!

> You can download pre-2.9 versions through the F-Droid App, and there are many 3rd party tools that work well with the old WebDAV endpoint.

What would you recommend? What app, what version?

**Comment by hannesa2** [comment]
An other way could be to makes it yourself.

These are the recent tags 
<img width="179" alt="image" src="https://user-images.githubusercontent.com/3314607/52531271-dbb14580-2d12-11e9-845f-0096ed427970.png">
Checkout eg `git checkout -b oc-android-2.8.0 oc-android-2.8.0` and build your own version, but of course, you have to handle the release keystore for your own. 
This needs some extra work https://github.com/hannesa2/owncloud-android/commit/a6d8e4a385d1b9d511865dda6e217904a7e91791 I checked-in everything encrypted and Travis knows the password

**Comment by michaelstingl** [comment]
> What would you recommend? What app, what version?

2.8.0 works fine with the older ownCloud versions. It's in the “F-Droid Archive” repository. Also _FolderSync_ you mentioned is an awesome app.
