### ISSUE TITLE
different types of upload

### ISSUE THREAD

**Issue by mstojanovic** [owncloud/android#2575]
due to the change in #2436 the previously available choices for upload (copy, move) are now not possible, and this is a feature i heavily relied on. also, awaiting for review on the expansion of the choices available in #2509 is obsolete (added to 2.12.0 milestone)

it would be great if we can have those 3 options back (copy, move, remove) as a prompt on each upload or even better as a default choice in the settings (which i guess its not the best option for most users)

**Comment by jesmrec** [comment]
We will have to research the options inside the native implementation to keep the same features as before. Thanks for the requests.

**Comment by PVince81** [comment]
Am also missing this option.

My workflow is that I usually that when I come home from a busy day, I'll upload all pictures from the DCIM folder to a temporary folder on ownCloud with "move" mode, because I don't want to upload them again later on, nor keep them on the device as I'll archive them on my computer. (I'm not using instant upload due to bandwidth limits) Then when I ever turn on my desktop computer, I have the desktop client there that will download the pictures and then I'll import them into digikam and remove from ownCloud.

If the native way is not possible from inside the OC app, maybe there's another way by having a file manager move the files into the OC folder ? I saw something that was telling that the OC Android app now integrates better with native apps ?

**Comment by davigonz** [comment]
Thanks for sharing your thoughts @mstojanovic and @PVince81 , I see your point, this decision was taken because the more we integrate the app with the Android system, the better, in terms of user experience and less amount of bugs to take care of. 

> If the native way is not possible from inside the OC app, maybe there's another way by having a file manager move the files into the OC folder ? I saw something that was telling that the OC Android app now integrates better with native apps ?

Yes, now we can manage oC files from the [Document Provider](https://central.owncloud.org/t/owncloud-2-11-for-android-released/20515),  and move files to the ownCloud app will be addressed via https://github.com/owncloud/android/issues/2496 so do not worry, we will put the move option back but in a better way, using the document provider.

**Comment by mstojanovic** [comment]
@davigonz:
> Thanks for sharing your thoughts @mstojanovic and @PVince81 , I see your point, this decision was taken because the more we integrate the app with the Android system, the better, in terms of user experience and less amount of bugs to take care of.

any idea when that should be officially released?
is there a chance to add a 'remove' option too. i.e. just to upload the files and not make them available offline by default?

**Comment by davigonz** [comment]
> is there a chance to add a 'remove' option too. i.e. just to upload the files and not make them available offline by default?

From now on the upload will depend on the features that Android Document Provider provides and this provider is the responsible of copying/moving files between different apps and internal folders. So if you move some files to ownCloud, they will be automatically uploaded to ownCloud and removed from the original folder, but not removed from the destination folder (ownCloud folder) as you propose.

**Comment by mstojanovic** [comment]
well... i guess since its planed to re introduce the options then this issue can be closed.

ty for your answer

**Comment by jesmrec** [comment]
will keep the reference from the pertinent document provider issue
