### ISSUE TITLE
ownCLOUD App Android crashes permanent

### ISSUE THREAD

**Issue by KlausThomasMueller** [owncloud/android#2580]
### Actual behaviour
-ownCLOUD App crashes frequently when connected to ownCLOUD server.

ownCLOUD server runs on Linux Mint
-Main user has around 450GB data in 150.000 files
With this user, I'm not able to work

-Second user created specially for the mobile phone has around 45GB in 8.000 files (manly pictures and videos) operates mostly.

![A_Screenshot_20190618-105900_Software update](https://user-images.githubusercontent.com/50458780/59671816-a0da8500-91be-11e9-9f8e-2165e9baa0d0.jpg)
![A_Screenshot_20190501-214731_Device maintenance](https://user-images.githubusercontent.com/50458780/59671817-a0da8500-91be-11e9-8aad-bcc857543417.jpg)
![A_Screenshot_20190511-225022_ownCloud](https://user-images.githubusercontent.com/50458780/59671818-a0da8500-91be-11e9-9ec9-755d55269f14.jpg)
![A_Screenshot_20190511-221324_Clock](https://user-images.githubusercontent.com/50458780/59671819-a0da8500-91be-11e9-8b1d-0b79a6f55f3b.jpg)
![A_Screenshot_20190511-071605_ownCloud](https://user-images.githubusercontent.com/50458780/59671820-a1731b80-91be-11e9-9234-b4ad6ee888ba.jpg)
![A_Screenshot_20190509-191442_oCloudde](https://user-images.githubusercontent.com/50458780/59671821-a1731b80-91be-11e9-8692-b823449865fe.jpg)

### Expected behaviour
-Tell us what should happen
 My target was to have a system like I'm used from my company where oneDrive provides me all files an all systems (laptop, tablet and mobile phone).

Because of the volume, it should also be possible to shift the ownCLOUD folder to the extrnal SD with 128GB for the offline available files.

I'm using the system in the moment only as backup with foldersync.

### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, too less files

### Environment data
Android version:
A520FXXUACSE6/A520FOXXAACSE6/A520FXXUACSE6 (05.01.2019)
Device model: 
Samsung SM-A520F

Stock or customized system:
Stock system

ownCloud app version:
Version 2.11.0 (06.13.2019)

ownCloud server version:
ownCloud 10.1.1 (stable) 

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hi @KlausThomasMueller , first of all, thanks for reporting this. We are aware of the crashes that are taking place in the app recently and we have put the focus on fixing them, e.g. https://github.com/owncloud/android/issues/2560. 

I think all the information you attach might be helpful to find the cause of the crashes but without steps to reproduce is even more difficult, so I have a couple of questions:

1. Are you using camera uploads or available offline files? These two features use jobs in background and we suspect they have something to do with the crashes since some of your crashes appear while you are using other apps.
2. It seems some of your crashes are triggered in the uploads view, is something you can reproduce with specific steps or is kind of random?

Thanks

**Comment by davigonz** [comment]
@KlausThomasMueller I see you are using 2.11, could you send us some logs? First, you need to enable the Developer Menu by tapping 5 times the app version within Settings and you will see the Logs section.

![52464638-f4d3be00-2b7b-11e9-891f-ef98eb96934f](https://user-images.githubusercontent.com/15261363/59701759-9340f180-91f6-11e9-9a32-44baf55fb9f8.gif)

**Comment by KlausThomasMueller** [comment]
Hi David,

attached you find the log. It should not be published
somewhere in the WEB.

Yes, I'm using photo and video upload. This was one of the main reasons to use a own cloud storage to save the photos from our mobile phones.

As it seems not to be possible to switch the storage location for offline files to the external SD-Card, I only made some tests.

My screenshots are manly from the upload, but this is more by accident.
With my main user, it crashes so fast, that you are nearly not able to switch within the menu.
There is nothing to reproduce.
Think it depends on the number of files and size of the data on the storage.

As I wrote, I'm using FolderSync to backup the Androids and OwnCloud Desktop with Linux and Windows.


⁣Mit freundlichen Grüßen

Klaus Müller
Ulmenweg 50
63741 Aschaffenburg

Tel. +491713172769


Gesendet mit Blue ​

**Comment by davigonz** [comment]
Thanks @KlausThomasMueller for your answer.

The screenshots related to uploads are not crashes but ANR (application not responding) errors and that issue is already reported in https://github.com/owncloud/android/issues/2212 and it will be faced later. Anyway, your logs will be very helpful but I do not find them, how did you send them? You could send us an email to android-app@owncloud.com

**Comment by jesmrec** [comment]
Logs received. Thanks!

**Comment by jesmrec** [comment]
Is this still reproducible? @KlausThomasMueller
