### ISSUE TITLE
[New arch] Stop supporting <10 servers

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2636]
We have a bunch of constants to consider specific cases for servers with < 10 versions.

![Screenshot_2019-08-21_at_16_12_38](https://user-images.githubusercontent.com/15261363/63439697-d1dd6d00-c42e-11e9-897f-881570811735.png)

@michaelstingl what about removing them? Removing just a couple could help us a lot for handling ownCloud clients in a proper way, as I detailed in https://github.com/owncloud/android/issues/2635

### PRs:
- App: https://github.com/owncloud/android/pull/2756
- Library: https://github.com/owncloud/android-library/pull/286

### Old PRs, need to pick the commits from there and put them in the new branches
- App: https://github.com/owncloud/android/pull/2648
- Library: https://github.com/owncloud/android-library/pull/265

**Comment by michaelstingl** [comment]
> @michaelstingl what about removing them?

@davigonz Sure. New iOS app is also oC10+.

Who do we need version mapping at all? Preferred way would be to read the capabilities for a feature from the server?

**Comment by abelgardep** [comment]
Which should be the expected behaviour here?

- Showing a snackbar with an action that will send the user to the login view (The user could use the app and may have inconsistiences reported here: https://github.com/owncloud/android/pull/2648#issuecomment-536497298) [Current status of this PR #2756]

- Showing a dialog that cannot be dismissed with an action that will send the user to the login view (The user won't be able to use the app with an old server)

@jesmrec @davigonz @michaelstingl

**Comment by davigonz** [comment]
> Showing a dialog that cannot be dismissed with an action that will send the user to the login view (The user won't be able to use the app with an old server)

I would go for this one

**Comment by abelgardep** [comment]
Ready to CR @davigonz 👍
