### ISSUE TITLE
[BUG]The photos/videos auto-synced to unexpected account and more chaos

### ISSUE THREAD

**Issue by NiceFeather** [owncloud/android#2718]
I have three user accounts which added into the app and located at left panel. but there are some issues of account chaos as following:

1. **Chaos in account switching**, almost of times all of contents combined with the account wasn't working properly in right file list view;
2. **The photos/videos auto-synced to unexpected account**. Since there is no account where the photo/video is mapped in the Settings, the unexpected account is automatically synchronized after the photo is completed. this is also a special case of account confusion.

**Comment by NiceFeather** [comment]
Another use case, while sharing anything through ownCloud, there is displayed up accounts selection dialog, but these accounts are problematic and cannot continue to be selected.

![SmartSelect_20191114-171816_ownCloud](https://user-images.githubusercontent.com/28109556/68844821-604b4d00-0705-11ea-8889-53f661071d2d.jpg)
![SmartSelect_20191114-172040_Solid Explorer](https://user-images.githubusercontent.com/28109556/68844839-67725b00-0705-11ea-9c3f-c4a04bae4409.jpg)
![SmartSelect_20191114-173843_ownCloud](https://user-images.githubusercontent.com/28109556/68845032-bae4a900-0705-11ea-8628-cb90ba41045d.jpg)

**Comment by davigonz** [comment]
Hi @NiceFeather , thanks a lot for your feedback, we really appreciate it, but could you open different issues for each bug you have detected? Otherwise, we will lose focus.

I see here three different issues:

1. Photos/videos are uploaded to unexpected account. Allow to choose specific account when using automatic (camera) uploads.
2. Account switching mix up the files
3. Use username instead of full name when showing accounts dialog for sharing

We could keep this issue to fix the issue 1, Photos/videos are uploaded to unexpected account. Regarding that issue, I would also like to know what is the behaviour you expect:

1. Show a dialog to choose an account when enabling automatic (camera) uploads
2. Allow multiaccount within automatic (camera) uploads

**Comment by NiceFeather** [comment]
> could you open different issues for each bug you have detected? Otherwise, we will lose focus.

Sure no problem, I'll report single issue everytime in later.

>  I would also like to know what is the behaviour you expect

Actually, how can this function be close to the user behaviour habit, this design is not simplly, I personally prefer the first design, but not showing up an account selection dialog, need to **carry on the account selecting/assignment to the photo/video uploads directory in advance in the Setting**. It is clear that it is impossible to ask a user to choose an uploaded account after taking a photo, which would make the user hate the processing.   

As for the second, it should not be consistent with the user requirements, most people can not have the need to send photos to multiple accounts.

**Comment by jesmrec** [comment]
Stuff related:  https://github.com/owncloud/android/issues/2651

**Comment by jesmrec** [comment]
Mixed list of files fixed
Currently, camera uploads allows to select the account to upload to.
