### ISSUE TITLE
Remove deprecated logs

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2757]
During #2730, some logs functions were deprecated in order to avoid a big refactor and posible conflicts with new architecture modularization. Now, modularization has been merged so these deprecated functions can be removed and replaced with new ones.

![Screenshot 2019-12-11 at 13 33 32](https://user-images.githubusercontent.com/47524927/70621877-e67e8480-1c1a-11ea-927e-44e42325c133.png)

### PR

- App #2770 
- Library (if needed) https://github.com/owncloud/android-library/pull/293

**Comment by hannesa2** [comment]
Please switch direct to `Timber` and **delete** `Log_OC` complete, then I can get rid of the need of https://github.com/JakeWharton/timber/pull/371 and can use common upstream version instead of special version which support [delegation](https://github.com/hannesa2/Logcat/blob/5cba849239a0d71ef21f69d91c986c875c16b580/LogcatLib/build.gradle#L28-L29)

**Comment by hannesa2** [comment]
It's not a hard requirement for this timber-only task, but I start to remove it https://github.com/hannesa2/Logcat/pull/31

**Comment by abelgardep** [comment]
To move this forward as soon as possible, it would be great to know how to approach this. 
3 options:

- Keep using Log_OC but updated methods.
- Switch direct to Timber not removing Log_OC
- Switch direct to Timber removing Log_OC. This may leads to problems to other people who use the library to log.

@davigonz @jesmrec @michaelstingl

**Comment by davigonz** [comment]
`Log_OC` is meant to log the ownCloud App for Android and oC Android library and I think that we should not maintain it just because it could be used by other apps using the library, our library is not a logging library but "an easy way to communicate Android apps with ownCloud servers". Logging is an additional task that any app using the oC Android library should take care of in my opinion.

Said this, I would implement the last option **Switch direct to Timber removing Log_OC**
