### ISSUE TITLE
[CI] Create public project on Bitrise.io

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#2767]
<img width="986" alt="Add_new_App_-_Bitrise" src="https://user-images.githubusercontent.com/214010/71156832-15ab7c00-2241-11ea-89c0-d32a5adb4cb5.png">

More info:
https://blog.bitrise.io/free-developer-plan-features-for-open-source-projects-on-bitrise

**Comment by jesmrec** [comment]
Created three new apps to handle the actual jobs in a public way:

![Screenshot 2021-03-30 at 15 00 00](https://user-images.githubusercontent.com/14894746/112993165-30b9ab00-9169-11eb-99e0-9ada7fad50fa.png)

Next steps:

- Add the jobs' webhooks to the GitHub repositories, in order to execute the public ones instead the  private ones (i do not have permissions to do this. Howto: https://github.com/bitrise-io/bitrise-webhooks#github---setup--usage)

- Test the jobs and check everything is correct (let them a couple of days)

- Rename the apps in BitRise (get rid of the `NEW (public)` prefix

- Remove the private apps in BitRise after the tests with the public ones are OK

I have tested the new jobs, by accessing them with no credentials (incognito window, other browser) 

Actions available:

- View the list of builds
- View and download the builds's logs
- View the `bitrise.yml` file (no important info is revealed here)
- Apply some filters
- View/Download the artifacts. Final artifacts will be available under the deploy URLs that can be checked in the logs: 

<img width="1195" alt="Screenshot 2021-03-31 at 09 37 07" src="https://user-images.githubusercontent.com/14894746/113108167-faca0480-9204-11eb-8f58-495876caf44b.png">


Actions not available:

- Check/manage the organization
- Check/manage the workflows
- Check the `Test Report`  addon

**Comment by jesmrec** [comment]
Public projects were  created and are already available and active. Nothing else to do here.

Feel free to reopen if something else is missing.
