### ISSUE TITLE
App crashes on opening any suggestions

### ISSUE THREAD

**Issue by kalnav** [owncloud/android#3013]
### Actual behaviour
-Tell us what happens

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
@kalnav could you detail the problem you are reporting please?

**Comment by xaviergouardes** [comment]
Hello, I have the same problem today.

**Actual behaviour**
-Tell us what happens : I just bought the app on the android play store. When I launch it, it closes immediately.

**Expected behaviour**
-Tell us what should happen : When I launch it, i can use it.

**Steps to reproduce**
1 - Buy the application on the android play store
2 - open it
3 - it closes immediately

**Environment data**
Android version: 10 QKQ1.191215.002
Device model: Smartphone RedMi 9S MUI 12.0.1
Stock or customized system:
ownCloud app version: I don't know if I bought it on 08/11/2020
ownCloud server version:

**Logs**
- I don't know how to recover log files

Thank you for your help,

Xavier,

**Comment by jesmrec** [comment]
Hi @kalnav . We released a new version some days ago. Did the problem still happen on your side?
