### ISSUE TITLE
Top bar icon is the app icon

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#305]
Currently the icon in the top bar is the same as the app icon: White/light with rounded corners. This looks very off in the top bar.

Much like on iOS, the icon in the top bar should be the cloud in light/white, without anything around it, directly on the dark background of the top bar.

cc @MTRichards @rperezb @davivel

**Comment by donniezazen** [comment]
@jancborchardt @davivel Is there a place that documents the color codes used in ownCloud artwork?

**Comment by jancborchardt** [comment]
@donniezazen yes: https://github.com/owncloud/promo#logo

**Comment by donniezazen** [comment]
@jancborchardt @davivel One of the reasons the ownCloud logo is not centered in the screenshots I posted earlier is because the clouds image is wider than its height. Either we need to make another icon that fits well in the ActionBar or we can you an app agnostic icons like below. Google apps like Gmail, YouTube, Drive, etc. and other apps like Evernote, Runtastic, etc. all use hamburger menu aka the three horizontal lines.

![device-2015-05-08-144031-edit](https://cloud.githubusercontent.com/assets/841656/7533926/22d5f598-f593-11e4-8552-6f0929d2953e.png)
![device-2015-05-08-144243-edit1](https://cloud.githubusercontent.com/assets/841656/7533927/22d9a4b8-f593-11e4-8894-4c5c4f9aa0d1.png)
![device-2015-05-08-145715](https://cloud.githubusercontent.com/assets/841656/7533928/22dbb938-f593-11e4-8f68-b8d6e9e281e0.png)
![device-2015-05-08-145817](https://cloud.githubusercontent.com/assets/841656/7533929/22e3012a-f593-11e4-9cff-e40f223edfa0.png)
![device-2015-05-08-145857](https://cloud.githubusercontent.com/assets/841656/7533930/22e49a8a-f593-11e4-828f-bd491c86abe3.png)

**Comment by davivel** [comment]
You mean that the cloud image iself is wider than high, right? Because the full image file is square.

Personally I don't see any problem with the alignment. The clound itself is not symetric around its vertical center, so I just don't expect it looks perfectly centered.

For Material Design (Android 5 and later) Google recommends the hamburger menu, but we shouldn't consider that mandatory at all. Just to take in consideration, do not try to enable Material Design yet. There are build settings to consider before (coming soon).

**Comment by donniezazen** [comment]
The current logo with white background is a square image. The white background steals the focus and makes it look metrically aligned in the ActionBar.

The image with only clouds obviously has more width than height. When system places it in ActionBar it may or may not look metrically aligned. I can move the clouds down in an image background which blends with the color of ActionBar and try to make them look centered but with different text string how it looks can only be unpredictable.

![device-2015-05-08-185440](https://cloud.githubusercontent.com/assets/841656/7537325/a721f9c4-f5b5-11e4-9a8e-0df68ec1f374.png)
![device-2015-05-08-185447](https://cloud.githubusercontent.com/assets/841656/7537326/a72857b0-f5b5-11e4-8a26-18883ef83e2f.png)

As you can see the up button, logo, title, overflow menu icons are all out of the grid [1]. One thing we can do is to defer this issue till when we are ready to adopt material design. It would make sense to consider the whole ActionBar at that point of time. Also `android:logo` is only available for API 11 or above so that's another thing to consider.

PS:- By no means I am a designer, reality is far from it. I am just messing around with it. Thanks for engaging.

[1] http://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

**Comment by jancborchardt** [comment]
@donniezazen thank you very much for noting these design details. I think we really should rework in Material Design soon and fix this.

**Comment by sudhirkhanger** [comment]
This bug report is probably not valid as there's a hamburger menu now instead of app icon.

**Comment by AndyScherzinger** [comment]
True, @rperez you can close this one imho :)

**Comment by rperezb** [comment]
yep, @AndyScherzinger you may have closed it too :smile:

**Comment by AndyScherzinger** [comment]
Okay, will do that in the future :)
