### ISSUE TITLE
[FEATURE REQUEST] Proportional thumbnails

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3050]
Current thumbnails in Android app has squared shape. So, the miniature is only part of the pic.

left Android, right iOS:

![Screenshot 2021-01-13 at 14 50 56](https://user-images.githubusercontent.com/14894746/104460786-d1f38500-55ae-11eb-89cf-694540dbaf2a.png)

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
We'll try to fix with the current set up, using Glide and checking if it could be fixed easily

Moving from Glide to Coil (written in Kotlin and supporting coroutines) could be a good solution for this, but this stuff is dependant on [changes of the files view regarding new architecture](https://github.com/owncloud/android/issues/2869)

**Comment by fesave** [comment]
I just checked that the web version displays the images as the Android app does. I think if we change the thumbnail to proportional size these photos will lose detail and will not be distinguishable. Also, the grid view mode will be disproportionate as it contains square and other rectangular images. 

What do you think @michaelstingl , @tbsbdr ?

cc @jesmrec 

![pictures_web](https://user-images.githubusercontent.com/49989790/141274976-944eeb02-8bc0-4570-b34f-86c0684c5087.png)

**Comment by abelgardep** [comment]
From my point of view, proportional thumbnails have more cons than pros. 

I agree that with ultra-wide images, we lose so much detail and can not be easily distinguishable. I think that crop and center as we currently have is a good way to keep consistency across the whole file list. All images will have the same shape and it looks better in my opinion.

**Comment by JuancaG05** [comment]
I agree with @fesave and @abelgardep. Personally, I like it most when all the images thumbnails are displayed with the same shape (square in this case), as it creates a feeling of consistency (and better-looking I think). Consistency is also supported because it it shown the same way as in the web version.

**Comment by tbsbdr** [comment]
I guess something like this is the userstory:
**Userstory "find by preview"**
_As a user I want to see a filepreview so that I can find files just by looking at the preview (and not having to read the filename)._

--> I would bet, that both approaches -squared and rectangle- satisfy the users story nevertheless the drawbacks and advantages of both approaches.
 

But I agree with @abelgardep and @JuancaG05 
I would also stick with the squared preview, as it provides a more calm ui at first glance imo.

**Comment by jesmrec** [comment]
then we should move the discussion to the iOS team, where the thumbnails inherit the image shape. Same ideas should be implemented throughout the platforms
