### ISSUE TITLE
Align with 10.7 sharing behavior

### ISSUE THREAD

**Issue by pmaier1** [owncloud/android#3114]
## User story
As a user I want to share with other users by entering their email address. Currently I usually get two results when I search for a user
1. the real user on the system and
2. a federated user (because federation IDs have the same syntax like email addresses). As I'm not familiar with ownCloud specifics, I don't know what a "federated" user is.
As the lookup for the "real user" takes some time in my installation, it happens that I only see the "federated user" first. When I'm too quick, I click on it and see the share failing (because there actually is no federated user; I'm looking for the real user) which I don't understand. At this point I open a support request.

## Solution approach
Change the sharing autocomplete to only display the federated user 
1. once the regular user search has finished and
2. did not find results for the input provided

As a consequence in case that the entered email address matches a known user, only show that user.

**Comment by jesmrec** [comment]
The Android client reflects the server response, that depends (in this case) directly from the `Extra field to display in autocomplete results` option. I guess that the described case happens when the `Email` option is selected.

With such option selected, and typing the whole email address:

<img width="410" alt="Screenshot 2021-02-24 at 09 07 14" src="https://user-images.githubusercontent.com/14894746/108967441-d2883c80-767f-11eb-8ba1-cb1fcbdec66a.png">

we show both federated and local results to be chosen by the user. In case of a total match, you want to show only the email and getting rid of the remote result. Remote result will be shown only in case nothing else matches.

but my question is.. which will be the server 10.7 behaviour? I mean, will something change in the API? which is the real change in server we have to adapt in the client? 

Is there any deadline? (for prioritization/organization purposes)

**Comment by michaelstingl** [comment]
> 2\. As the lookup for the "real user" takes some time in my installation, it happens that I only see the "federated user" first.

Android app just renders the API response and isn't affected by the delay-problem.
