### ISSUE TITLE
[MDM] Platform setup

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3416]
[SPIKE] : https://github.com/owncloud/android/issues/3399
Once we've set the basic logic in the app to work with managed restrictions and testes it with Test DPC, we have to find a suitable EMM platform that we can use to manage remotely the app. The list of available platforms appears in the [AppConfig webpage](https://www.appconfig.org/). We'll have to test some of them and conclude which one is better for our purpose.

### TASKS

- [x] Decide which platform is the best for our testing purposes (then each client will use its own)
- [x] Try to manage the app configurations with the platform selected

### Findings

- JAMF doesn't offer support for Android anymore
- MobileIron needs payment
- IBM does offer a free 30 days-trial period without the need to contact a vendor

### Result
The platform we decided to use finally was IBM MaaS360. Quick guide: https://github.com/owncloud/android/issues/3416#issuecomment-966144612

**Comment by jesmrec** [comment]
[IBM MaaS 360](https://m6.maas360.com/emc/) allows to create 30-days trial accounts. 

Once you hace an account in that platform, integration with Android Enterprise must be done, by using an existing Google account. From this moment, it is posible to enroll devices using an URL with credentials or a QR code. Enrollment process will create work profile in the enrolled device.

Also, it contains an app "repository" and a "App Configuration" section (needed to be researched).

**Comment by JuancaG05** [comment]
The MDM platform we finally chose for testing purposes was IBM MaaS360.

### How to test MDM with IBM MaaS360
If it is the first setup you perform:

1. Change the default security policy for Android devices so that they can install non-Google Play apps (we'll upload an APK). To get this: _Security > Policies > Default Android MDM Policy > Security > App Security >_ Set
_Allow Installation of Non-Google Play Applications_ to "Yes".
2. Add a new user for you to identify in your device afterwards. For this purpose, go to _Users > Add User_ and follow the indications.
3. Add the device you are going to test the app on. Go to _Devices > Add Device_ and follow the instructions.
4. Add the ownCloud app. Go to _Apps > Add > Android > Enterprise App for Android_ and upload the APK built with the MDM flavor.
5. Inside the ownCloud app menu, declare the managed configurations. Go to _App Configurations > Add configuration_ and upload the XML with the definition of the managed configurations. In our case, this file is `managed_configurations.xml`, and it can be located in the resources of the Android project. Once this file is uploaded and configurations are shown with their default value, click _Next_ and in the Distributions tab, check _Set as default configuration_, check _Specific devices_ looking for your test device, and go back to Configuration tab to finally click _Save as draft_.
6. In _App Configurations_, go into the draft just created and click _Publish_.
7. Distribute the app to your test device. For this, inside the ownCloud app menu in _Apps_ section, click _Distribute_, write the name of your test device and follow the instructions.

If you have already registered and distributed the MDM app to your test devices:

8. Go to _Apps > ownCloud > Apps Configurations > (the configuration name you want to modify)_.
9. Click _Edit_ to modify the value of the configurations you want, check the changes in the next screen and finally, save the changes and publish the new configurations.
10. Go to ownCloud app in your test device to check the changes performed.
