### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mstojanovic** [owncloud/android#3487]
### Actual behaviour
after the switch to the more secure file management i can not access the files i download (green or purple icon) from other apps.

### Expected behaviour
if i download (green or purple icon) a file (picture, film, pdf,...) i want to be able to open it with another app on my phone or send it via e.g. a messenger.
 
### Steps to reproduce
1. open a file in the android app or set the file to available offline

Can this problem be reproduced with the official owncloud server?
yes

### Environment data
Android version: A11

Device model: Samsung A52s

Stock or customized system: stock, secret directory

ownCloud app version: 2.19

ownCloud server version: 10.4 i believe

### Logs
N/A since its not a crash

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/android/issues/3488 ?

**Comment by mstojanovic** [comment]
no. this is a separate problem #3488 was about in app use and sharing, this is about memory location and file not accessible/found after a download. if i download the file (green icon) i expect it to be available on the system. another stepping stone here is e.g.:
i have a pdf in my documents folder on my phone. i upload it to the server with the app. it shows a green download icon. i delete the source on the phone, green icon still shows but i can not find the copy on my phone.

this was reported as bug since 'downloaded' means available on the device and its not. so items marked as 'downloded' should have the file available on the device too. or remove that mark and add a proper download option (gdrive: downloads, mega: mega -> mega downloads)

anyway if i upload a file i dont need another copy on my system (even be it hidden), just bloats the memory (on the old, 'unsafe', system i at least could delete the copy bloat and the download mark would be removed until i redownloaded. also opening a file in the app should not download by default)

**Comment by abelgardep** [comment]
Thanks for opening the issue @mstojanovic 

There are several things to clarify about this.

### 1. Download status 

About the next statement: 

> this was reported as bug since 'downloaded' means available on the device and its not. so items marked as 'downloded' should have the file available on the device too.

Since ScopedStorage addition, the download concept in the ownCloud App is a little bit confusing. We are checking the [alternatives to Download concept in this issue](https://github.com/owncloud/android/issues/3289). At the moment, the green icon is just a way to show that the file is cached and that the file is available in the internal storage. 

It does **NOT** mean that the file is public and accessible without ownCloud or DocumentsProvider.

### 2. Export or Download option

About the next statement:
> or remove that mark and add a proper download option (gdrive: downloads, mega: mega -> mega downloads)

This is in our scope. We opened [an issue to export files out of scoped storage](https://github.com/owncloud/android/issues/3462). We do think that this functionality is necessary to enable again some use-cases that are missing since scoped storage.

### 3. Duplications, cached files...

> anyway if i upload a file i don't need another copy on my system (even be it hidden), just bloats the memory

I partially agree with you. We need to cache the file we need to upload till the file is uploaded successfully to the server. This is a necessary temporary duplication. We do this because the upload could fail and if the source file is deleted, we will have the option to retry the upload and not lose the file. It's data-loss protection. Once the upload is done, the duplicated file could be removed. I agree with you. Please check #3289, we already thought about that. Suggestions are welcome, feel free to comment there.

> on the old, 'unsafe', system i at least could delete the copy bloat and the download mark would be removed until i redownloaded.

At the moment, you can still do this within the ownCloud app. If the file is marked as downloaded, you can click on delete and select `delete local only`. That way, the downloaded file in scoped storage will be removed but the server file will be there. If you want to open it again, the file will be downloaded again. 

> opening a file in the app should not download by default

We are concerned about that. At the moment only the videos are streamed, we are planning on increasing the streamed files to audios(#2823), photos and so on, as well as improving the cache system to remove files that are stored and not used for a long time. -> #3289

Again, thanks for sharing your experience with the ownCloud App. Feel free to suggest anything else 👍

**Comment by mstojanovic** [comment]
ok, basically you have all my reports covered as far as i see (would be nice to see whenthis will be implemented), so this can be closed. ty, ill close the issue
