### ISSUE TITLE
Cast to external device

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3532]
I started to implement the ability to cast to Chromecast or to a Google nest device. 
![image](https://user-images.githubusercontent.com/3314607/151709989-a3e2dadd-5e1d-4dc0-b5f8-d3118b306ac0.png)

But till now, I'm failed with ownCloud files/videos. (both local downloaded or direct from backend are failing, only hard coded like _https://storage.googleapis.com/wvmedia/clear/h264/tears/tears.mpd_ works). If someone is interested too or want to jump into this, **I can push my complete branch**. 
For this I already pushed some pre-commits to keep changes for cast as small as possible. It try to avoid huge pull requests 
* https://github.com/owncloud/android/pull/3531
* https://github.com/owncloud/android/pull/3530
* https://github.com/owncloud/android/pull/3512
* https://github.com/owncloud/android/pull/3515
* https://github.com/owncloud/android/pull/3529
* https://github.com/owncloud/android/pull/3533

**Comment by tripplehay** [comment]
Okay that's a great idea 'll try to hop on this with you and will try to avoid a big pull request

**Comment by hannesa2** [comment]
Because it's based on other commits, I'll first finish it on my fork https://github.com/hannesa2/owncloud-android/pull/201 and when it's done, I extract cast commits to a pull request here. @tripplehay

**Comment by tripplehay** [comment]
Alright that'll be great. @hannesa2

**Comment by hannesa2** [comment]
I run into several unsupported video formats and the fastest workaround is to download file and share it with VLC https://github.com/google/ExoPlayer/issues/9941#issuecomment-1031264141 
So I keep now less attention to this topic, but everyone is warmly welcome to make it perfect https://github.com/hannesa2/owncloud-android/pull/201

**Comment by theScrabi** [comment]
@hannesa2 we can not merge your changes at this point.
The Problem is that you introduce the `GSM` library into the app: https://github.com/hannesa2/owncloud-android/pull/201/files#diff-b2999a545c396e7aa39a800b63bfabf795f4921a4b6a5e1e712ed79ab236e324R32

This is a closed source library. Introducing such a library would brake the support for F-Droid, as the F-Droid repository does not allow any closed source libraries or code, especially not the GSM lib.
Over at NewPipe we have encountered similar issues, which we where not able to fix yet. See the [PipeCast Project](https://github.com/teamNewPipe/pipecast). Here we so far only managed to support UPnP.

In order to be able to use GSM libraries we'd have to create separate versions for F-Droid and the Google Play store. So far we do not have a plan for doing this.
