### ISSUE TITLE
Migrate to Media3

### ISSUE THREAD

**Issue by parneet-guraya** [owncloud/android#4157]
Media3 is the new home for Exoplayer and it is recommended to migrate to it. Exoplayer is now the part of this library.

>Apps that are currently using the standalone com.google.android.exoplayer2 library and androidx.media should migrate to androidx.media3. Use the [migration script](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide#exoplayer) to migrate gradle build files, Java and Kotlin source files, and XML layout files from ExoPlayer 2.19.1 to AndroidX Media3 1.1.1

Let me know about this and assign this to me, I will do it.

**Comment by JuancaG05** [comment]
Hi @parneet-guraya! Nice to see you again over here! 😃
Thanks for opening the issue. Seems a nice improvement 👍. I encourage you to make it and send a PR so that we can review it and hopefully merge it 🚀.
There's no need to assign the issue, just develop it and whenever it's ready we'll link the PR with the issue 👌.

**Comment by parneet-guraya** [comment]
Nice to see you here too 😃, Working on it 🚀.

**Comment by parneet-guraya** [comment]
Hi @JuancaG05, hope you're doing fine.

So, I was working on the migration and it was successful. But I would like you to read this first https://github.com/nextcloud/android/issues/11977#issue-1901894790.(Just ignore the specific file names mentioned there). I had pushed a PR regarding migration in the nextcloud's android client and had some question which are same for migration in owncloud's client. You can also see the [migration](https://github.com/nextcloud/android/pull/11936#issue-1878875220) I did there If you want to see how would Immersive mode look like if you want.

- The reason to use immersive mode  was pretty much the same but  instead of launching Dialog here we are using another activity to go full screen.

So, do let me know what you think about having a single activity for media playback?
Thanks!

**Comment by JuancaG05** [comment]
Hi @parneet-guraya! Let's see if I can reply to your questions.

About the first question: I'm not very familiarised with the Media UI concepts, what do you mean with cut-out mode? And what effect would it have in other non-media previews? Could you post some screenshots to see it more visually?

About the second question: if you were trying and couldn't get what Google Drive has, it's ok, `NEVER` mode looks good enough (more than `SHORT_EDGES`). Maybe Google Drive is using another kind of toolbar, or more likely they are using Jetpack Compose, which allows much more flexibility than XML 😄. I hope we can introduce it veeeery soon in ownCloud.

I saw the before and after videos of your PR and they look great! 💯 When you have it for ownCloud, it would be so cool if you posted some videos as well!

Thanks a lot for your contributions, we're very happy with them 😺😍

**Comment by parneet-guraya** [comment]
Thanks @JuancaG05, appreciate your feedback :smile:  and yes surely would put a demo of before and after.

So, In order to have Immersive mode smoothly In/out. It needs [(best practices for handling display cutout)](https://developer.android.com/develop/ui/views/layout/display-cutout#best_practices_for_display_cutout_support) to have either `SHORT_EDGES` or `NEVER`. Since, it takes effect in the `Activity` only not in `Fragment` since that is just a part of activity. I was asking to migrate the media play back code which is right now in `Fragment` to `Activity`, that way we can specify the [cutout mode](https://developer.android.com/develop/ui/views/layout/display-cutout#choose_how_your_app_handles_cutout_areas) (basically it describes how  UI should be rendered in the notch area on devices with notches) and since we are going to have separate `Activity`, It would not effect other non-media previews and only what we choose to render in the Media playback Activity. So, let me know and I will push a PR about migration to activity first then I can push the `Media3` migration and I'm thinking to push these two changes as two separate PR's (`Activity Migration` and `Media3 migration`) so to avoid having too much changes in a single PR, is that right?

Yes, we can go with `NEVER` mode. It looks good than the `SHORT_EDGES` (unless used the approach what G-Drive using). However in future I still try to achieve that If I could :+1: .

**Comment by JuancaG05** [comment]
Hi @parneet-guraya! I was taking a look and it seems that some of the media preview fragments are in Java, and others are already in Kotlin. I think it's a great opportunity to kotlinize those classes, but on the other hand I see this could be a little bit complex. If I understood well, your idea is refactoring and moving the `PreviewVideoFragment.java` and `PreviewImageFragment.kt` to a same activity (let's say `PreviewMediaActivity.kt`?), right?

I see these two classes have much different content between them, and maybe trying to unify them is tricky since we'll have a very big new activity, which is not the aim, the architecture we follow says it's good to separate concerns and keep things simple. The solution I can think of is creating a new activity, parallel to `FileDisplayActivity.kt`, which is our main activity now, but just used for the media preview cases (instead of creating new fragments, you would switch to that activity). You can set that activity to the cutout mode you prefer, but it will continue hosting fragments. In that way, we can keep using the current media preview fragments and avoid a difficult refactor.

What do you think about this proposal? 🤔 Maybe I'm missing something in the solution you suggest and that's why I see it too complex, so just let me know 😀.

BTW, after taking a look at some other apps, I see `SHORT_EDGES` a good option too (see YouTube for example, with videos in full screen), the problem would be the toolbar, which keeps a weird appearance. But now it's up to you, you can choose whatever you want and we'll give our input 🤩.

Thanks a lot again for your involvement with the app! 🥇

**Comment by parneet-guraya** [comment]
> About the activity structure I propose, just take a look at the `start...Preview` methods in `FileDisplayActivity.kt`. `startImagePreview` starts the new activity dedicated to images previews, while `startAudioPreview` and `startVideoPreview` are creating the new corresponding fragment instances. The idea is that these two last methods work like the first one but instantiating the new `PreviewMediaActivity.kt` and thus, being able to set its cutout mode. 

So, making sure If we're on the same page. You are talking about having a `PreviewMediaActivity` (audio and video) and which can be launched from either of the `start...preview` method?

> BTW, I guess the audio preview is not a problem for this since we won't need an immersive mode there (nothing important to show on screen), is that right?

And If I consider the above, yes, audio does not need to have a cutout mode (unless required to show the audio playback UI in a certain way). Primarly Video playback needs it for the going fullscreen. So, does that mean we should have a single Activity just for video (for ex: `PreviewVideoActivity`) and leave the audio preview `PreviewAudioFragment` as it is?

>You could also maybe get more ideas from the changes that were proposed in this issue: #3144.
Yes, this is talking about having a single `PreviewVideoFragment` instead of having two files like we have currently, PreviewVideoFragment (for simple view)  and PreviewVideoActivity (For Full screen). But, as discussed for having a cutout mode set, we need `Activity`.

Also, this is talking more about refactoring the code and having the duplicated logic in one file. Which indeed would happen if we go with `Activity` and implement immersive mode to have video functionality in a single place and yes kotlinization also.

**Comment by JuancaG05** [comment]
> And If I consider the above, yes, audio does not need to have a cutout mode (unless required to show the audio playback UI in a certain way). Primarly Video playback needs it for the going fullscreen. So, does that mean we should have a single Activity just for video (for ex: `PreviewVideoActivity`) and leave the audio preview `PreviewAudioFragment` as it is?

Yes, I would go with this approach to make it simpler. Let's create a `PreviewVideoActivity.kt` (refactor the one we already have) and launch it from the `startVideoPreview` method, and for the moment we'll let the audio preview stay as it is 👍.

**Comment by parneet-guraya** [comment]
Okay, great. Should I make that migration to activity in a separate PR first or keep it in the media migration?

**Comment by JuancaG05** [comment]
Since it is finally just one activity, I would make everything in a same PR, not too complex to separate it in 2 different PR, I think I'll be able to review it properly 👍

**Comment by JuancaG05** [comment]
Some stuff affected in this PR that could be good to QA, in addition to the core feature (video play):
- Filter for menu options in main file list is OK while previewing a video
- If video file is removed while previewing it, go back to the main file list (app doesn't crash or behaves wrongly)
- Menu options in the video preview are working properly

@jesmrec
