### ISSUE TITLE
I can't log in to the cloud on Mail.ru

### ISSUE THREAD

**Issue by guland2000** [owncloud/android#4168]
Official documents telling go to:
https://webdav.cloud.mail.ru but it's doesn't, playing without webdav , cloud didn't works🥺
[owncloud.2023-09-22-1.log](https://github.com/owncloud/android/files/12695990/owncloud.2023-09-22-1.log)

At the same time with Davx5 app (with settings  above) everything is OK, can see and use file system in mail.ru cloud.

**Comment by JuancaG05** [comment]
Hi @guland2000! In the case of the ownCloud app, we just support servers with an ownCloud instance installed. It's true that ownCloud uses WebDAV, but unfortunately we're not supporting every server which uses WebDAV, so that's why mail.ru cloud is not working from our app.
Closing this issue. Feel free to add any other comment or open a new issue if you find problems in the app! 🍻
