### ISSUE TITLE
Auto upload of pictures only uploads new photos

### ISSUE THREAD

**Issue by ezcGman** [owncloud/android#4171]
### Actual behaviour
I've enabled the "Auto Upload pictures" feature and it's not uploading any pictures to my server. New pics I took since I enabled the feature are uploaded, but none of the hundreds of already existing pictures are uploaded.

### Expected behaviour
I expect the app to also upload all existing pictures in the camera folder.
 
### Steps to reproduce
1. Enable "Auto upload pictures"
2. Pick the targer folder
3. Pick the local folder (`/tree/primary:DCIM/Camera`. Yes, it's the right folder ;))
4. Oberserve that even after hours no pics are uploaded
5. Take a new pic and abserve it's uploaded

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
I did not wanna test uploading my personal photos / sync to the public test server, sorry ;)

### Environment data
Android version: 13 TKQ1.220807.001

Device model: Xiaomi 11 Pro

Stock or customized system: Stock (MIUI 14.0.14.0)

ownCloud app version: 4.1.0

ownCloud server version: 10.12.2.1

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
This is the expected behaviour. In our rodmap is expanding the behaviour to older pictures in the chosen account, but not implemented yet.

**Comment by ezcGman** [comment]
Interesting...

So I opened an issue, because for my girlfriends phone it was working. However, for her the setting was turned on already since quite a while, but the folder on the server only had around 10 pictures. I re-selected the source folder and it upload 1000+ pictures. So I assumed it does indeed upload all images in the folder...

Weird...

**Comment by JuancaG05** [comment]
Hi @ezcGman! Thanks for opening a new issue!

Well, as @jesmrec says, this is the expected behaviour. It could be that the modification date of the files in the source folder you selected was somehow more recent than the las sync timestamp, which is set at the moment you enable the auto-uploads setting. Maybe, if the setting was already turned on, what I can think of is that it got stuck at some point and the last sync timestamp wasn't updated for some reason, or that the modification date of the files in that source folder was changed (due to moving the files or whatever), or a combination of both. The code that chooses the pictures to upload is the next:

```
val filteredList: List<DocumentFile> = arrayOfLocalFiles
            .sortedBy { it.lastModified() }
            .filter { it.lastModified() >= lastSyncTimestamp }
            .filter { it.lastModified() < currentTimestamp }
            .filter { MimetypeIconUtil.getBestMimeTypeByFilename(it.name).startsWith(syncType.prefixForType) }
```

In any case, we'll take into account your suggestion to upload every picture in the folder you choose and not only the new ones. For the moment, the solution I can suggest is, from the Gallery app (for example) choose all those files you want to upload, and click "Share with...", then share all of them with ownCloud in the same folder you want to upload the new ones.

We'll keep you updated with this, but anything else you want to comment just post it here! 🍻

**Comment by ezcGman** [comment]
Yeah that makes total sense (that it hung and didn't update the last sync timestamp... I'll do the initial manual upload for now, thanks!

And thanks guys for the work on this project!! <3

Greetings,

Andy!
