### ISSUE TITLE
[BUG] Conflict in copy: File without extension 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4222]
Check the following steps out:
 
### Steps to reproduce

1. In a folder (non-root), create or upload a file that lacks of extension in the filename
2. Select the file to copy
3. Select as destination the same folder (conflict)
4. Fix the conflict with `keep both`

Current: error `it's not posible to copy a folder into a descendant`
Expected: file copied with `(1)` after the name

https://github.com/owncloud/android/assets/14894746/68f63d2a-324c-426e-89eb-c085c029ffe4

Pixel 2, Android 11
Reproducible in 4.1.1
Reproducible in oC10 & oCIS

**Comment by Aitorbp** [comment]
The `startsWith` function will not work with files that lack an extension for the following reason:
If we have a file called `test` and we want to copy this same file to the same folder. The file will behave as follows:

`“test (1)”.startsWith(“test”)`

This function will return `true` and therefore enter the `INVALID_COPY_INTO_DESCENDANT` exception, since the prefix is the same.

The behavior with extension would be the following:

`“test (1).log”.startsWith(“test.log”)`

The` test.log` prefix is not contained in the target therefore it will return `false`. With a folder it has the same behavior, only instead of having an extension it has a slash `/` at the end.

I remove the startsWith condition from the `CopyRemoteFileOperation` class and keep this logic in the `CopyFileUseCase`, where these exceptions are being handled.
