### ISSUE TITLE
Android connection to CNAME fails

### ISSUE THREAD

**Issue by Floaty-** [owncloud/android#455]
First of all I must say what a GREAT idea with ownCloud. I love it.
Used a lot on my home computers.

But... ;)
I noticed something when setting up ownCloud on my android device.
In DNS theres a CNAME owncloud.mydomain.tld pointing to realhostname.mydomain.tld
When I try to connect to the CNAME owncloud.mydomain.tld it will not connect.
So I rooted my android device and added IP and owncloud.mydomain.tld to the hosts file.
Now my android device will connect.

Does the android client send realhostname.mydomain.tld instead of the name I type in as connection name?
Apache needs owncloud.mydomain.tld to serve the correct page. Not the name it gets translated from DNS.

Windows client does not have that problem. Am I doing something wrong or is this a bug?

{"installed":"true","version":"6.0.2.2","versionstring":"6.0.2","edition":""}
Android client is version 1.5.4

**Comment by mooncong** [comment]
You can lookup cname type of dns manually.
```
private String getCnameForHost(final String host) throws TextParseException {
		final Lookup lookup = new Lookup(host, Type.CNAME);
		lookup.run();
		if (lookup.getAnswers().length == 0) {
			return null;
		}

		String target = ((CNAMERecord) lookup.getAnswers()[0]).getTarget()
				.toString();

		return target.substring(0, target.length() - 1);
	}
```

**Comment by jeweloper** [comment]
Any news to this bug?

I've got a internet access with a dynamic IP. This is the reason I have to use a DDNS-Service.
The only possibility to provide my self hosted owncloud service under my private domain is to use the DDNS-domain as CNAME.

So, the workaround mentioned by Floaty doesn't work, because I have not a static IP.

Are there any plans to fix this bug or any other known workarounds?

**Comment by davivel** [comment]
I'm sorry, but as far as I know, there is not a lot of interest in this. 

Summoning @owncloud/android-developers for more opinions / hands.

**Comment by jeweloper** [comment]
@davivel thanks for your feedback.
After some "investigation" I recognized, that my problem is caused by a bug of my router.
If it is a CNAME-record-domain the IPv6 DNS lookup fails by the router.
The oc-desktop-client could handle it and fallback to IPv4 connection.
In android the connection is completely broken, when there is a problem with IPv6.
So I jump to conclusions.
My workaround is to disable IPv6 in android. I hope with a new router the problems are gone.

**Comment by LukeOwncloud** [comment]
IPv6... yes, that issue is known: https://github.com/owncloud/android/issues/616

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
