### ISSUE TITLE
Unable to connect with SSL

### ISSUE THREAD

**Issue by ConiKost** [owncloud/android#470]
I've installed the ownCloud Client on my Android phone (Nexus4), Version 1.5.5. Owncloud itself is running on Version 6.0.2.

My Windows and Linux client can connect without any problems. But I am unable to connect with my android phone.

When typing my URL: https://cloud.domain.tld/ it just says "An unknown error occurred". That's it. What can I do?

https://cloud.domain.tld/status.php can be reached without any problems from my phone in the browser. I can't find any connection attempt on my webserver from my android phone..

**Comment by privong** [comment]
For what it's worth, I am also experiencing issues synchronizing contacts and my calendar with owncloud using davDroid. This leads me to suspect that the fault is either the the nginx configuration or with an underlying android library. Unfortunately, I have not figured out how to differentiate between the two. Given my nginx configuration is unchanged (since before the problem arose), I supsect android, but I have no proof.

**Comment by privong** [comment]
Correction, it seems this was an SNI issue, for me. I disabled all other SSL servers in my nginx configuration, restarted the server, and now I can connect with both the android owncloud client and with davdroid. So, perhaps this issue (at least for me) was related to #300 and there not (yet) being support for SNI?

**Comment by davivel** [comment]
@privong, the support of SNI in the app is limited, conditioned by the smartphone. What model is yours? What Android version does it hold?

**Comment by davivel** [comment]
@faulkner93 , @InfoSec812 , @Ruelam - the issue with the trailing slash is well-known; it should be fixed with the current released version (1.6.2), though we are still discussing if that's true in other issue. Sorry for the inconvenience.

**Comment by davivel** [comment]
@R0000, that's quite strange. There must be some rule in your server configuration that is enforcing lowercase in some way. 

The app is not transforming the case-state of the URL. Even if it did it, your use case does not fit in a possible bug, since there is no way that the app knows wether precisely the 'C' character should be lowercase or uppercase.

Please, take a look to your web server configuration.

**Comment by davivel** [comment]
@poschd , did you check the Nginx configuration? I think it suffered some update in the change from OC 6 to OC 7. Please, take a look to: http://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html

Other possibilities: do you use SNI in your server? What model is your device? What Android version?

**Comment by davivel** [comment]
@brantg , do you use SNI in your server? What model is your device? What Android version?

**Comment by davivel** [comment]
@ConiKost, is this still a problem for you?

In that case, could you create a new user and try to log-in? Please, use only alphanumerical character both in user name and password? 

Do you use non-alphanumerical characters in your real user name and password?

Could you also have a look to the recommended Nginx configuration in http://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html  ? I think it was updated with OC 7.

**Comment by brantg** [comment]
@davivel, No, my entire installation is sealed behind a firewall so I never bothered to set up HTTPS.  All my connections to the server are plain HTTP.

My phone is an LG-E980 running Android 4.4.2.  I did check the behavior of the Android software since the server update to 8.0 and it is unchanged.  In a few weeks I intend to deploy a DNS server so I can use a name rather than an IP for the URL; if that changes the behavior of the app I will report back.

**Comment by davivel** [comment]
Thanks, @brantg . I am looking forward about your report. But please, I need to ask you to do it in a new issue, since this one is specific for HTTPS access. You can include a link to here in the new one to keep in track.

**Comment by privong** [comment]
@davivel I am using Android 4.4.4 on a Moto G LTE (1st gen).

**Comment by guettli** [comment]
For all people read this thread from bottom up.: Please check your https://example.com/status.php before anything else. In my case status.php told me exactly what's wrong.

**Comment by brantg** [comment]
@guettli, This was enormously helpful, thank you!  Apparently I just needed to add the server IP as a trusted domain and status.php made this totally clear.  Be advised that for me the path was http://1.2.3.4/owncloud/status.php.

@davivel, Adding the trusted domain completely resolved my Android issue and I suspect my plan to set up DNS would have also done so for the same reason.

**Comment by davivel** [comment]
Got it, trusted domain.

Please, @ConiKost , @poschd , @privong , could you check if this helps you? : https://forum.owncloud.org/viewtopic.php?f=17&t=20220

**Comment by privong** [comment]
@davivel I just checked, and the trusted doman settings have been set since I installed owncloud, so it doesn't correlate with the android client issues I was experiencing. So I don't think that resolves the issue, for me.

**Comment by rthresh** [comment]
I am thinking the problem is common to both Android and iPad.  I am guessing by the behaviour of the self signed cert (I'm running 7.04 under ClearOS) THAT the cert is not recognized on the devices, I had trouble getting Windoz 8.1 to sign in, until I opened up the browser and set it to NOT use a proxy setting.  From the browsers even on iPad, I have to tell the browser to except the "unknow" or untrusted cert for my owncloud to connect with https.   Once I do that it works, but there is no dialog to enable that process with the moble clients..... just guessing here :-)

**Comment by rthresh** [comment]
oh btw, I have nated my https connection through my sonic wall to the lan server clearos.

**Comment by ConiKost** [comment]
@davivel Sorry, but I won't be able to test this anymore, as I don't have any android phone anymore.

**Comment by rthresh** [comment]
Yea..OK we have same issue from ipadBest regards Robert     Conrad Kostecki --- Re: [android] Unable to connect with SSL (#470) --- From:"Conrad Kostecki" <notifications@github.com>To"owncloud/android" <android@noreply.github.com>Cc"rthresh" <rthresh@tes-it.com>Date:Mon, Mar 30, 2015 12:44 PMSubjectRe: [android] Unable to connect with SSL (#470)@davivel Sorry, but I won't be able to test this anymore, as I don't have any android phone anymore.
—Reply to this email directly or view it on GitHub.              




This message is intended for the sole use of the individual and entity to which it is addressed, and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended addressee, nor authorized to receive for the intended addressee, you are hereby notified that you may not use, copy, disclose or distribute to anyone the message or any information contained in the message. If you have received this message in error, please immediately advise the sender by reply email and delete the message.

**Comment by childnode** [comment]
same here with owncloud for android 1.7.1, but:
according to https://code.google.com/p/android/issues/detail?id=61085#c8
TLS 1.1 and 1.2 are DISABLED by default up to Lolipop!

according to https://github.com/owncloud/android/issues/362#issuecomment-71622802
> Actually, TLSv1.2 cipher suites (e.g. those with either SHA256 or SHA384) are supported from API level 20 onwards (Android 4.4) so do not expect to get a TLSv1.2 connection on an earlier OS. Just confirmed with Android 4.2.

while ssllabs says it is "supported": 
https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2

I get SSL3 handshake errors (!):

```
D/SimpleFactoryManager(25608): getClientFor(OwnCloudAccount ... : 
D/OwnCloudClient #3(25608): Creating OwnCloudClient
V/SimpleFactoryManager(25608):     new client {@owncloud.childno.de, 1108168888}
D/OwnCloudClient #3(25608): REQUEST GET /status.php
D/AdvancedSslSocketFactory(25608): Creating SSL Socket with remote owncloud.childno.de:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@4208ef48
D/AdvancedSslSocketFactory(25608):  ... with connection timeout 5000 and socket timeout 5000
D/OwnCloudClient #3(25608): Exception occurred
D/OwnCloudClient #3(25608): javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x41bcef38: Failure in SSL library, usually a protocol error
D/OwnCloudClient #3(25608): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5eac5cf8:0x00000000)
D/OwnCloudClient #3(25608): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
D/OwnCloudClient #3(25608): 	at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.verifyPeerIdentity(AdvancedSslSocketFactory.java:248)
D/OwnCloudClient #3(25608): 	at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:185)
D/OwnCloudClient #3(25608): 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
```

```
D/OwnCloudClient #3(25608): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x41bcef38: Failure in SSL library, usually a protocol error
D/OwnCloudClient #3(25608): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5eac5cf8:0x00000000)
D/OwnCloudClient #3(25608): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
D/OwnCloudClient #3(25608): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
D/OwnCloudClient #3(25608): 	... 20 more
E/GetRemoteStatusOperation(25608): Connection check at https://owncloud.childno.de: SSL exception
E/GetRemoteStatusOperation(25608): javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x41bcef38: Failure in SSL library, usually a protocol error
E/GetRemoteStatusOperation(25608): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5eac5cf8:0x00000000)
E/GetRemoteStatusOperation(25608): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
```

for this server config:

```
SSLCipherSuite \
EECDH+ECDSA:\
EECDH+AESGCM:\
EECDH+aRSA+SHA384:\
EECDH+aRSA+SHA256:\
!EDH:!SSLv2:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CBC

SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
```

which should work fine and is working fine for anything, expect the android client. Also Desktop Owncloud client works since 1.7.1 https://github.com/owncloud/client/issues/1556

https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.childno.de

```
# openssl s_client -connect owncloud.childno.de:443
CONNECTED(00000003)
...
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
...
```

something is really strange ...

P.S: I'm not anymore on "stock" Android 4.3 from Sony but on CM 11 but even this should not be a problem at all: https://github.com/CyanogenMod/android_external_openssl/tree/cm-11.0

**Comment by thejrose1984** [comment]
Not sure if the issue I'm experiencing is the same as above, but I notice SSL Cert errors, but only from the Android platform. Hitting my instance of OC from the web from iOS and WIndows seems OK, but Android seems to give this issue.

**Comment by quimpg** [comment]
I have the same problem, the app doesn't connect generating unknown error

APP version: 1.8 (Android)
https://cloud.pagans.cat/status.php (looks everything ok)

What I'm missing?

Thanks!

**Comment by boscowitch** [comment]
ALLOW HIGHER ENCRYPTIO FFS!!!!
cant believe i paid for this... and it fails at basics that are defaults post snowden ... how could i trust the app to use less secure settings...

**Comment by tobiasKaminsky** [comment]
@boscowitch I have enabled FFS and I can connect with the app.
Can you explain how to reproduce the problem?
(I also use letsencrypt, with apache2)

**Comment by boscowitch** [comment]
Well I use nginx as an reverse proxy that points to my apache  so nginx handles all the ssl encyption and I set my encryption modes to only secure alorithms wiht high encryption like for example here https://cipherli.st/
to disallow weak encryption:
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
before I allowed this:
ssl_ciphers 'EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA';

but that also fails .....

and i cant imagine the reverse proxying beeing the problem ... since it works fine with the linux client and in the browser but here my settings:

proxy_set_header X-Real-IP  $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header Host $host;
proxy_pass http://127.0.0.1:8888;

127.0.0.1:8888 is where the apache vhost is running pointing to the owncloud dir...

**Comment by childnode** [comment]
@boscowitch I bet same problem [as for me above](https://github.com/owncloud/android/issues/470#issuecomment-105204737): have you tried to enable `EECDH+aRSA+SHA`? yes, it's just a bad workaround ;/

**Comment by boscowitch** [comment]
unfortunately every other free client seems to have the same limitations... i find this very strange why the heck should an app have less SSL chipers available than the chrome browser on android...

**Comment by davivel** [comment]
@ConiKost, thanks anyway for your feedback.

@childnode , your input here is **awesome**. Thank you so much for your effort.

Right now the app (the OC library for Android) is explicitly enabling support for TLSv1.2 protocol, but it's not explicitly enabling any concrete cipher. We could try to explicitly request all the available ciphers, just in case any of them is not enabled by default. All this keeping the current approach, that is, using the SSL stuff shipped with the Android system.

Another approach could be shipping our own SSL implementation and cipher suites with the app... but I don't think this is feasible in the short term.

**Comment by boscowitch** [comment]
so only chrome or apps with it's own ssl implementation can connect ... I must say I excepted more from Android also disabling TLS 1.2 because of 2% incompatible websites in the whole web.... seems kinda drastic especially since websites have to update more often anyway out of security reasons... at least they should allow apps to enable it and not totally dissable it.

And I'm on Android 5 and as it seems it's still not working by default as the posts claims.... what the heck is this really NSA influence

**Comment by theced7** [comment]
Hi,

I'm still getting unknown errors using this config:
```
 ssl_protocols               SSLv2 SSLv3 TLSv1 TLSv1.1;

  ssl_ciphers                 EECDH+aRSA+SHA:EECDH+ECDSA:EECDH+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256;
```

I'm using Owncloud 8.2.7 and Nginx and the App version 2.1.2. CM 13/Android 6.0.1.

On another note: If you don't mind me asking, why is this issue unresolved for so long? Not being able to (safely) use a cloud on mobile is pretty much killing its core functionality.

**Comment by zsusag** [comment]
Is there any update to this issue? I'm trying to connect via https using the android app to my newly created owncloud server hosted on lighttpd under FreeBSD and I believe I'm having issues. I REALLY don't want to connect via http. Or, if anybody has any alternatives, I would be very interested in hearing about them.

**Comment by boscowitch** [comment]
hmm this is a serious issue for a lot of users who care about post snowden security... i guess i will be looking into nextcloud soon to check if they are willing to prioritize  this issuw...

**Comment by DrissiReda** [comment]
Hello I have a similar issue on my iOS app, everything worked perfectly beffore SSL, once added I started having on and off issues, the app randomly freezes, and rarely works on my log I found this line : 
`host-001.home:443 37.168.224.23 - - [01/Mar/2018:15:30:02 +0100] "PROPFIND /owncloud/remote.php/webdav/InstantUpload/ HTTP/1.1" 403 232 "-"     "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.2"`

But when it works I find this : 
host-001.home:443 37.168.224.23 - - [01/Mar/2018:15:30:02 +0100] "GET /owncloud/index.php/apps/files/api/v1/thumbnail/64/64/InstantUpload/P    hoto-2017-09-30-19-14-07_2768.JPG HTTP/1.1" 403 232 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.2"

I hope this could help

**Comment by davigonz** [comment]
> Hello I have a similar issue on my iOS app, everything worked perfectly beffore SSL, once added I started having on and off issues, the app randomly freezes, and rarely works on my log I found this line 

Hi @DrissiReda , thank you for the logs, will be useful. Can you please include this information in a [iOS repository](https://github.com/owncloud/ios/issues) issue as well? Thanks

**Comment by DrissiReda** [comment]
Already did when  I first encountered this issue.

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
