### ISSUE TITLE
InstantUpload notifications

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/android#481]
1. The success notification is of no help at all. I expect the upload to be sucessful - no need to tell me.

2. The failure message in contrary doesn't help either. I have no idea if the app will retry again (if so can I see the upload queue) or if I have to take manual action to trigger the instant upload again.

@rperezb @MTRichards @jancborchardt THX

**Comment by Bugsbane** [comment]
Rather than just retrying after an hour, I'd suggest tryng to figure out the problem and monitor that. For example, if it couldn't retry because the server wasn't available, then check again, whenever the phone's connection status changes. In cases where we don't have access to any data about where the problem might change then I'd suggest leaving a fail notification that lets users manually retry, and then also trying regularly, taking the notification away if successful.

**Comment by tobiasKaminsky** [comment]
1. is still valid: @jancborchardt can we just remove this? Or is the current behaviour (showing a success notification for ~2s) ok?
2. is solved by the new upload pane.

**Comment by jancborchardt** [comment]
Does tapping the error notification retry? Or link to the new upload list – that would be ideal.

Succes notification for 2 secs is nice like now, yes. :)

**Comment by tobiasKaminsky** [comment]
Clicking on error notification opens the upload pane.
So closing it.
