### ISSUE TITLE
The server took too long to respond

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/android#516]
After entering username/password i get 'the server took too long to respond'.
Although i'm able to use the same account with the sync client on Windows and Linux. Using another account just works fine.
Any idea what causes this?
Using the latest Android app 1.5.5

EDIT: tried on 3 different Android devices running 4.4.x

@davivel

**Comment by flexibeast** [comment]
i've just set up ownCloud 8.0 (using the package from the opensuse.org repo) on Apache 2.2 / Debian Wheezy(+updates) x86_64, and am facing a similar issue with the Android client. i can access my ownCloud instance via HTTPS in my phone's Web browser using mobile data, but the Android client says "The server took too long to respond", regardless of whether i specify the URL in the form "[fqdn]" or "[fqdn]/owncloud".

**Comment by flexibeast** [comment]
Okay, i found the cause of the problem: i hadn't modifed the ownCloud `config.php` file to specify [fqdn] as a trusted domain. Doing so fixed the problem. :-)

**Comment by tobiasKaminsky** [comment]
@flexibeast great, good to hear.
@davivel we really need to get the error message from the server passed to the app to help the user with such things...

**Comment by tkteun** [comment]
I have the issue lately with my owncloud installation. This suddenly started happening when I was in the configuration process. I personally suspect it had something to do with me playing around with server side encryption (which encrypts the entire storage by default, not by setting as advertised).

I'm running on Apache with a self-signed certificate, whenever I point the Android app to my installation instance, it hangs around 10 seconds before coming up with the aforementioned error message.

On my server I get the following messages:
access.log:
{client_IP} - - [11/Mar/2015:16:26:17 +0100] "GET /owncloud/status.php HTTP/1.1" 200 2043 "-" "Android-ownCloud"
error.log:
[Wed Mar 11 16:13:28 2015] [error] [client {client_IP}] File does not exist: /var/www/favicon.ico, referer: https://{fqdn}/owncloud/status.php

The result of calling status.php on my laptop is:
{"installed":true,"maintenance":false,"version":"8.0.2.0","versionstring":"8.0.2","edition":""}

The {fqdn} was already added to config.php so that shouldn't matter. The error message already appears without entering a user name. At first I thought there was an issue with the self-signed certificate, but I've imported it into my phone with CAdroid and there's a successfull 200 message on status.php so that shouldn't matter. I hope I find a chance soon to do some wiresharking on this with an intermediate computer.

**Comment by tobiasKaminsky** [comment]
@tkteun maybe you can create a new server instance with a clean and simple installation to exclude encryption as a source for this problem?

**Comment by peteruithoven** [comment]
After updating to the latest version of owncloud and reinstalling the mobile client on Android I'm also getting this issue, how can I debug this?
Desktop client works fine, iCal calender seems to be synced just fine using caldav. 
status.php gives:
``` 
{"installed":true,"maintenance":false,"version":"8.0.2.0","versionstring":"8.0.2","edition":""}
```

**Comment by GenomeAnalysts** [comment]
I just installed ownCloud Server version 8.0.2 for the first time and although it responds well to web access, the Android mobile app constantly gives me this error. I do have the fqdn correctly added to the trusted domains in config.php, so that's not the cause of the problem in my case.

**Comment by tkteun** [comment]
My phone was installed with all kind of factory bloatware, I haven't experienced this problem since I've installed Cyanogenmod 12. Similar errors in the use of DAV/CAdroid have disappeared.

I think something was interfering with (homemade) SSL / certificates in the factory (hardened) firmware, but I'm unable to reproduce since I've reinstalled my phone.

**Comment by davivel** [comment]
@peteruithoven , @GenomeAnalysts , what are your device models and Android versions?

@tkteun , what is your device model? What Android version did it have before your changed to Cyanogenmod?

**Comment by tkteun** [comment]
I have a Samsung Galaxy S4 Mini (GT-I9195) which was supplied through Vodafone in The Netherlands. I guess it was running 4.4.4 or similar.

This meant in my case that the phone had Samsung and Vodafone applications pre-installed and the regular rooting tools weren't functioning. I've experienced a lot of problems updating my bootloader using heimdall and finally got it to work with updated versions of both clockworkmod and heimdall. Now I'm running Cyanogenmod 12.1 on Android 5.1.1.

**Comment by PeteHardy** [comment]
My  Galaxy S3 can only add a new server & account when WiFi is connected. Otherwise I get the "The server took too long to respond" message.

**Comment by wuffleton** [comment]
+1 to this bug
I've been having this issue over mobile data and certain (but not all) wifi networks around my workplace. It's been happening since one of the 8.x owncloud server upgrades, but I'm not entirely sure which one. Local wifi (on same network as server) works as expected, faster wireless networks where I work also seem to work. If it makes any difference I'm running a dual-stack IPv4/IPv6 server, since I saw another bug referencing improper IPv6 handling. However, this still seems to occur even if I set my mobile APN to IPv4 only, or connect from an IPv4-only hotspot. 

The client isn't even talking to the server: I get absolutely nothing in the remote server logs. Just how long is the remote timeout currently set to? Since mobile networks tend to have higher latency, wouldn't it make more sense to bump this value up? 

Setup is as follows: 
Owncloud Server: 8.1.3-1 
Owncloud App: 1.8.0 (F-Droid)
Device Model: HTC One M8
Device OS: CyanogenMod 12.1 (Android 5.1.1)
Webserver: nginx + uwsgi
Server OS: Arch Linux 

I can provide my server configs on request if you feel that it will help isolate the issue, but I feel like this problem lies in the app's intolerance for higher latency networks. 

Can also get my Android catlog if that could help isolate things, but I saw nothing of troubleshooting-worthy value in there when I was trying to solve this on my own.

**Comment by wuffleton** [comment]
Actually realized my APN was on dual stack still, and the WiFi AP I tried before worked today, so I think this is possibly related to #616. Switching my APN to IPv4 only allowed the app to work as expected (might be a viable workaround for some people if their carrier supports it). 

Most cell carriers operate on IPv6 with tunneled v4 or have dual stack, so I wouldn't be surprised if something is choking up when operating with v6. 

Oddly enough I have no issues with v6/dual stack on my home WiFi, but this might be a good place to start looking for the cause of this issue.

**Comment by Kycko** [comment]
Hey guys, today I had the same issue after changing my passwords for both admin and user accounts. I've reenabled my account in desktop, then in my phone, and then tried to do that on MiPad, but received this error. I've found [a solution] (https://help.nextcloud.com/t/30-sec-to-wait-before-login-since-update-10-0/2599). 
Note that if your device is connected to the same WiFi, you must delete EXTERNAL IP. 
GL&HF ^_^

**Comment by austin1029** [comment]
I have same problem except it only works when I connect my android to a VPN.

**Comment by kesavanm** [comment]
Switching from auto config to DHCP Server on Pv6 settings inside Gateway router can let Android ownCloud sync with self certified one. 
![dhcp-server](https://cloud.githubusercontent.com/assets/1879445/25143672/f05e1ebe-2430-11e7-967f-8e61e7a3b313.png)

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app switched to a new networking library. I'd assume this issue is gone. In case this happens again, please open a new issue. (too many things changed)
