### ISSUE TITLE
Update to Material design step 1: add OC THEME based on Material Design THEME

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#692]
We need to go with the times … @davivel did you already read up on the material design? ;)

**Comment by kalicki** [comment]
News?

**Comment by jancborchardt** [comment]
@MTRichards @rperezb @davivel can we put this on the roadmap? It’s comparable to what iOS 8 compatibility is for the iOS app.

**Comment by kalicki** [comment]
I think Design Material only on Android. IMHO

**Comment by kalicki** [comment]
Material Design on web app? e.g. http://materializecss.com

**Comment by jancborchardt** [comment]
We’re in the Android issue tracker – we’re only talking about Material design on Android. We’ll not change our web app to Material design.

**Comment by davivel** [comment]
Let's do it. 

First step: apply the new THEME. This will be only noticeable in Android 5.0+ devices, since the THEME is not included in the Android Support Library, so in Android 4.x no change should be introduced first.

Let me rename the issue in this sense. I will add some other issues with steps we already thought about. Everybody feel free to comment in any of them, or add others you consider interesting.

**Comment by davivel** [comment]
Since this is the first step, this will require to increase the build target to level 21. We would like to start this internally due to this, but we should be able to share screenshots of the styling while progressing on it, and tweak details of it depending on the comments from everybody - even from @jancborchardt ! ;) .

I'll ping again here when the build target is updated.

**Comment by davivel** [comment]
Some more Material Desing stuff in #983 and #984

**Comment by jancborchardt** [comment]
@davivel great stuff! Provide screenshots as soon as you can. :)

**Comment by AndyScherzinger** [comment]
#1076

**Comment by davivel** [comment]
This part is DONE :)
