### ISSUE TITLE
Share short url

### ISSUE THREAD

**Issue by TeHashX** [owncloud/android#699]
Please enable short url when sharing links from mobile app.
Thanks

**Comment by davivel** [comment]
@jancborchardt , he wants an option to generate *shortened* URLs that are redirected to the normal URL. Something like goo.gl or bit.ly URLs.

**Comment by tobiasKaminsky** [comment]
I think this is only a server part issue.
If the  server would have such an option this would also work directly on our app as the app only presents the url given by the server (afaik).
And of course for security and privacy reason this shortener must not use some third parties like goo.gl or bit.ly

So I suggest to close this issue here and open it in /core?
It should not be too much of work...

**Comment by jancborchardt** [comment]
Yeah, this issue is separate from the mobile apps.
