### ISSUE TITLE
Navigation Drawer: Brainstorming the content

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#757]
I have in lots of issues that a navigation drawer (sidebar) is wanted.
Here we should discuss (maybe with) mockups which functions should be in the navigation drawer and if it is really needed.
The list below is only a teaser of the real issues that should be linked to it, once they are created.

Here is some guideline when to use it and what to include in.
https://developer.android.com/design/patterns/navigation-drawer.html

Content:
 - Accounts with Avatars: List of Accounts expanding after clicking "Accounts"
 - Separation 
 - All Files
 - On device (#407)
 - Favorites
 - Recent
 - Shared with you
 - Shared with others
 - Shared by link
 - Transfers: Shows current transfer, failed transfers, possibility to resume (#765)
 - Separation
 - Settings
   - Help
   - Feedback
   - Log

Then only "account refresh" and "sort" will stay in "three points" on the top right side.

**Comment by tobiasKaminsky** [comment]
![drawer](https://cloud.githubusercontent.com/assets/5836855/5593026/a5b71f62-91ef-11e4-9942-222cf2c250ac.png)

Ladies and Gentleman, we now have a navigation drawer :)
This is just a dummy.
My plan is to move the existing functions to the drawer:
- Accounts with Avatars: Should it possible to change it here directly? I think yes.
- Settings
- Help
- Log

Feedback is more than welcome. Especially @jancborchardt as I not very good at design...

**Comment by jancborchardt** [comment]
NICE! This is really really cool, seriously.

Design-wise, we should follow the [Google Design guidelines for the navigation drawer](http://www.google.com/design/spec/patterns/navigation-drawer.html).

For example more spacing. And having the account switcher drop down when you click on the name (we can add a settings icon right next to the name as a quick link for settings).

We can use the [icons from core](https://github.com/owncloud/core/tree/master/core/img/actions) – I will list which when it’s not middle of the night like now. ;)

The ability to change avatars would be a nice addition, yes.
Help and Log should be items inside Settings (on the bottom), and not have their own dedicated items in the siebar. We shouldn’t cram too much in there. ;)

Best belated Christmas present ever! :dancer:

**Comment by tobiasKaminsky** [comment]
Regarding accounts: I want to do it this way:
![expandable-list-android-right-indicator](https://cloud.githubusercontent.com/assets/5836855/5595004/8a2fcb72-9267-11e4-9a55-1598d85029b0.png)
(from http://theopentutorials.com/tutorials/android/listview/android-expandable-list-view-example)

Maybe "Help", "Log", "Feedback" can also be grouped by this?

**Comment by tobiasKaminsky** [comment]
There is a little problem regarding the "three lines (hamburger):
![drawer1](https://cloud.githubusercontent.com/assets/5836855/5595920/359c72b8-9280-11e4-9ffd-c71c16ba590f.png)
As you can see it is very full in the ActionBar.
Also, currently the owncloud icon is used to browse up the folder hierarchy.
But this is the same method, which is used for the hamburger. 
And I have no solution found to use both. Beside that it would be very difficult to touch this very small hamburger.
So my current idea is to stop using the owncloud icon as "up" and start using it as toggle for the navigation drawer. For browsing there can be used the folder name as it is now.

**Comment by tobiasKaminsky** [comment]
Also there is a problem with android version < 3.0. On this versions there is no support for the "hamburger". It is just not there. But swiping from left to right still opens the drawer.

**Comment by tobiasKaminsky** [comment]
@davivel For your information :)
Feedback is welcome :)

**Comment by tobiasKaminsky** [comment]
Has anybody an idea / url how I can get the user icon of an account?
My idea was to have the icon next to the account in the list...

**Comment by jancborchardt** [comment]
Well, the stuff that is in the »three dots« can go away:
* »Refresh account« can fully vanish in favor of pull to refresh. Yes, it’s not the full account – but currently there’s no real way to distinguish that anyway.
* »Settings« will be on the bottom of the sidebar
* »Sort« should either be in the settings, or above the file list (next to a to-be-introduced search bar).

The upload and new folder action should be behind a [floating action button](http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons) on the bottom right.

Pressing the hamburger icon _as well as_ the ownCloud icon (and swiping from the left edge of screen) should reveal the sidebar. Navigation into parent folders can be done by pressing the folder name and navigating up in the dropdown, or by using the back button.


Does that sound good?

**Comment by tobiasKaminsky** [comment]
Wow. 
These are real big changes.
But I like them :)
I will add them one after the other ;)

**Comment by jancborchardt** [comment]
Yup yup – the road to material design. :) cc @davivel

**Comment by tobiasKaminsky** [comment]
What is the lowest API we have to support?
This is relevant for the floating button...It seems it has to be API 21.

**Comment by tobiasKaminsky** [comment]
Currently state of the art:
![drawer2](https://cloud.githubusercontent.com/assets/5836855/5606134/cffa9858-941f-11e4-9f12-456711a19fc9.png)

**Comment by tobiasKaminsky** [comment]
Regarding "sort": Personally I think this can stay as the only item in the action bar.

**Comment by tobiasKaminsky** [comment]
By the way: All Files / On Device is also working :) :)

![drawer3](https://cloud.githubusercontent.com/assets/5836855/5606668/bd83009c-9439-11e4-990d-603aaca8d5f2.png)

Sorting is for now an entry in the action bar.

**Comment by joeplus** [comment]
Fantastic work so far, huge improvement coming with this! Regarding the user icon: Would it be possible to use the users avatar from the server or is there no method to retrieve it?

Regarding the different accounts: Why not stick to Google's suggestion?
![Account switch](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7c2dhcFRZdzBPWnM/patterns_navdrawer_elevation1.png)
Personally I really like it but that is open for discussion of course. I am not quite sure how difficult this is to implement since there is a [support library](https://developer.android.com/tools/support-library/features.html#v7-appcompat) from Google which should work all the way down to Android 2.1 (API Level 7).

**Comment by jancborchardt** [comment]
Yep, I’d agree with @joeplus that we should stick to the Material design and the look of the new Android Lollipop here. :)

**Comment by tobiasKaminsky** [comment]
But...For me I have different accounts, but no user icon.
Then they would look  all the same?

**Comment by tobiasKaminsky** [comment]
Currently we use android-support-library v4.
Material design is only available in v7. 
@davivel Is it possible to upgrade to v7?

**Comment by joeplus** [comment]
I guess so. The username and / or server would have to be shown as well under the image. So instead of "Jonothan Lee" and "heyfromjonothan@gmail.com" it should probalby say "Tobi$" and on the new line "10.0.2.2".

The images would still look the same for people who don"t change them but has the advantage of showin the correct image for people who use them, like me and my family :-)

**Comment by Kernald** [comment]
Some design notes here (I'm aware it's a work in progress):
 - the drawer should be displayed over the action bar (this means more space for it, nicer on the eye): http://www.google.com/design/spec/patterns/navigation-drawer.html
 - the application icon shouldn't be displayed anymore on the action bar: http://www.google.com/design/spec/layout/structure.html#structure-app-bar
 - if the user didn't set a profile picture, maybe generate one with the first letter of its username, like GMail does? This allows to assign a specific color to these accounts without pictures, to make them more identifiables

Moving to support v7 would allow to drop SherlockActionBar too, using `ActionBarActivity`.

**Comment by jancborchardt** [comment]
> if the user didn't set a profile picture, maybe generate one with the first letter of its username, like GMail does? This allows to assign a specific color to these accounts without pictures, to make them more identifiables

@Kernald yeah we do that in the ownCloud web interface itself already too.

@tobiasKaminsky the algorithm for that is at https://github.com/owncloud/core/blob/master/core/js/placeholder.js – it basically computes a value out of the username, and uses that as hue for the HSL color (Hue-Saturation-Lightness).

**Comment by tobiasKaminsky** [comment]
As @davivel pointed out in another issue, we will support only 4.x in the future.
So then it should be very easy to use the floating buttons.

I like the idea with the first letter of the username and the generated color.

**Comment by davivel** [comment]
Awesome stuff in progress here. Really. I'm full of envy for not coming here 'til now. Great work.

API level 14 should be OK henceforth. Still pending to discuss how to handle this exactly, but officially we do not support Android 2.x or 3.x anymore - though the app is still working in those versions.

About android-support-v7, I don't think that's a problem even for Android 2.2, but I'm not sure, should try it. In any case, go for it.

Another important point of going this way is dropping ActionBarSherlock from the app. It made a really good service, but it's time to move on. 

Congrats, I'm really happy to see this in progress.

**Comment by Kernald** [comment]
@davivel : as its name indicates, the support-v7 is compatible back to API 7. Which is Android 2.1. In theory, it should work fine.

**Comment by tobiasKaminsky** [comment]
Is there something that android/google provides for the account switching?
I have not found something so far... :/

**Comment by joeplus** [comment]
Didn't find anything from Google either. Some other lib/project on GitHub though but I guess you have already seen that. But I believe it requires API Level 10 at a minimum: https://github.com/neokree/MaterialNavigationDrawer

**Comment by tobiasKaminsky** [comment]
@davivel Can we just use the library @joeplus has referenced? This one also uses Calligraphy
Android-UI.

**Comment by davivel** [comment]
Coming back, sorry...

I'll have a look to the library.

**Comment by davivel** [comment]
Well, at first sight it uses other external library. I'd prefer not having chained dependencies in the project. Let's see if we can find some other option..

**Comment by davivel** [comment]
Let's do it.

A first version of the navigation drawer finally came the internal current sprint. @tobiasKaminsky, you already made the work!!

Before we dumbly repeat things, I need to ask you about the work you already did on it. Did you remove ActionBarSherlock in your work, or could you add the drawer without that step?

About the *scope* of what we want to achieve in this sprint (remember: QA will review it, so we need a closure), I would like to let some things out:

- No Material Design consideration for the first version; this includes the styling of the accounts selector and the floating action button.
- We were considering not moving the account selection at all for the first version; but if it's working for you, we could consider include it.
- Android 2.x and 3.x are not supported anymore; if this works there, fine; it doesn't work there, fine; if it's ugly there, just look to other side :)
- Only entries that really go to some view may be in the drawer. For instance, the 'On device' you show in the last picture has no target right now. There's no need to remove it, it's OK let it commented so that it does not appear. Our list right now includes:
  -> Files (or 'All Files', whatever is prefered)
 -> Settings
 -> Logs (only visible in APK built in debug mode, such as the current option in the action bar menu).

About Material Design stuff: it's coming. I will create some issues about how we'd like to take the first steps there. Let's keep the issues small so that they are easier to go 'til the end.

**Comment by jancborchardt** [comment]
Great to see the progress here! Please share screenshots as soon as you can so we can iterate. :)

**Comment by tobiasKaminsky** [comment]
@davivel 
I have updated my (old) local navigation_drawer branch.
ActionBarSherlock is still in my branch. 
Account selection is working for me. But currently a new created account is only shown after a restart of the app. (but this should be some minor changes).
I do not know about the support of 2.x and 3.x, but I doubt it ;)
On Device vs all Files is already working.

I have seen that @masensio is working currently on navigationDrawer in owncloud/android.
What should I do with my branch on my local pc? Push it as a new branch?

**Comment by davivel** [comment]
Yes, please. Maybe we need to change our strategy. The work of María in that branch started getting rid of ActionBarSherlock and we're still with it - we found some unexpected dependencies when added the Android Support Library with the ActionBar.

So, if your drawer is already working even with ActionBarSherlock, maybe we can take it as the starting point and getting rid of ActionBarSherlock with #692 .

**Comment by davivel** [comment]
@tobiasKaminsky , I removed our navigation_drawer branch. We will keep our changes about ActionBarSherlock locally and study if merging them with your navigation_drawer, or just moving them to the first branch about Material Desing.

**Comment by tobiasKaminsky** [comment]
I have updated my branch and committed it directly here.
"On device vs all files" is working
Reloading account list after creating a new account is also working

Next step for me is to implement the account avatar or at least a circle in a calculated color of the username. (there is already some code in it, trying to do this).

**Comment by tobiasKaminsky** [comment]
PR is #987 

Currently state:
![drawer](https://cloud.githubusercontent.com/assets/5836855/7787354/f9d0c05c-0207-11e5-9e30-bf862daf5ea7.jpg)

Remaining problem: Color calculation is not the same as in /core as Integer.parseInt is not working the same in JavaScript and Java.

**Comment by masensio** [comment]
Hi @tobiasKaminsky,

we will review your contribution to add this to the app.
Thanks a lot for the navigation drawer implementation.

**Comment by davivel** [comment]
@tobiasKaminsky , it's great to see the progress of the account selection. @jancborchardt, maybe you would like to make some comments on that design?

From our side, we need to apply some QA to this right now, before it grows too much. We need to grant that the introduction of both the navigation drawer layout and the action bar don't result in unexpected behaviours or bugs in different Android versions. 

We don't want to interfere the progress of the account selection, so we will proceed next way: I will create a separate branch from navigationDrawer_update called navigationDrawer_basic. In it we will hide the account list; unfortunately we don't have enough QA power to test all of it before ending the current sprint, so we will hide it for this _basic branch in order to keep the scope of tests under control. The work on the account list, or on other navigation drawer entries, may go on in navigationDrawer_update.

**Comment by jancborchardt** [comment]
It's very cool! I would just not duplicate the ownCloud logo there, and instead of having a separate line for the name, just show the name behind "Account".

Also, we should really get Material design in so this looks proper modern :)

**Comment by tobiasKaminsky** [comment]
The lower ownCloud logo should be replaced by the avatar of the current account.
If it is not there I want to use the rectangle with the first letter. 
Do you agree?

Regarding Material design: What is missing in the drawer?

**Comment by Kernald** [comment]
The fonts, colors and margins will need a little bit of work to be Material-Design compliant. Also, using icons for every entry would look much better.

See [here](http://www.google.com/design/spec/patterns/navigation-drawer.html) for details.

**Comment by Kernald** [comment]
And Google just releases a design support library. It's worth [taking a look](http://android-developers.blogspot.fr/2015/05/android-design-support-library.html).

**Comment by jancborchardt** [comment]
Any updates on this, especially the Material-style account switcher, the Favorites entry and the »Sjared« entries? @AndyScherzinger @tobiasKaminsky @LukeOwncloud @Kernald

**Comment by AndyScherzinger** [comment]
Not yet. I think we can revive the account switcher implementation done by @tobiasKaminsky and I can rework the drawer implementation for the UI side of the issue. So yeah I kind of have it on my personal roadmap UI wise -what do you say @tobiasKaminsky should I open a new branch (from master) to revive your already been done efforts?

**Comment by tobiasKaminsky** [comment]
So...we did the next step: account switching is back: #1537 
What else is missing here?

**Comment by tobiasKaminsky** [comment]
Closing as this issue is just to big and should be separated in smaller ones if necessary.
