### ISSUE TITLE
File modification date lost when uploading file

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#761]
When uploading a file using the Android app the file creation date is set to the upload date.

Instead, the file creation date of the file from the Android file system should be used.

EDITED by @davivel: the creation date of the file suffers an ancient bug, not sure if fixable; BUT the MODIFICATION DATE of the file should be set with the upload. See https://github.com/owncloud/android/issues/761#issuecomment-115287988

EDITED by @davigonz: 

PR:  https://github.com/owncloud/android/pull/1849
PR android library: https://github.com/owncloud/android-library/pull/140

**Comment by purigarcia** [comment]
I am not sure about this, @LukeOwncloud .
We use what the server give us which is the upload date. In the server, it works that way.

**Comment by LukeOwncloud** [comment]
Mmh... What a bad issue report. No sample, no code. I cannot remember myself what I meant. Closing!

**Comment by davivel** [comment]
No worries, @LukeOwncloud , I do remember, and it's important.

When a file is uploaded the app should tell to the server what is the last modification date of that file so that it matches the reality about when it was modified. The app is not doing it, so the server sets as modification time the upload time (the moment when the copy in the server is created).

This should be considered a bug of the client.

**Comment by fxshpac** [comment]
@davivel With Android client 1.7.2 and OCS 8.1.3 on x86 Ubuntu, I can reproduce the same issue. All the uploaded files are now showing incorrect time stamps now and it makes my other backup software believe all of them have been changed and copy them all over again.

The PC client however works just fine. Can you share some progress on this please? Thx
