### ISSUE TITLE
Use the native Android folder icon

### ISSUE THREAD

**Issue by strugee** [owncloud/android#772]
This will make ownCloud fit in more with the rest of the platform.

**Comment by tobiasKaminsky** [comment]
@strugee 
The icons are the same as the web-frontend.
So this is more a general question: be consistent to the native os or have the same look across all platforms for owncloud...

**Comment by strugee** [comment]
Oops. I seem to have missed this.

@jancborchardt thoughts?

**Comment by jancborchardt** [comment]
We introduced new simpler filetype icons for the web interface which will come with ownCloud 8.2. People should have a uniform experience regarding that across ownCloud, so we should use our nice new filetype icons instead of the default Android ones (actually they are pretty similar anyway).

See https://github.com/owncloud/android/issues/1118 (I’m closing this hence, ok? :)

**Comment by LukeOwncloud** [comment]
I am still curious. What is the native Android folder icon? Are you talking about the material icon: https://www.google.com/design/icons/#ic_folder

**Comment by jancborchardt** [comment]
Yep, that’s the one.
