### ISSUE TITLE
App uses Android proxy setting but ignores exclusions

### ISSUE THREAD

**Issue by nRaecheR** [owncloud/android#793]
# Expected behaviour

The client connects to the local ownCloud instance with a local IP address/name in the local LAN without using the proxy set in the Android WiFi proxy setting when there is an exclusion set for the actual local IP address/name. 
# Actual behaviour

Beginning with 1.6.2 the ownCloud Android client is no longer able to connect to the local IP address/name of an public server with a valid SSL certificate from within the local LAN when there is a proxy set in the system WiFi settings and the local IP address/name of the server is in the exclusion list for this proxy.

After entering the URL an error message appears reads "Ein unbekannter Fehler ist aufgetreten!" with an red exclamation mark. 
The Apache2 log of the server doesn't show any sign of a request from the client, the ownCloud log is empty too. The DNS server logfile shows that the name is resolved properly from the Android devices IP address. 
Using the public server name is still functioning but is much slower because of the routing through the public internet.
All previous clients worked with this setup without problems. Older clients needed the option to ignore the SSL certificate. 
# Steps to reproduce
- Setup a proxy server in the WiFi settings and add an exclusion for the local IP address/name
- Connect to the WiFi AP.
- Start client 1.6.2
- Choose Settings/New account
- Type the local IP address/name into the field "Server address" 
# Environment data

Android version: 4.4.4, 4.4.2
Device model: Nexus 10, Samsung Galaxy S4 
ownCloud app version: 1.6.2 (from F-Droid)
ownCloud version : 7.0.x

**Comment by nRaecheR** [comment]
Unfortunately the problem still exists with 1.7.0. This is very annoying while using in an Enterprise environment where an proxy server is obligatory.

**Comment by MarkyMarkMark** [comment]
Can I just add my name to the list.  In an education environment (where owncloud is very useful) we cannot work without proxy servers and so this renders the program useless.

**Comment by nRaecheR** [comment]
Same with 1.7.1...it seems none of the maintainers care about this showstopper bug.

**Comment by Spindletop** [comment]
A workaround (requiring rebuilding the application) if you don't want to use the system proxy settings in the owncloud android client, is to disable it by removing "applyProxySettings();" call in "OwnCloudClient.java". It workes for my environment which uses proxy authenication for internet access but none for the local network in which owncloud is running.

Well, I even dare to state this should be standard or at least an option, because the owncloud client does not ask for user/password for the proxy...

**Comment by AndyScherzinger** [comment]
Looking at the code @Spindletop mentioned the actual implementation simply sets the proxy if it finds one in applyProxySettings(); but does not check if the System property "http.nonProxyHosts" holding the host pattern matches the uri. 
--> So with the system property it should be possible to write a proxy selector, like shown here: http://madhurtanwani.blogspot.de/2010/05/using-proxyselector-to-take-control-of.html

Unfortunately I don't have proxy environments to write an implementation and give it a test drive since this will most likely need some playing around to get it to work if one wants to write a proper implementation. Or someone can provide me with a setup, than I can give it a try. (Don't bash me I am just a contributor ;)

Besides looking at the code I am not sure the implementation works for http and https or just for http...

Any input, suggestions, environments/setups anyone? @davivel @Spindletop @nRaecheR 

simplest solution might be to just match the uri with the exclude pattern and if it matches simple not callilng the applyProxy method but implementing a ProxySelector seems to me to be the classier solution :D

**Comment by davivel** [comment]
> but does not check if the System property "http.nonProxyHosts" holding the host pattern matches the uri. 

Yes, we missed the exclusion list from the proxy settings. Probably this started to fail for @nRaecheR in the moment we started to consider the proxy settings at all.

>  http and https or just for http...

Works for both, that's tested.

We should put some hurry on this.

**Comment by davivel** [comment]
Sorry, but we need to drop issues from milestone 2.4.0 to get it out next to OC 10 server.

This time we'll move topics to ```backlog``` instead of directly to next release, so that we can schedule 2.5.0 properly.

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
