### ISSUE TITLE
add menu entry for global upload of modified files

### ISSUE THREAD

**Issue by joede** [owncloud/android#877]
In my issue report #876, I reported a bad behaviour of the client. I mentioned a "second step" as a work-around for this. 
The current implementation of the client if more *file oriented*. I have to *download* single files, mark singles files to *stay in sync* und *upload* single files is modified.
To make ths a little bit more handy, the client should allow the upload of all modified files within a directory (from it's global menu). It isn't funny to manually sync / upload a couple of files by opening the context menu of each modified file. ;-)
IMO it is worth thinking about an configuration option, where the user is able to choose between "manually upload modified files", or "automatically upload local changes".

**Comment by davivel** [comment]
Hi, @joede.

I think right now there are some improvements in the app near of what you purpose here.

For instance, now you can manually sync a full folder, what will make that any files locally changed in it are uploaded (if no conflict is found due to changes in the server). The only weak point compared with your proposal would be the root folder, since the app can't browse to its parent to show the context menu on it.

We also just merged (will be released soon) the feature of multi-selection, that allows to sync all the files or folders in the selection with a single action. This will allow to sync the root folder better.

About configuration options, I also think we should give more power to the user. We need to carefully select the options to include, considering possible combinations of network, local storage, and power availability.

Let me invite you to track the progress of #1677, where we are trying to collect some of the main problems and planned solutions around synchronization. Feel free to add any comment there about your ideas.
