### ISSUE TITLE
Remote&Local doesn't delete locally

### ISSUE THREAD

**Issue by Crasha** [owncloud/android#917]
When I want to delete a file both from my phone and the server, it only deletes it on the server and not my phone.

I'm using an LG Nexus 5, running Android 5.0.1.

No custom ROM. All stock.

**Comment by rperezb** [comment]
Thanks for contacting us.

I guess that the file is already downloaded on the device, is this right?

**Comment by Crasha** [comment]
It's a photo that was taken on the mobile device, which was automatically uploaded. I chose to delete local and remote, and it only deleted on the server only.

**Comment by masensio** [comment]
Hi @Crasha 

Could you provide us the bug description using the template https://github.com/owncloud/android/blob/master/issue_template.md ?

Thanks

**Comment by masensio** [comment]
Hi @Crasha,

with your details, I've understood:

STEPS TO REPRODUCE
1. Enable instant uploads
2. Take a photo
3. Photo is uploaded instantly
4. Delete the photo, locally and in server

CURRENT BEHAVIOUR
The photo is deleted in server but not locally. So it appears in the ownCloud Folder Data in your device but no in ownCloud app (Is it right?)

EXPECTED BEHAVIOUR
The photo is neither in ownCloud app nor ownCloud Folder Data.

DEVICE:
Nexus 5, Android 5.0.1

Please, tell me if I'm wrong. 

But with these steps, and 1.7.1 version  I've tried to reproduce the issue with a Nexus 5  (Android 5.1) and the app works properly. 
If you  have more information about this issue, please add here.

Thanks.

**Comment by tobiasKaminsky** [comment]
@Crasha is this still valid?

**Comment by Crasha** [comment]
Since the new update, you cannot delete the picture/video both simultaneously from the local device or server. Instead you can delete it from the server, or delete the file locally. Trying the separate deletions seem to work fine - Deleting from Server only & Deleting locally only.

**Comment by tobiasKaminsky** [comment]
Really? on 2.0.0 a downloaded file can be deleted both from server and local when clicking "yes".

**Comment by davivel** [comment]
Closing. @Crasha , add a comment if want to resume the issue. Thanks.
