### ISSUE TITLE
Android Client : Uploads from device duplicated on Device

### ISSUE THREAD

**Issue by delbydev** [owncloud/android#929]
Hello

Thanks To D Molkentein for closing Desktop client ref #3025

So using the Android ownCloud client to upload photos to the server - absolute godsend but have decided to create an SSH Server on the android device and scp -

However - using the SSH session on Android device I noticed some overhangs of ownCloud that could be better - for storage efficiency on the client device

The original files in DCIM were still there (expected)
But a duplicate copy of the uploaded file was stored in the owncloud "virtual area" (/owncloud/username@owncloudHostHASH/PhotoArea1/PhotoArea2.

Is this normal? If I go ahead remove the files from the owncloud area on the device (to free up space) will this remove process sync on the server? (Believe not)

Apart from using SSH session on the phone to bulk remove- is there an automated routine in the ownCloud client to purge these surplus copies from the device after they have been uploaded ?

Or plans to?

Or do we need to create internal housekeeping mechanisms to purge these files?

Thanks

**Comment by masensio** [comment]
hi @delbydev,

thanks for your feedback.
I think this issue is included in
https://github.com/owncloud/android/issues/819.
Please track it there.

**Comment by delbydev** [comment]
Thanks for feedback @Masensio - Regrettably #819 doesn't cover the scenario described above. 
In summary - when using "upload" to server - files are duplicated in two places on the same android device.  

#929 talks about syncing - but the android client is not syncing - it is a user interface to manage files on the server with the handy facility to upload - not upload and duplicate on device - 

Please reopen

**Comment by masensio** [comment]
Hi @delbydev,

I closed the issue because I thought that the duplication of the files was when you upload the file. Avoid the duplicity of files is an improvement for our app.

But, if the real problem of this issue is the sync process, please describe the issue with the template https://github.com/owncloud/android/blob/master/issue_template.md and reopen it.

Thanks

**Comment by cga** [comment]
The main thing to avoid photos duplication is to be able to select the photos folder you want to sync to owncloud rather than creating the instant upload folder which storage the photos taken by the camera. This photos are also storage in the android photos gallery having the same photos in two locations. If you don't have enough storage in your device you don't really want this
Easier
Being able to select what photos location you want to sync and do not create instant upload folder which lead to duplications
