### ISSUE TITLE
Android Client Does not auto upload ScreenShots taken

### ISSUE THREAD

**Issue by axet** [owncloud/android#95]
Camera upload works well. But Screenshots taken by Volume Down + Power buttons not working.

**Comment by mueller-ma** [comment]
Anything happening here?

**Comment by davigonz** [comment]
@axet @enoch85 @8h2a @mueller-ma 

The Instant uploads feature will be replaced with Camera uploads feature, which is going to be included in the next Android app release (2.6.0). 

To use it, you just have to select a camera folder and the pictures and videos contained there will be automatically uploaded to the folder you select in a period of 15 minutes at most.

In your case, if you want to upload your screenshots, you can set your screenshots folder in this feature and they will be automatically uploaded.

The feature is already available in 2.5.1 beta version, so you can test it now, any feedback is welcome.

**Comment by axet** [comment]
I already wrote an app which helps me to move camera / screenshots to the user specified folder.

https://gitlab.com/axet/android-media-merger

**Comment by davigonz** [comment]
@axet Pretty interesting app 👍 

You opened this issue because screenshots were not being properly detected and uploaded to your ownCloud account, do you still have the same problem?

We are not going to try to detect Screenshots event any more because we cannot trust it, since Android system kills the observer responsible for detect it, but once you move all the screenshots to the folder selected in new Camera uploads feature, the screenshots will be detected as common pictures in a folder and uploaded.

**Comment by axet** [comment]
I'm no longer using owncloud. But for some people move-app can help.

**Comment by davigonz** [comment]
Ok, so I will close it this issue since, as I explained in my previous comment, the screenshots can be uploaded with Camera Uploads feature. Please, reopen this if necessary.
