### ISSUE TITLE
Connection problems with some routers over Wifi

### ISSUE THREAD

**Issue by xAaeEx** [owncloud/android#964]
There are some problems with routers that don't have NAT-Loopback if you want to upload/connect to your self-hosted owncloud.

Example case:
Owncloud local network (ip 192.168.1.100)
Owncloud global dns example.com (ip 90.50.100.30 )

if you want to connect over wifi (local network) to your owncloud and use example.com as url to it, then it will try to connect to 90.50.100.30 and it wont work. NAT-Loopback would lookup which ip you have and remap it to you local ip. 

Is there a possibility to get Advanced settings, on app side, where I can set the SSID (Wifi name) and the local ip to be able to connect through Wifi if I am connected to it?
I saw that on another app called Transdrone (see screenshots attached).
What do you guys think?

![screenshot_2015-04-28-10-41-45](https://cloud.githubusercontent.com/assets/8521598/7365953/10b90eb4-ed95-11e4-9e18-2c3ecc2f18b8.png)
![screenshot_2015-04-28-10-41-53](https://cloud.githubusercontent.com/assets/8521598/7365954/10b9683c-ed95-11e4-8dc1-72f6245cfd91.png)

**Comment by untitaker** [comment]
My router also doesn't support NAT-loopback. I ended up running my own DNS-server in the local network, which spoofs the DNS entry to point to the local IP. That was extremely painful, but I don't think that this should be solved by each app individually.

**Comment by davivel** [comment]
I don't think we have the time to add something like this. As @untitaker told, this is not an issue that should be solved in the application level. If accessing to a server through different IPs is needed, the network should be configured to do so. That's why NAT-loopback exists, because it is a network issue. An as @untitaker did, installing a custom DNS server in your local network should do the work. In the end, mapping domain names to IP addresses is the motivation for DNS existance.

I'm sorry, but won't be done.
