### ISSUE TITLE
More informative error Feedback is essential

### ISSUE THREAD

**Issue by tilllt** [owncloud/android#966]
Hi,

i spent almost an hour going through my server logs and owncloud log, checking if WebDAV is working ok etc. Only to find out that the reason for uploads from my phone to my owncloud failing was just a ssl certificate problem. while it is correct, that an upload SHOULD fail for security reasons if there is a problem with the certificate, i would assume that the client should also give a hint about the problem.

The ONLY feedback visible in the Android Client right now is "Upload Failed".

cheers,t.

______

BUGS & IMPROVEMENTS

- [ ] Shorter error message https://github.com/owncloud/android/issues/966#issuecomment-273114245 [READY_TO_TEST]

**Comment by davivel** [comment]
You are totally right. Indeed, reporting problems with SSL certificates worked better before, and we need to review why.

Thanks for reporting.

**Comment by trs998** [comment]
Android makes a notification in the notification pulldown for the owncloud app's "upload failed" event.

When tapped, this merely returns the user to the he owncloud app, looking at a file which is not uploaded. This screen (IMHO) should also contain the error information - ideally a summary and then a much more detailed message - which would logically be what the user expects when tapping "upload failed" - the answer should be showing a screen something like:

 file X failed to upload, with error Y. Further detail: Y arose from Z

X is filename and path
Y should be googleable error (error SSL_VERIFICATION_FAILED )
Z should be information useful to a server admin (SSL certificate not trusted due to revocation information fetch failure, for example)

**Comment by tilllt** [comment]
Additionally it should give you an option (maybe by re-entering password) to sync anyways, if it is a certificate problem. If you are one the road ad definitely need a file, a minor certificate error might be acceptable. In my case it was merely a problem in the trust chain, my certificate was fine and didn't have to be changed.

Am 6. Mai 2015 09:45:13 MESZ, schrieb trs998 <notifications@github.com>:
>Android makes a notification in the notification pulldown for the
>owncloud app's "upload failed" event.
>
>When tapped, this merely returns the user to the he owncloud app,
>looking at a file which is not uploaded. This screen (IMHO) should also
>contain the error information - ideally a summary and then a much more
>detailed message - which would logically be what the user expects when
>tapping "upload failed" - the answer should be showing a screen
>something like:
>
> file X failed to upload, with error Y. Further detail: Y arose from Z
>
>X is filename and path
>Y should be googleable error (error SSL_VERIFICATION_FAILED )
>Z should be information useful to a server admin (SSL certificate not
>trusted due to revocation information fetch failure, for example) 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/android/issues/966#issuecomment-99357795

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
> Additionally it should give you an option (maybe by re-entering password) to sync anyways, if it is a certificate problem.

From a security perspective this is not a good idea. Users tend to click through all warnings they see when possible.
So no it should not be possible. Security by design. Period. 
If the web server is not configured correctly, it must be fixed.

> a minor certificate error might be acceptable

The issue is just that the app can't detect whether this is a "minor" certificate error and also these errors make MITM attacks possible.

**Comment by tilllt** [comment]
Since probably most users run their own owncloud server, i think it should be left to the decision of the admin / user to decide what to do. if i am abroad and cannot access my own owncloud installation because the certificate is expired, i'd appreciate if i can decide myself how to handle that situation.

btw you missed the point: the android client failed silently without giving any clue why. turned out an expired certificate was the reason, so it should

1. say so
2. let me decide what to do.

**Comment by rugk** [comment]
Yes it should do 1., but not really 2. At least not in a very, very hard way.
Skipping security errors is bad. So probably a more-or-less hidden "I know what I am doing" mode in the settings could enable such a skipping, but otherwise there should be no possibility to skip such errors.
Because I think there are also non-admin users using OwnCloud. (When you share your OwnCLoud with friends e.g.)

**Comment by davivel** [comment]
Proposal of fix in #1881; things done:

 - when uploads fail due to an untrusted server certificate, a specific error is shown, both in the notification and in list of failed uploads (no more "Unkown error" for this situation";

- HTTP status phrase is saved in RemoteOperationResults to use as a fallback when ErrorMessageAdapter does not know a better user message for the result; this message will be used instead of the current "Unknown error" for HTTP error responses that are currently not translated to a localized error message in the app;

- Toasts have been replaced with Snackbars where possible (Toasts created by Services or Activities finishing need to remain that way)

Not done:

- ask the user to accept untrusted certificate clicking on a failed upload in the list of uploads; that is already asked whenever the user tries to browse through the untrusted account; ftm might be enough.

**Comment by jesmrec** [comment]
Improvement:

The error message in the uploads view is shown using two raws. A shorter message would be easy to read in terms of UX, so the other errors is this view are short messages and not sentences.

<img width="332" alt="screen shot 2017-01-17 at 12 23 20" src="https://cloud.githubusercontent.com/assets/14894746/22018616/f1dd4dc8-dcaf-11e6-88c4-81f07fd06f4a.png">

Some examples:

`Certificate not trusted`
`Certificate expired`
`Certificate not valid`

@davivel

**Comment by davivel** [comment]
Checking improvement.

**Comment by jesmrec** [comment]
Approved 

CC @davivel @davigonz
