### ISSUE TITLE
General usability issues

### ISSUE THREAD

**Issue by mase76** [owncloud/android#988]
Hi!
I think, the android app should work exactly like the desktop app. All files and folders
added to the owncloud folder should be uploaded and synced automatically. Marking
single files to be kept in sync is very complicated. And every change made locally on the
device should be synced directly, or an option for that should be added. Overall a sync
interval should be configurable.

**Comment by gerroon** [comment]
They have to explain this sync stuff, it is very confusing, claiming that this is a sync app is a bit false advertisement. It is a nice app, however it is no sync app by any standard.

**Comment by davivel** [comment]
This issue is too general. All the topics you mention are already registered in the repository, most of them under the labels 'sync' or 'storage'. Let me invite you to check them and track their state there.

https://github.com/owncloud/android/labels/sync
https://github.com/owncloud/android/labels/storage
